/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3/include   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_sdl_wasm/@mplatform@ssdl@ssdl_platform.nim.c.o /workspaces/Storie/nimcache_sdl_wasm/@mplatform@ssdl@ssdl_platform.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "SDL3/SDL_events.h"
#include <string.h>
#include "SDL3/SDL_render.h"
#include "SDL3/SDL_rect.h"
#include "SDL3/SDL_pixels.h"
#include "SDL3_ttf/SDL_ttf.h"
#include "SDL3/SDL_surface.h"
#include "SDL3/SDL_init.h"
#include "SDL3/SDL_error.h"
#include "SDL3/SDL.h"
#include "SDL3/SDL_video.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__sDelIiIV63LMKvgOIHN9cyw tySequence__sDelIiIV63LMKvgOIHN9cyw;
typedef struct tySequence__sDelIiIV63LMKvgOIHN9cyw_Content tySequence__sDelIiIV63LMKvgOIHN9cyw_Content;
typedef struct tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg;
typedef struct tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw;
typedef struct tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_Buffer__Z2JRNesPVTeaRmoAdqiepA tyObject_Buffer__Z2JRNesPVTeaRmoAdqiepA;
typedef struct tySequence__cKlYxzOU8LeDpPZNqgOEWQ tySequence__cKlYxzOU8LeDpPZNqgOEWQ;
typedef struct tySequence__cKlYxzOU8LeDpPZNqgOEWQ_Content tySequence__cKlYxzOU8LeDpPZNqgOEWQ_Content;
typedef struct tyObject_Cell__iX167sFbQmcbAKdeH6G60A tyObject_Cell__iX167sFbQmcbAKdeH6G60A;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Style__laaxTIpM6pbqv2olYLQHUg tyObject_Style__laaxTIpM6pbqv2olYLQHUg;
typedef struct tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tySequence__sDelIiIV63LMKvgOIHN9cyw {
  NI len; tySequence__sDelIiIV63LMKvgOIHN9cyw_Content* p;
};
typedef NU8 tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA;
typedef NU8 tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA;
typedef NU8 tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw;
struct tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw {
	tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA kind;
union{
	struct {
	NI keyCode;
	tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA keyAction;
} _kind_1;
	struct {
	tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw button;
	NI mouseX;
	NI mouseY;
	tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA action;
} _kind_2;
	struct {
	NI moveX;
	NI moveY;
} _kind_3;
	struct {
	NI newWidth;
	NI newHeight;
} _kind_4;
};
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg {
	RootObj Sup;
};
struct tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg {
	tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg Sup;
	SDL_Window* window;
	SDL_Renderer* renderer;
	NF targetFps;
	NI cellWidth;
	NI cellHeight;
	TTF_Font* font;
	NIM_BOOL running;
};
struct tySequence__cKlYxzOU8LeDpPZNqgOEWQ {
  NI len; tySequence__cKlYxzOU8LeDpPZNqgOEWQ_Content* p;
};
struct tyObject_Buffer__Z2JRNesPVTeaRmoAdqiepA {
	NI width;
	NI height;
	tySequence__cKlYxzOU8LeDpPZNqgOEWQ cells;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ {
	NU8 r;
	NU8 g;
	NU8 b;
};
struct tyObject_Style__laaxTIpM6pbqv2olYLQHUg {
	tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ fg;
	tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ bg;
	NIM_BOOL bold;
};
struct tyObject_Cell__iX167sFbQmcbAKdeH6G60A {
	NimStringV2 ch;
	tyObject_Style__laaxTIpM6pbqv2olYLQHUg style;
	NIM_BOOL transparent;
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tySequence__sDelIiIV63LMKvgOIHN9cyw_Content { NI cap; tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw data[SEQ_DECL_SIZE]; };
struct tySequence__cKlYxzOU8LeDpPZNqgOEWQ_Content { NI cap; tyObject_Cell__iX167sFbQmcbAKdeH6G60A data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZsdlZsdl95platform_u193)(tySequence__sDelIiIV63LMKvgOIHN9cyw* x_p0, tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___platformZsdlZsdl95platform_u245)(tySequence__sDelIiIV63LMKvgOIHN9cyw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95platform_u248)(tySequence__sDelIiIV63LMKvgOIHN9cyw dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__PlyfjOI6Unt59cWQnMeZGrg_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__OsWUmvNw5UIqmxlnvse82Q_15 = { 17 | NIM_STRLIT_FLAG, "SDL_Init failed: " };
static const NimStringV2 TM__OsWUmvNw5UIqmxlnvse82Q_16 = {17, (NimStrPayload*)&TM__OsWUmvNw5UIqmxlnvse82Q_15};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__OsWUmvNw5UIqmxlnvse82Q_17 = { 25 | NIM_STRLIT_FLAG, "SDL_CreateWindow failed: " };
static const NimStringV2 TM__OsWUmvNw5UIqmxlnvse82Q_18 = {25, (NimStrPayload*)&TM__OsWUmvNw5UIqmxlnvse82Q_17};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__OsWUmvNw5UIqmxlnvse82Q_19 = { 27 | NIM_STRLIT_FLAG, "SDL_CreateRenderer failed: " };
static const NimStringV2 TM__OsWUmvNw5UIqmxlnvse82Q_20 = {27, (NimStrPayload*)&TM__OsWUmvNw5UIqmxlnvse82Q_19};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__OsWUmvNw5UIqmxlnvse82Q_22 = { 69 | NIM_STRLIT_FLAG, "WASM build: Font loading not yet implemented, text rendering disabled" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__OsWUmvNw5UIqmxlnvse82Q_21 = {{69, (NimStrPayload*)&TM__OsWUmvNw5UIqmxlnvse82Q_22}}
;
extern NIM_BOOL nimInErrorMode__system_u4277;
extern TFrame* framePtr__system_u2675;
static NIM_CONST NU32 TM__OsWUmvNw5UIqmxlnvse82Q_14[3] = {3701606400, 3070229760, 1553959936};
N_LIB_PRIVATE TNimTypeV2 NTIv2__PlyfjOI6Unt59cWQnMeZGrg_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg), .align = (NI16) NIM_ALIGNOF(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg), .depth = 2, .display = TM__OsWUmvNw5UIqmxlnvse82Q_14, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4277);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == ((NI)(-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == ((NI)-1));
LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_FALSE;
		(*res_p2) = (NI)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2675 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2675).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2675;
	framePtr__system_u2675 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4495();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2675 = (*framePtr__system_u2675).prev;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sDelIiIV63LMKvgOIHN9cyw, pollEvents__platformZsdlZsdl95platform_u183)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0) {
	tySequence__sDelIiIV63LMKvgOIHN9cyw result;
	tySequence__sDelIiIV63LMKvgOIHN9cyw events_1;
	SDL_Event sdlEvent_1;
NIM_BOOL* nimErr_;
	nimfr_("pollEvents", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	events_1.len = 0; events_1.p = NIM_NIL;
	nimlf_(145, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	events_1.len = 0; events_1.p = (tySequence__sDelIiIV63LMKvgOIHN9cyw_Content*) newSeqPayload(0, sizeof(tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw), NIM_ALIGNOF(tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw));
	nimZeroMem((void*)(&sdlEvent_1), sizeof(SDL_Event));
	{
		nimln_(148);		while (1) {
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = SDL_PollEvent((&sdlEvent_1));
			if (!T4_) goto LA3;
			nimln_(149);			switch (sdlEvent_1.type) {
			case ((SDL_EventType)256):
			{
				nimln_(151);				(*p_p0).running = NIM_FALSE;
			}
			break;
			case ((SDL_EventType)768):
			{
				SDL_KeyboardEvent key_1;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T7_;
				nimln_(156);				key_1 = sdlEvent_1.key;
				nimln_(158);				T7_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)0);
				T7_._kind_1.keyCode = ((NI) (key_1.key));
				T7_._kind_1.keyAction = ((tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA)0);
				add__platformZsdlZsdl95platform_u193((&events_1), T7_);
			}
			break;
			case ((SDL_EventType)769):
			{
				SDL_KeyboardEvent key_2;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T9_;
				nimln_(165);				key_2 = sdlEvent_1.key;
				nimln_(166);				T9_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)0);
				T9_._kind_1.keyCode = ((NI) (key_2.key));
				T9_._kind_1.keyAction = ((tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA)1);
				add__platformZsdlZsdl95platform_u193((&events_1), T9_);
			}
			break;
			case ((SDL_EventType)1025):
			{
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD_;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__2;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__3;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__4;
				SDL_MouseButtonEvent mouse_1;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw btn_1;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T15_;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_2;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_3;
				colontmpD_ = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__2 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__3 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__4 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				nimln_(173);				mouse_1 = sdlEvent_1.button;
				nimln_(174);				switch (mouse_1.button) {
				case ((NU8)1):
				{
					nimln_(175);					colontmpD_ = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0);
					btn_1 = colontmpD_;
				}
				break;
				case ((NU8)2):
				{
					nimln_(176);					colontmpD__2 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)1);
					btn_1 = colontmpD__2;
				}
				break;
				case ((NU8)3):
				{
					nimln_(177);					colontmpD__3 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)2);
					btn_1 = colontmpD__3;
				}
				break;
				default:
				{
					nimln_(178);					colontmpD__4 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)3);
					btn_1 = colontmpD__4;
				}
				break;
				}
				nimln_(179);				T15_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)1);
				T15_._kind_2.button = btn_1;
				nimln_(182);				if ((((NI) (mouse_1.x))) < ((NI)(-2147483647 -1)) || (((NI) (mouse_1.x))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (mouse_1.x)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellWidth == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (mouse_1.x))), (*p_p0).cellWidth, &TM__OsWUmvNw5UIqmxlnvse82Q_2)) { raiseOverflow(); goto LA1_;
				};
				T15_._kind_2.mouseX = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_2);
				nimln_(183);				if ((((NI) (mouse_1.y))) < ((NI)(-2147483647 -1)) || (((NI) (mouse_1.y))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (mouse_1.y)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellHeight == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (mouse_1.y))), (*p_p0).cellHeight, &TM__OsWUmvNw5UIqmxlnvse82Q_3)) { raiseOverflow(); goto LA1_;
				};
				T15_._kind_2.mouseY = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_3);
				T15_._kind_2.action = ((tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA)0);
				nimln_(179);				add__platformZsdlZsdl95platform_u193((&events_1), T15_);
			}
			break;
			case ((SDL_EventType)1026):
			{
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__5;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__6;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__7;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw colontmpD__8;
				SDL_MouseButtonEvent mouse_2;
				tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw btn_2;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T21_;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_4;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_5;
				colontmpD__5 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__6 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__7 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				colontmpD__8 = (tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0;
				nimln_(188);				mouse_2 = sdlEvent_1.button;
				nimln_(189);				switch (mouse_2.button) {
				case ((NU8)1):
				{
					nimln_(190);					colontmpD__5 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)0);
					btn_2 = colontmpD__5;
				}
				break;
				case ((NU8)2):
				{
					nimln_(191);					colontmpD__6 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)1);
					btn_2 = colontmpD__6;
				}
				break;
				case ((NU8)3):
				{
					nimln_(192);					colontmpD__7 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)2);
					btn_2 = colontmpD__7;
				}
				break;
				default:
				{
					nimln_(193);					colontmpD__8 = ((tyEnum_MouseButton__hoFVb5gMzxTkKTC4B9boKGw)3);
					btn_2 = colontmpD__8;
				}
				break;
				}
				nimln_(194);				T21_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)1);
				T21_._kind_2.button = btn_2;
				nimln_(197);				if ((((NI) (mouse_2.x))) < ((NI)(-2147483647 -1)) || (((NI) (mouse_2.x))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (mouse_2.x)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellWidth == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (mouse_2.x))), (*p_p0).cellWidth, &TM__OsWUmvNw5UIqmxlnvse82Q_4)) { raiseOverflow(); goto LA1_;
				};
				T21_._kind_2.mouseX = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_4);
				nimln_(198);				if ((((NI) (mouse_2.y))) < ((NI)(-2147483647 -1)) || (((NI) (mouse_2.y))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (mouse_2.y)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellHeight == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (mouse_2.y))), (*p_p0).cellHeight, &TM__OsWUmvNw5UIqmxlnvse82Q_5)) { raiseOverflow(); goto LA1_;
				};
				T21_._kind_2.mouseY = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_5);
				T21_._kind_2.action = ((tyEnum_InputAction__eXdHrkKkYjghItBajOjCpA)1);
				nimln_(194);				add__platformZsdlZsdl95platform_u193((&events_1), T21_);
			}
			break;
			case ((SDL_EventType)1024):
			{
				SDL_MouseMotionEvent motion_1;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T23_;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_6;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_7;
				nimln_(203);				motion_1 = sdlEvent_1.motion;
				nimln_(204);				T23_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)2);
				nimln_(206);				if ((((NI) (motion_1.x))) < ((NI)(-2147483647 -1)) || (((NI) (motion_1.x))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (motion_1.x)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellWidth == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (motion_1.x))), (*p_p0).cellWidth, &TM__OsWUmvNw5UIqmxlnvse82Q_6)) { raiseOverflow(); goto LA1_;
				};
				T23_._kind_3.moveX = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_6);
				nimln_(207);				if ((((NI) (motion_1.y))) < ((NI)(-2147483647 -1)) || (((NI) (motion_1.y))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (motion_1.y)), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto LA1_;
				}
				if ((*p_p0).cellHeight == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt((((NI) (motion_1.y))), (*p_p0).cellHeight, &TM__OsWUmvNw5UIqmxlnvse82Q_7)) { raiseOverflow(); goto LA1_;
				};
				T23_._kind_3.moveY = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_7);
				nimln_(204);				add__platformZsdlZsdl95platform_u193((&events_1), T23_);
			}
			break;
			case ((SDL_EventType)517):
			{
				SDL_WindowEvent window_1;
				tyObject_InputEvent__csaN5g9cp8Z5oSiJot1vMCw T25_;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_8;
				NI TM__OsWUmvNw5UIqmxlnvse82Q_9;
				nimln_(211);				window_1 = sdlEvent_1.window;
				nimln_(212);				T25_.kind = ((tyEnum_InputEventKind__gF0wnRP9cFw1fRaSQLaYO9aA)3);
				nimln_(214);				if ((*p_p0).cellWidth == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt(((NI) (window_1.data1)), (*p_p0).cellWidth, &TM__OsWUmvNw5UIqmxlnvse82Q_8)) { raiseOverflow(); goto LA1_;
				};
				T25_._kind_4.newWidth = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_8);
				nimln_(215);				if ((*p_p0).cellHeight == 0){ raiseDivByZero(); goto LA1_;
				}
				if (nimDivInt(((NI) (window_1.data2)), (*p_p0).cellHeight, &TM__OsWUmvNw5UIqmxlnvse82Q_9)) { raiseOverflow(); goto LA1_;
				};
				T25_._kind_4.newHeight = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_9);
				nimln_(212);				add__platformZsdlZsdl95platform_u193((&events_1), T25_);
			}
			break;
			default:
			{
			}
			break;
			}
		} LA3: ;
	}
	nimln_(221);	nimln_(143);	nimln_(221);	result = events_1;
	nimln_(145);	eqwasMoved___platformZsdlZsdl95platform_u245((&events_1));
	eqdestroy___platformZsdlZsdl95platform_u248(events_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___platformZsdlZsdl95platform_u248(events_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, display__platformZsdlZsdl95platform_u599)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0, tyObject_Buffer__Z2JRNesPVTeaRmoAdqiepA* current_p1, tyObject_Buffer__Z2JRNesPVTeaRmoAdqiepA* previous_p2) {
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T31_;
	nimfr_("display", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
{	nimln_(233);	T1_ = (NIM_BOOL)0;
	T1_ = SDL_SetRenderDrawColor((*p_p0).renderer, ((NU8)0), ((NU8)0), ((NU8)0), ((NU8)255));
	(void)(T1_);
	nimln_(234);	T2_ = (NIM_BOOL)0;
	T2_ = SDL_RenderClear((*p_p0).renderer);
	(void)(T2_);
	{
		NI y_1;
		NI i_1;
		y_1 = (NI)0;
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_1 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__OsWUmvNw5UIqmxlnvse82Q_13;
				if (!(i_1 < (*current_p1).height)) goto LA5;
				nimlf_(238, "/workspaces/Storie/platform/sdl/sdl_platform.nim");				y_1 = i_1;
				{
					NI x_1;
					NI i_2;
					x_1 = (NI)0;
					nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");					i_2 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NI TM__OsWUmvNw5UIqmxlnvse82Q_12;
							if (!(i_2 < (*current_p1).width)) goto LA8;
							nimlf_(239, "/workspaces/Storie/platform/sdl/sdl_platform.nim");							x_1 = i_2;
							{
								tyObject_Cell__iX167sFbQmcbAKdeH6G60A cell_1;
								NI idx_1;
								NI TM__OsWUmvNw5UIqmxlnvse82Q_10;
								NI TM__OsWUmvNw5UIqmxlnvse82Q_11;
								tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ bg_1;
								NIM_BOOL T14_;
								SDL_FRect rect_1;
								NIM_BOOL T15_;
								nimZeroMem((void*)(&cell_1), sizeof(tyObject_Cell__iX167sFbQmcbAKdeH6G60A));
								nimln_(240);								if (nimMulInt(y_1, (*current_p1).width, &TM__OsWUmvNw5UIqmxlnvse82Q_10)) { raiseOverflow(); goto BeforeRet_;
								};
								if (nimAddInt((NI)(TM__OsWUmvNw5UIqmxlnvse82Q_10), x_1, &TM__OsWUmvNw5UIqmxlnvse82Q_11)) { raiseOverflow(); goto BeforeRet_;
								};
								idx_1 = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_11);
								nimln_(241);								if (idx_1 < 0 || idx_1 >= (*current_p1).cells.len){ raiseIndexError2(idx_1,(*current_p1).cells.len-1); goto BeforeRet_;
								}
								cell_1 = (*current_p1).cells.p->data[idx_1];
								nimln_(244);								{
									if (!cell_1.transparent) goto LA12_;
									nimln_(245);									goto LA9;
								}
LA12_: ;
								nimln_(248);								bg_1 = cell_1.style.bg;
								nimln_(249);								T14_ = (NIM_BOOL)0;
								T14_ = SDL_SetRenderDrawColor((*p_p0).renderer, bg_1.r, bg_1.g, bg_1.b, ((NU8)255));
								(void)(T14_);
								nimln_(251);								nimln_(252);								rect_1.x = ((float) (((NF)(((NF) (x_1))) * (NF)(((NF) ((*p_p0).cellWidth))))));
								nimln_(253);								rect_1.y = ((float) (((NF)(((NF) (y_1))) * (NF)(((NF) ((*p_p0).cellHeight))))));
								rect_1.w = ((float) (((NF) ((*p_p0).cellWidth))));
								rect_1.h = ((float) (((NF) ((*p_p0).cellHeight))));
								nimln_(257);								T15_ = (NIM_BOOL)0;
								T15_ = SDL_RenderFillRect((*p_p0).renderer, (&rect_1));
								(void)(T15_);
								nimln_(260);								{
									NIM_BOOL T18_;
									tyObject_Color__Hqll1DUMMlXu7Cgaj9bbfpQ fg_1;
									SDL_Color color_1;
									SDL_Surface* surface_1;
									T18_ = (NIM_BOOL)0;
									T18_ = (((NI)0) < cell_1.ch.len);
									if (!(T18_)) goto LA19_;
									T18_ = !(((*p_p0).font == 0));
LA19_: ;
									if (!T18_) goto LA20_;
									nimln_(261);									fg_1 = cell_1.style.fg;
									nimln_(262);									color_1.r = fg_1.r;
									color_1.g = fg_1.g;
									color_1.b = fg_1.b;
									color_1.a = ((NU8)255);
									nimln_(265);									surface_1 = TTF_RenderText_Solid((*p_p0).font, nimToCStringConv(cell_1.ch), ((size_t) (cell_1.ch.len)), color_1);
									nimln_(266);									{
										SDL_Texture* texture_1;
										if (!!((surface_1 == 0))) goto LA24_;
										nimln_(268);										texture_1 = SDL_CreateTextureFromSurface((*p_p0).renderer, surface_1);
										nimln_(269);										{
											NIM_BOOL T30_;
											if (!!((texture_1 == 0))) goto LA28_;
											nimln_(271);											T30_ = (NIM_BOOL)0;
											T30_ = SDL_RenderTexture((*p_p0).renderer, texture_1, ((SDL_FRect*) NIM_NIL), (&rect_1));
											(void)(T30_);
											nimln_(272);											SDL_DestroyTexture(texture_1);
										}
LA28_: ;
										nimln_(273);										SDL_DestroySurface(surface_1);
									}
LA24_: ;
								}
LA20_: ;
							} LA9: ;
							nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");							if (nimAddInt(i_2, ((NI)1), &TM__OsWUmvNw5UIqmxlnvse82Q_12)) { raiseOverflow(); goto BeforeRet_;
							};
							i_2 = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_12);
						} LA8: ;
					}
				}
				if (nimAddInt(i_1, ((NI)1), &TM__OsWUmvNw5UIqmxlnvse82Q_13)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_13);
			} LA5: ;
		}
	}
	nimlf_(275, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	T31_ = (NIM_BOOL)0;
	T31_ = SDL_RenderPresent((*p_p0).renderer);
	(void)(T31_);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(364, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	nimlf_(518, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimlf_(521, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZsdlZsdl95platform_u761)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg** dest_p0, tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* src_p1) {
	tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init__platformZsdlZsdl95platform_u18)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("init", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	{
		int T3_;
		NimStringV2 colontmpD_;
		tyArray__Re75IspeoxXy2oCZHwcRrA T7_;
		NCSTRING T8_;
		T3_ = (int)0;
		T3_ = SDL_Init((NU32)(SDL_INIT_VIDEO | SDL_INIT_EVENTS));
		if (!(T3_ < ((NI32)0))) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(35);		T7_[0] = TM__OsWUmvNw5UIqmxlnvse82Q_16;
		T8_ = (NCSTRING)0;
		T8_ = SDL_GetError();
		colontmpD_ = cstrToNimstr(T8_);
		T7_[1] = colontmpD_;
		echoBinSafe(T7_, 2);
		nimln_(36);		nimln_(31);		nimln_(36);		result = NIM_FALSE;
		nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		goto BeforeRet_;
		{
			LA6_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimlf_(38, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	(*p_p0).window = SDL_CreateWindow("Storie SDL3", ((int)1024), ((int)768), SDL_WINDOW_RESIZABLE);
	nimln_(45);	{
		NimStringV2 colontmpD__2;
		tyArray__Re75IspeoxXy2oCZHwcRrA T16_;
		NCSTRING T17_;
		if (!((*p_p0).window == 0)) goto LA13_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(46);		T16_[0] = TM__OsWUmvNw5UIqmxlnvse82Q_18;
		T17_ = (NCSTRING)0;
		T17_ = SDL_GetError();
		colontmpD__2 = cstrToNimstr(T17_);
		T16_[1] = colontmpD__2;
		echoBinSafe(T16_, 2);
		nimln_(47);		SDL_Quit();
		nimln_(48);		nimln_(31);		nimln_(48);		result = NIM_FALSE;
		nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		goto BeforeRet_;
		{
			LA15_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA13_: ;
	nimlf_(50, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	(*p_p0).renderer = SDL_CreateRenderer((*p_p0).window, ((NCSTRING) NIM_NIL));
	nimln_(52);	{
		NimStringV2 colontmpD__3;
		tyArray__Re75IspeoxXy2oCZHwcRrA T25_;
		NCSTRING T26_;
		if (!((*p_p0).renderer == 0)) goto LA22_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(53);		T25_[0] = TM__OsWUmvNw5UIqmxlnvse82Q_20;
		T26_ = (NCSTRING)0;
		T26_ = SDL_GetError();
		colontmpD__3 = cstrToNimstr(T26_);
		T25_[1] = colontmpD__3;
		echoBinSafe(T25_, 2);
		nimln_(54);		SDL_DestroyWindow((*p_p0).window);
		nimln_(55);		SDL_Quit();
		nimln_(56);		nimln_(31);		nimln_(56);		result = NIM_FALSE;
		nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
		goto BeforeRet_;
		{
			LA24_:;
		}
		{
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA22_: ;
	nimlf_(92, "/workspaces/Storie/platform/sdl/sdl_platform.nim");	echoBinSafe(TM__OsWUmvNw5UIqmxlnvse82Q_21, 1);
	nimln_(93);	(*p_p0).font = ((TTF_Font*) NIM_NIL);
	nimln_(98);	(*p_p0).cellWidth = ((NI)1);
	nimln_(99);	(*p_p0).cellHeight = ((NI)1);
	nimln_(104);	(*p_p0).running = NIM_TRUE;
	nimln_(106);	nimln_(31);	nimln_(106);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setTargetFps__platformZsdlZsdl95platform_u706)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0, NF fps_p1) {
	nimfr_("setTargetFps", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
	nimln_(283);	(*p_p0).targetFps = fps_p1;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, getSize__platformZsdlZsdl95platform_u132)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	int w_1;
	int h_1;
	NIM_BOOL T1_;
	NI colontmp_;
	NI TM__OsWUmvNw5UIqmxlnvse82Q_23;
	NI colontmp__2;
	NI TM__OsWUmvNw5UIqmxlnvse82Q_24;
	nimfr_("getSize", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
	w_1 = (int)0;
	h_1 = (int)0;
	nimln_(127);	T1_ = (NIM_BOOL)0;
	T1_ = SDL_GetWindowSize((*p_p0).window, (&w_1), (&h_1));
	(void)(T1_);
	nimln_(128);	if ((*p_p0).cellWidth == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(((NI) (w_1)), (*p_p0).cellWidth, &TM__OsWUmvNw5UIqmxlnvse82Q_23)) { raiseOverflow(); goto BeforeRet_;
	};
	colontmp_ = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_23);
	if ((*p_p0).cellHeight == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(((NI) (h_1)), (*p_p0).cellHeight, &TM__OsWUmvNw5UIqmxlnvse82Q_24)) { raiseOverflow(); goto BeforeRet_;
	};
	colontmp__2 = (NI)(TM__OsWUmvNw5UIqmxlnvse82Q_24);
	nimln_(124);	nimln_(128);	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown__platformZsdlZsdl95platform_u121)(tyObject_SdlPlatformcolonObjectType___PlyfjOI6Unt59cWQnMeZGrg* p_p0) {
	nimfr_("shutdown", "/workspaces/Storie/platform/sdl/sdl_platform.nim");
	nimln_(110);	{
		if (!!(((*p_p0).font == 0))) goto LA3_;
		nimln_(111);		TTF_CloseFont((*p_p0).font);
	}
LA3_: ;
	nimln_(114);	{
		if (!!(((*p_p0).renderer == 0))) goto LA7_;
		nimln_(115);		SDL_DestroyRenderer((*p_p0).renderer);
	}
LA7_: ;
	nimln_(116);	{
		if (!!(((*p_p0).window == 0))) goto LA11_;
		nimln_(117);		SDL_DestroyWindow((*p_p0).window);
	}
LA11_: ;
	nimln_(118);	SDL_Quit();
	popFrame();
}
