/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib_full/@mplatform@sraylib@sraylib_render3d.nim.c.o /workspaces/Storie/nimcache_wasm_raylib_full/@mplatform@sraylib@sraylib_render3d.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "raylib.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw;
typedef struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw;
typedef struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ;
typedef struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content tySequence__uFLLGQVsiasALrzzzvqnZw_Content;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef NF32 tyArray__9aTCwbdg1cSQimdVd0OEKVw[4];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ {
	RootObj Sup;
};
struct tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw {
	tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ Sup;
	Camera3D camera;
	Vector3 modelPosition;
	Vector3 modelScale;
	NIM_BOOL inMode3D;
	Material defaultMaterial;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ {
	NF32 x;
	NF32 y;
	NF32 z;
};
struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ position;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ up;
	NF32 fov;
	NF32 near;
	NF32 far;
};
typedef NF32 tyArray__EH3vwk2gvJbf6WGsCM9baJQ[16];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  NI len; tySequence__uFLLGQVsiasALrzzzvqnZw_Content* p;
};
struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	tySequence__uFLLGQVsiasALrzzzvqnZw indices;
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content { NI cap; NU16 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZraylibZraylib95render3d_u113)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZraylibZraylib95render3d_u135)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZraylibZraylib95render3d_u137)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3);
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZraylibZraylib95render3d_u143)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZraylibZraylib95render3d_u145)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2);
N_LIB_PRIVATE N_NIMCALL(Camera3D, toRlCamera__platformZraylibZraylib95render3d_u55)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(Vector3, toRlVec3__platformZraylibZraylib95render3d_u14)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0);
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZraylibZraylib95render3d_u168)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1);
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZraylibZraylib95render3d_u171)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg meshData_p1);
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZraylibZraylib95render3d_u200)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__KWZG8q1O7eDG79b50MsigZA_3 = { 30 | NIM_STRLIT_FLAG, "Raylib 3D renderer initialized" };
N_LIB_PRIVATE TNimTypeV2 NTIv2__mxlEqSEmWJ4ALNl1BC9aKjw_;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__KWZG8q1O7eDG79b50MsigZA_2 = {{30, (NimStrPayload*)&TM__KWZG8q1O7eDG79b50MsigZA_3}}
;
extern NIM_BOOL nimInErrorMode__system_u4234;
static NIM_CONST NU32 TM__KWZG8q1O7eDG79b50MsigZA_4[3] = {3701606400, 3864839680, 423930112};
N_LIB_PRIVATE TNimTypeV2 NTIv2__mxlEqSEmWJ4ALNl1BC9aKjw_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw), .align = (NI16) NIM_ALIGNOF(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw), .depth = 2, .display = TM__KWZG8q1O7eDG79b50MsigZA_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZraylibZraylib95render3d_u113)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	(*r_p0).defaultMaterial = LoadMaterialDefault();
	echoBinSafe(TM__KWZG8q1O7eDG79b50MsigZA_2, 1);
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZraylibZraylib95render3d_u135)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0) {
	UnloadMaterial((*r_p0).defaultMaterial);
}
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZraylibZraylib95render3d_u137)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3) {
	Color bgColor_1;
	bgColor_1.r = ((NU8) (((NF)(((NF) (clearR_p1))) * (NF)(255.0))));
	bgColor_1.g = ((NU8) (((NF)(((NF) (clearG_p2))) * (NF)(255.0))));
	bgColor_1.b = ((NU8) (((NF)(((NF) (clearB_p3))) * (NF)(255.0))));
	bgColor_1.a = ((NU8)255);
	ClearBackground(bgColor_1);
	BeginMode3D((*r_p0).camera);
	(*r_p0).inMode3D = NIM_TRUE;
}
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZraylibZraylib95render3d_u143)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0) {
	{
		if (!(*r_p0).inMode3D) goto LA3_;
		EndMode3D();
		(*r_p0).inMode3D = NIM_FALSE;
	}
LA3_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(Vector3, toRlVec3__platformZraylibZraylib95render3d_u14)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0) {
	Vector3 result;
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	colontmpD_ = v_p0.x;
	result.x = colontmpD_;
	colontmpD__2 = v_p0.y;
	result.y = colontmpD__2;
	colontmpD__3 = v_p0.z;
	result.z = colontmpD__3;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(Camera3D, toRlCamera__platformZraylibZraylib95render3d_u55)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0) {
	Camera3D result;
	Vector3 T1_;
	Vector3 T2_;
	Vector3 T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(Camera3D));
	nimZeroMem((void*)(&T1_), sizeof(Vector3));
	T1_ = toRlVec3__platformZraylibZraylib95render3d_u14((*cam_p0).position);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.position = T1_;
	nimZeroMem((void*)(&T2_), sizeof(Vector3));
	T2_ = toRlVec3__platformZraylibZraylib95render3d_u14((*cam_p0).target);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.target = T2_;
	nimZeroMem((void*)(&T3_), sizeof(Vector3));
	T3_ = toRlVec3__platformZraylibZraylib95render3d_u14((*cam_p0).up);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.up = T3_;
	result.fovy = (*cam_p0).fov;
	result.projection = ((int)0);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZraylibZraylib95render3d_u145)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2) {
	Camera3D T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(Camera3D));
	T1_ = toRlCamera__platformZraylibZraylib95render3d_u55(cam_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).camera = T1_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZraylibZraylib95render3d_u168)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1) {
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	NF32 colontmpD__4;
	NF32 colontmpD__5;
	NF32 colontmpD__6;
	Vector3 T1_;
	Vector3 T2_;
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	colontmpD__4 = (NF32)0;
	colontmpD__5 = (NF32)0;
	colontmpD__6 = (NF32)0;
	colontmpD_ = mat_p1[(((NI)12))- 0];
	T1_.x = colontmpD_;
	colontmpD__2 = mat_p1[(((NI)13))- 0];
	T1_.y = colontmpD__2;
	colontmpD__3 = mat_p1[(((NI)14))- 0];
	T1_.z = colontmpD__3;
	(*r_p0).modelPosition = T1_;
	colontmpD__4 = mat_p1[(((NI)0))- 0];
	T2_.x = colontmpD__4;
	colontmpD__5 = mat_p1[(((NI)5))- 0];
	T2_.y = colontmpD__5;
	colontmpD__6 = mat_p1[(((NI)10))- 0];
	T2_.z = colontmpD__6;
	(*r_p0).modelScale = T2_;
}
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZraylibZraylib95render3d_u171)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg meshData_p1) {
	Mesh mesh_1;
	NI T1_;
	NI T2_;
	nimZeroMem((void*)(&mesh_1), sizeof(Mesh));
	T1_ = meshData_p1.vertices.len;
	mesh_1.vertexCount = ((int) ((NI)((T1_) / (((NI)6)))));
	T2_ = meshData_p1.indices.len;
	mesh_1.triangleCount = ((int) ((NI)((T2_) / (((NI)3)))));
}
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZraylibZraylib95render3d_u200)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4) {
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZraylibZraylib95render3d_u103)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw** dest_p0, tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* src_p1) {
	tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw*, newRaylibRenderer3D__platformZraylibZraylib95render3d_u58)(void) {
	tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* result;
	tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* T1_;
	Vector3 T2_;
	Vector3 T3_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw*) nimNewObj(sizeof(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw), NIM_ALIGNOF(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw));
	(*T1_).Sup.Sup.m_type = (&NTIv2__mxlEqSEmWJ4ALNl1BC9aKjw_);
	result = T1_;
	T2_.x = 0.0f;
	T2_.y = 0.0f;
	T2_.z = 0.0f;
	(*result).modelPosition = T2_;
	T3_.x = 1.0f;
	T3_.y = 1.0f;
	T3_.z = 1.0f;
	(*result).modelScale = T3_;
	(*result).inMode3D = NIM_FALSE;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZraylibZraylib95render3d_u92)(tyObject_RaylibRenderer3DcolonObjectType___mxlEqSEmWJ4ALNl1BC9aKjw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
