/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib_full/@mplatform@sraylib@sraylib_platform.nim.c.o /workspaces/Storie/nimcache_wasm_raylib_full/@mplatform@sraylib@sraylib_platform.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "raylib.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA;
typedef struct tySequence__nvriSt31gnUeMU1UGN79aEw tySequence__nvriSt31gnUeMU1UGN79aEw;
typedef struct tySequence__nvriSt31gnUeMU1UGN79aEw_Content tySequence__nvriSt31gnUeMU1UGN79aEw_Content;
typedef struct tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg;
typedef struct tyObject_RenderBuffercolonObjectType___oV1dowsrGVOfH1l5V9cxqSA tyObject_RenderBuffercolonObjectType___oV1dowsrGVOfH1l5V9cxqSA;
typedef struct tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA;
typedef struct tySequence__IaaRlJTe4GNQBReVva7TLA tySequence__IaaRlJTe4GNQBReVva7TLA;
typedef struct tySequence__IaaRlJTe4GNQBReVva7TLA_Content tySequence__IaaRlJTe4GNQBReVva7TLA_Content;
typedef struct tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg {
	RootObj Sup;
};
struct tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q {
	tyObject_PlatformcolonObjectType___Qbb9c9cXa9bR0AiUtG9aCfp6Wg Sup;
	NIM_BOOL running;
	NI windowWidth;
	NI windowHeight;
	NF targetFps;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA {
	NI maxTextureSize;
	NIM_BOOL mouseSupport;
	NIM_BOOL resizeEvents;
	NIM_BOOL hardwareAcceleration;
};
struct tySequence__nvriSt31gnUeMU1UGN79aEw {
  NI len; tySequence__nvriSt31gnUeMU1UGN79aEw_Content* p;
};
typedef NU8 tyEnum_InputEventKind__nwQ4UyakVtkrIb9aq9bcvATw;
typedef NU8 tyEnum_InputAction__1LZ2CzsC9aLxJniP5V7Bfeg;
typedef NU8 tyEnum_MouseButton__9aXFZ7uqK3GCqAnRdMe9aGog;
struct tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg {
	tyEnum_InputEventKind__nwQ4UyakVtkrIb9aq9bcvATw kind;
union{
	struct {
	NI keyCode;
	tyEnum_InputAction__1LZ2CzsC9aLxJniP5V7Bfeg keyAction;
} _kind_1;
	struct {
	tyEnum_MouseButton__9aXFZ7uqK3GCqAnRdMe9aGog button;
	NI mouseX;
	NI mouseY;
	tyEnum_InputAction__1LZ2CzsC9aLxJniP5V7Bfeg action;
} _kind_2;
	struct {
	NI moveX;
	NI moveY;
} _kind_3;
	struct {
	NF scrollX;
	NF scrollY;
} _kind_4;
	struct {
	NI newWidth;
	NI newHeight;
} _kind_5;
};
};
struct tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA {
	NU8 r;
	NU8 g;
	NU8 b;
	NU8 a;
};
struct tySequence__IaaRlJTe4GNQBReVva7TLA {
  NI len; tySequence__IaaRlJTe4GNQBReVva7TLA_Content* p;
};
struct tyObject_RenderBuffercolonObjectType___oV1dowsrGVOfH1l5V9cxqSA {
	NI width;
	NI height;
	tySequence__IaaRlJTe4GNQBReVva7TLA commands;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA backgroundColor;
};
typedef NU8 tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg;
struct tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg {
	tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg kind;
union{
	struct {
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA clearColor;
} _kind_1;
	struct {
	NI rectX;
	NI rectY;
	NI rectW;
	NI rectH;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA rectColor;
	NI rectLineWidth;
} _kind_2;
	struct {
	NI circleX;
	NI circleY;
	NI circleRadius;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA circleColor;
	NI circleLineWidth;
} _kind_3;
	struct {
	NI lineX1;
	NI lineY1;
	NI lineX2;
	NI lineY2;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA lineColor;
	NI lineWidth;
} _kind_4;
	struct {
	NI textX;
	NI textY;
	NimStringV2 textContent;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA textColor;
	NI textSize;
} _kind_5;
	struct {
	NI pixelX;
	NI pixelY;
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA pixelColor;
} _kind_6;
};
};
struct tySequence__nvriSt31gnUeMU1UGN79aEw_Content { NI cap; tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg data[SEQ_DECL_SIZE]; };
struct tySequence__IaaRlJTe4GNQBReVva7TLA_Content { NI cap; tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init__platformZraylibZraylib95platform_u10)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NIM_BOOL enable3D_p1);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, shutdown__platformZraylibZraylib95platform_u51)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, getSize__platformZraylibZraylib95platform_u53)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA, getCapabilities__platformZraylibZraylib95platform_u58)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__nvriSt31gnUeMU1UGN79aEw, pollEvents__platformZraylibZraylib95platform_u83)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZraylibZraylib95platform_u91)(tySequence__nvriSt31gnUeMU1UGN79aEw* x_p0, tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___platformZraylibZraylib95platform_u124)(tySequence__nvriSt31gnUeMU1UGN79aEw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZraylibZraylib95platform_u127)(tySequence__nvriSt31gnUeMU1UGN79aEw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, display__platformZraylibZraylib95platform_u373)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, tyObject_RenderBuffercolonObjectType___oV1dowsrGVOfH1l5V9cxqSA* renderBuffer_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___platformZpixel95types_u108)(tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, setTargetFps__platformZraylibZraylib95platform_u427)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NF fps_p1);
N_LIB_PRIVATE N_NIMCALL(void, sleepFrame__platformZraylibZraylib95platform_u430)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NF deltaTime_p1);
N_LIB_PRIVATE N_NIMCALL(void, swapBuffers__platformZraylibZraylib95platform_u433)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0);
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__pdrL8upZZWEoiYQC9biOisw_3 = { 31 | NIM_STRLIT_FLAG, "Initializing Raylib platform..." };
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__pdrL8upZZWEoiYQC9biOisw_5 = { 30 | NIM_STRLIT_FLAG, "Failed to create raylib window" };
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__pdrL8upZZWEoiYQC9biOisw_6 = { 23 | NIM_STRLIT_FLAG, "Raylib window created: " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_7 = {23, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__pdrL8upZZWEoiYQC9biOisw_8 = { 1 | NIM_STRLIT_FLAG, "x" };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_9 = {1, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_8};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__pdrL8upZZWEoiYQC9biOisw_11 = { 32 | NIM_STRLIT_FLAG, "Shutting down Raylib platform..." };
static const struct {
  NI cap; NIM_CHAR data[74+1];
} TM__pdrL8upZZWEoiYQC9biOisw_12 = { 74 | NIM_STRLIT_FLAG, "field \'clearColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_13 = {74, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_12};
static const struct {
  NI cap; NIM_CHAR data[73+1];
} TM__pdrL8upZZWEoiYQC9biOisw_14 = { 73 | NIM_STRLIT_FLAG, "field \'rectColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_15 = {73, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_14};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_16 = { 69 | NIM_STRLIT_FLAG, "field \'rectX\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_17 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_16};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_18 = { 69 | NIM_STRLIT_FLAG, "field \'rectY\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_19 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_18};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_20 = { 69 | NIM_STRLIT_FLAG, "field \'rectW\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_21 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_20};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_22 = { 69 | NIM_STRLIT_FLAG, "field \'rectH\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_23 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_22};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_24 = {73, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_14};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_25 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_16};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_26 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_18};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_27 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_20};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_28 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_22};
static const struct {
  NI cap; NIM_CHAR data[77+1];
} TM__pdrL8upZZWEoiYQC9biOisw_29 = { 77 | NIM_STRLIT_FLAG, "field \'rectLineWidth\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_30 = {77, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_29};
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__pdrL8upZZWEoiYQC9biOisw_31 = { 75 | NIM_STRLIT_FLAG, "field \'circleColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_32 = {75, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_31};
static const struct {
  NI cap; NIM_CHAR data[71+1];
} TM__pdrL8upZZWEoiYQC9biOisw_33 = { 71 | NIM_STRLIT_FLAG, "field \'circleX\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_34 = {71, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_33};
static const struct {
  NI cap; NIM_CHAR data[71+1];
} TM__pdrL8upZZWEoiYQC9biOisw_35 = { 71 | NIM_STRLIT_FLAG, "field \'circleY\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_36 = {71, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_35};
static const struct {
  NI cap; NIM_CHAR data[76+1];
} TM__pdrL8upZZWEoiYQC9biOisw_37 = { 76 | NIM_STRLIT_FLAG, "field \'circleRadius\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_38 = {76, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_37};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_39 = {75, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_31};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_40 = {71, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_33};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_41 = {71, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_35};
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_42 = {76, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_37};
static const struct {
  NI cap; NIM_CHAR data[73+1];
} TM__pdrL8upZZWEoiYQC9biOisw_43 = { 73 | NIM_STRLIT_FLAG, "field \'lineColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_44 = {73, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_43};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_45 = { 70 | NIM_STRLIT_FLAG, "field \'lineX1\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_46 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_45};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_47 = { 70 | NIM_STRLIT_FLAG, "field \'lineY1\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_48 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_47};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_49 = { 70 | NIM_STRLIT_FLAG, "field \'lineX2\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_50 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_49};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_51 = { 70 | NIM_STRLIT_FLAG, "field \'lineY2\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_52 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_51};
static const struct {
  NI cap; NIM_CHAR data[73+1];
} TM__pdrL8upZZWEoiYQC9biOisw_53 = { 73 | NIM_STRLIT_FLAG, "field \'lineWidth\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_54 = {73, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_53};
static const struct {
  NI cap; NIM_CHAR data[73+1];
} TM__pdrL8upZZWEoiYQC9biOisw_55 = { 73 | NIM_STRLIT_FLAG, "field \'textColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_56 = {73, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_55};
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__pdrL8upZZWEoiYQC9biOisw_57 = { 75 | NIM_STRLIT_FLAG, "field \'textContent\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_58 = {75, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_57};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_59 = { 69 | NIM_STRLIT_FLAG, "field \'textX\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_60 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_59};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__pdrL8upZZWEoiYQC9biOisw_61 = { 69 | NIM_STRLIT_FLAG, "field \'textY\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_62 = {69, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_61};
static const struct {
  NI cap; NIM_CHAR data[72+1];
} TM__pdrL8upZZWEoiYQC9biOisw_63 = { 72 | NIM_STRLIT_FLAG, "field \'textSize\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_64 = {72, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_63};
static const struct {
  NI cap; NIM_CHAR data[74+1];
} TM__pdrL8upZZWEoiYQC9biOisw_65 = { 74 | NIM_STRLIT_FLAG, "field \'pixelColor\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_66 = {74, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_65};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_67 = { 70 | NIM_STRLIT_FLAG, "field \'pixelX\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_68 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_67};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__pdrL8upZZWEoiYQC9biOisw_69 = { 70 | NIM_STRLIT_FLAG, "field \'pixelY\' is not accessible for type \'DrawCommand\' using \'kind = " };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_70 = {70, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_69};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__pdrL8upZZWEoiYQC9biOisw_71 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__pdrL8upZZWEoiYQC9biOisw_72 = {90, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_71};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Oxv9aIjFb48SxLCAeWPp43Q_;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__pdrL8upZZWEoiYQC9biOisw_2 = {{31, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__pdrL8upZZWEoiYQC9biOisw_4 = {{30, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_5}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__pdrL8upZZWEoiYQC9biOisw_10 = {{32, (NimStrPayload*)&TM__pdrL8upZZWEoiYQC9biOisw_11}}
;
extern NIM_BOOL nimInErrorMode__system_u4234;
static NIM_CONST NU32 TM__pdrL8upZZWEoiYQC9biOisw_73[3] = {3701606400, 3070229760, 469574144};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Oxv9aIjFb48SxLCAeWPp43Q_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q), .align = (NI16) NIM_ALIGNOF(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q), .depth = 2, .display = TM__pdrL8upZZWEoiYQC9biOisw_73, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init__platformZraylibZraylib95platform_u10)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NIM_BOOL enable3D_p1) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	int T7_;
	int T8_;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	echoBinSafe(TM__pdrL8upZZWEoiYQC9biOisw_2, 1);
	InitWindow(((int)1024), ((int)768), "Storie Raylib");
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = IsWindowReady();
		if (!!(T4_)) goto LA5_;
		echoBinSafe(TM__pdrL8upZZWEoiYQC9biOisw_4, 1);
		result = NIM_FALSE;
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = (int)0;
	T7_ = GetScreenWidth();
	(*p_p0).windowWidth = ((NI) (T7_));
	T8_ = (int)0;
	T8_ = GetScreenHeight();
	(*p_p0).windowHeight = ((NI) (T8_));
	(*p_p0).running = NIM_TRUE;
	T9_[0] = TM__pdrL8upZZWEoiYQC9biOisw_7;
	colontmpD_ = dollar___systemZdollars_u14((*p_p0).windowWidth);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[1] = colontmpD_;
	T9_[2] = TM__pdrL8upZZWEoiYQC9biOisw_9;
	colontmpD__2 = dollar___systemZdollars_u14((*p_p0).windowHeight);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[3] = colontmpD__2;
	echoBinSafe(T9_, 4);
	result = NIM_TRUE;
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown__platformZraylibZraylib95platform_u51)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0) {
	echoBinSafe(TM__pdrL8upZZWEoiYQC9biOisw_10, 1);
	CloseWindow();
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, getSize__platformZraylibZraylib95platform_u53)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	int T1_;
	int T2_;
	NI colontmp_;
	NI colontmp__2;
{	T1_ = (int)0;
	T1_ = GetScreenWidth();
	(*p_p0).windowWidth = ((NI) (T1_));
	T2_ = (int)0;
	T2_ = GetScreenHeight();
	(*p_p0).windowHeight = ((NI) (T2_));
	colontmp_ = (*p_p0).windowWidth;
	colontmp__2 = (*p_p0).windowHeight;
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA, getCapabilities__platformZraylibZraylib95platform_u58)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0) {
	tyObject_PlatformCapabilities__8l9chQVd6Fw1Ct0qlLreU9bA result;
{	result.maxTextureSize = ((NI)4096);
	result.mouseSupport = NIM_TRUE;
	result.resizeEvents = NIM_TRUE;
	result.hardwareAcceleration = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__nvriSt31gnUeMU1UGN79aEw, pollEvents__platformZraylibZraylib95platform_u83)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0) {
	tySequence__nvriSt31gnUeMU1UGN79aEw result;
	tySequence__nvriSt31gnUeMU1UGN79aEw events_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	events_1.len = 0; events_1.p = NIM_NIL;
	events_1.len = 0; events_1.p = (tySequence__nvriSt31gnUeMU1UGN79aEw_Content*) newSeqPayload(0, sizeof(tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg), NIM_ALIGNOF(tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg));
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = WindowShouldClose();
		if (!T4_) goto LA5_;
		(*p_p0).running = NIM_FALSE;
	}
LA5_: ;
	{
		NIM_BOOL T9_;
		NI colontmpD_;
		NI colontmpD__2;
		int T12_;
		int T13_;
		tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg T14_;
		T9_ = (NIM_BOOL)0;
		T9_ = IsWindowResized();
		if (!T9_) goto LA10_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		T12_ = (int)0;
		T12_ = GetScreenWidth();
		(*p_p0).windowWidth = ((NI) (T12_));
		T13_ = (int)0;
		T13_ = GetScreenHeight();
		(*p_p0).windowHeight = ((NI) (T13_));
		T14_.kind = ((tyEnum_InputEventKind__nwQ4UyakVtkrIb9aq9bcvATw)4);
		colontmpD_ = (*p_p0).windowWidth;
		T14_._kind_5.newWidth = colontmpD_;
		colontmpD__2 = (*p_p0).windowHeight;
		T14_._kind_5.newHeight = colontmpD__2;
		add__platformZraylibZraylib95platform_u91((&events_1), T14_);
	}
LA10_: ;
	{
		NIM_BOOL T17_;
		tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg T20_;
		T17_ = (NIM_BOOL)0;
		T17_ = IsKeyPressed(((int)256));
		if (!T17_) goto LA18_;
		T20_.kind = ((tyEnum_InputEventKind__nwQ4UyakVtkrIb9aq9bcvATw)0);
		T20_._kind_1.keyCode = ((NI)256);
		T20_._kind_1.keyAction = ((tyEnum_InputAction__1LZ2CzsC9aLxJniP5V7Bfeg)0);
		add__platformZraylibZraylib95platform_u91((&events_1), T20_);
	}
LA18_: ;
	{
		NIM_BOOL T23_;
		tyObject_InputEvent__tsZWrgL3X4S3Gz9br6y7dVg T26_;
		int T27_;
		int T28_;
		T23_ = (NIM_BOOL)0;
		T23_ = IsMouseButtonPressed(((int)0));
		if (!T23_) goto LA24_;
		T26_.kind = ((tyEnum_InputEventKind__nwQ4UyakVtkrIb9aq9bcvATw)1);
		T26_._kind_2.button = ((tyEnum_MouseButton__9aXFZ7uqK3GCqAnRdMe9aGog)0);
		T27_ = (int)0;
		T27_ = GetMouseX();
		T26_._kind_2.mouseX = ((NI) (T27_));
		T28_ = (int)0;
		T28_ = GetMouseY();
		T26_._kind_2.mouseY = ((NI) (T28_));
		T26_._kind_2.action = ((tyEnum_InputAction__1LZ2CzsC9aLxJniP5V7Bfeg)0);
		add__platformZraylibZraylib95platform_u91((&events_1), T26_);
	}
LA24_: ;
	result = events_1;
	eqwasMoved___platformZraylibZraylib95platform_u124((&events_1));
	eqdestroy___platformZraylibZraylib95platform_u127(events_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___platformZraylibZraylib95platform_u127(events_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, display__platformZraylibZraylib95platform_u373)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, tyObject_RenderBuffercolonObjectType___oV1dowsrGVOfH1l5V9cxqSA* renderBuffer_p1) {
	tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA bg_1;
	Color T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	BeginDrawing();
	bg_1 = (*renderBuffer_p1).backgroundColor;
	T1_.r = bg_1.r;
	T1_.g = bg_1.g;
	T1_.b = bg_1.b;
	T1_.a = bg_1.a;
	ClearBackground(T1_);
	{
		tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg* cmd_1;
		NI i_1;
		NI L_1;
		NI T3_;
		cmd_1 = (tyObject_DrawCommand__fRpQG9cPSJx4petSc4JZ3Hg*)0;
		i_1 = ((NI)0);
		T3_ = (*renderBuffer_p1).commands.len;
		L_1 = T3_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= (*renderBuffer_p1).commands.len){ raiseIndexError2(i_1,(*renderBuffer_p1).commands.len-1); goto BeforeRet_;
				}
				cmd_1 = (&(*renderBuffer_p1).commands.p->data[i_1]);
				switch ((*cmd_1).kind) {
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)0):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_1;
					Color T7_;
					if (!(((1 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_13, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_1 = (*cmd_1)._kind_1.clearColor;
					T7_.r = c_1.r;
					T7_.g = c_1.g;
					T7_.b = c_1.b;
					T7_.a = c_1.a;
					ClearBackground(T7_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)2):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_2;
					Color T9_;
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_15, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_2 = (*cmd_1)._kind_2.rectColor;
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_17, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_19, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_21, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_23, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T9_.r = c_2.r;
					T9_.g = c_2.g;
					T9_.b = c_2.b;
					T9_.a = c_2.a;
					DrawRectangle(((int) ((*cmd_1)._kind_2.rectX)), ((int) ((*cmd_1)._kind_2.rectY)), ((int) ((*cmd_1)._kind_2.rectW)), ((int) ((*cmd_1)._kind_2.rectH)), T9_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)1):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_3;
					Rectangle T11_;
					Color T12_;
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_24, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_3 = (*cmd_1)._kind_2.rectColor;
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_25, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T11_.x = ((NF32) ((*cmd_1)._kind_2.rectX));
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_26, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T11_.y = ((NF32) ((*cmd_1)._kind_2.rectY));
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_27, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T11_.width = ((NF32) ((*cmd_1)._kind_2.rectW));
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_28, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T11_.height = ((NF32) ((*cmd_1)._kind_2.rectH));
					if (!(((6 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_30, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T12_.r = c_3.r;
					T12_.g = c_3.g;
					T12_.b = c_3.b;
					T12_.a = c_3.a;
					DrawRectangleLinesEx(T11_, ((NF32) ((*cmd_1)._kind_2.rectLineWidth)), T12_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)4):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_4;
					Color T14_;
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_32, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_4 = (*cmd_1)._kind_3.circleColor;
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_34, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_36, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_38, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T14_.r = c_4.r;
					T14_.g = c_4.g;
					T14_.b = c_4.b;
					T14_.a = c_4.a;
					DrawCircle(((int) ((*cmd_1)._kind_3.circleX)), ((int) ((*cmd_1)._kind_3.circleY)), ((NF32) ((*cmd_1)._kind_3.circleRadius)), T14_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)3):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_5;
					Color T16_;
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_39, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_5 = (*cmd_1)._kind_3.circleColor;
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_40, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_41, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((24 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_42, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T16_.r = c_5.r;
					T16_.g = c_5.g;
					T16_.b = c_5.b;
					T16_.a = c_5.a;
					DrawCircleLines(((int) ((*cmd_1)._kind_3.circleX)), ((int) ((*cmd_1)._kind_3.circleY)), ((NF32) ((*cmd_1)._kind_3.circleRadius)), T16_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)5):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_6;
					Vector2 T18_;
					Vector2 T19_;
					Color T20_;
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_44, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_6 = (*cmd_1)._kind_4.lineColor;
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_46, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T18_.x = ((NF32) ((*cmd_1)._kind_4.lineX1));
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_48, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T18_.y = ((NF32) ((*cmd_1)._kind_4.lineY1));
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_50, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T19_.x = ((NF32) ((*cmd_1)._kind_4.lineX2));
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_52, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T19_.y = ((NF32) ((*cmd_1)._kind_4.lineY2));
					if (!(((32 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_54, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T20_.r = c_6.r;
					T20_.g = c_6.g;
					T20_.b = c_6.b;
					T20_.a = c_6.a;
					DrawLineEx(T18_, T19_, ((NF32) ((*cmd_1)._kind_4.lineWidth)), T20_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)6):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_7;
					Color T22_;
					if (!(((64 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_56, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_7 = (*cmd_1)._kind_5.textColor;
					if (!(((64 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_58, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((64 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_60, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((64 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_62, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((64 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_64, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T22_.r = c_7.r;
					T22_.g = c_7.g;
					T22_.b = c_7.b;
					T22_.a = c_7.a;
					DrawText(nimToCStringConv((*cmd_1)._kind_5.textContent), ((int) ((*cmd_1)._kind_5.textX)), ((int) ((*cmd_1)._kind_5.textY)), ((int) ((*cmd_1)._kind_5.textSize)), T22_);
				}
				break;
				case ((tyEnum_DrawCommandKind__b9amtDSrKgoNNOhix3Ke9cPg)7):
				{
					tyObject_Color__kbuhB03DEkd9aC7M2BTgZhA c_8;
					Color T24_;
					if (!(((128 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_66, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					c_8 = (*cmd_1)._kind_6.pixelColor;
					if (!(((128 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_68, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					if (!(((128 &((NU8)1<<((NU)(((*cmd_1).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__pdrL8upZZWEoiYQC9biOisw_70, dollar___platformZpixel95types_u108((*cmd_1).kind)); goto BeforeRet_;
					}
					T24_.r = c_8.r;
					T24_.g = c_8.g;
					T24_.b = c_8.b;
					T24_.a = c_8.a;
					DrawPixel(((int) ((*cmd_1)._kind_6.pixelX)), ((int) ((*cmd_1)._kind_6.pixelY)), T24_);
				}
				break;
				default: __builtin_unreachable();
				}
				i_1 += ((NI)1);
				{
					NI T27_;
					T27_ = (*renderBuffer_p1).commands.len;
					if (!!((T27_ == L_1))) goto LA28_;
					failedAssertImpl__stdZassertions_u234(TM__pdrL8upZZWEoiYQC9biOisw_72);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA28_: ;
			} LA5: ;
		}
	}
	EndDrawing();
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setTargetFps__platformZraylibZraylib95platform_u427)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NF fps_p1) {
	(*p_p0).targetFps = fps_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, sleepFrame__platformZraylibZraylib95platform_u430)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0, NF deltaTime_p1) {
}
N_LIB_PRIVATE N_NIMCALL(void, swapBuffers__platformZraylibZraylib95platform_u433)(tyObject_RaylibPlatformcolonObjectType___Oxv9aIjFb48SxLCAeWPp43Q* p_p0) {
}
