/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib_full/@msrc@snimini@sfrontend.nim.c.o /workspaces/Storie/nimcache_wasm_raylib_full/@msrc@snimini@sfrontend.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__X64B7Q9ceiuE7g3XUrk07mQ tySequence__X64B7Q9ceiuE7g3XUrk07mQ;
typedef struct tySequence__X64B7Q9ceiuE7g3XUrk07mQ_Content tySequence__X64B7Q9ceiuE7g3XUrk07mQ_Content;
typedef struct tySequence__BdfKvzphw6Ov4Sxv8IGz2g tySequence__BdfKvzphw6Ov4Sxv8IGz2g;
typedef struct tySequence__BdfKvzphw6Ov4Sxv8IGz2g_Content tySequence__BdfKvzphw6Ov4Sxv8IGz2g_Content;
typedef struct tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ;
typedef struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw tySequence__z9cyhh9cmbMWU4a3QzH1fgyw;
typedef struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyObject_Token__H73wtlSU6RLHrlwmkx6tHQ tyObject_Token__H73wtlSU6RLHrlwmkx6tHQ;
typedef struct tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ;
struct tySequence__X64B7Q9ceiuE7g3XUrk07mQ {
  NI len; tySequence__X64B7Q9ceiuE7g3XUrk07mQ_Content* p;
};
struct tySequence__BdfKvzphw6Ov4Sxv8IGz2g {
  NI len; tySequence__BdfKvzphw6Ov4Sxv8IGz2g_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ {
	RootObj Sup;
	NimStringV2 name;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ fileExtensions;
	NIM_BOOL supportsTypeAnnotations;
};
struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw {
  NI len; tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content* p;
};
struct tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ {
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw stmts;
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tySequence__X64B7Q9ceiuE7g3XUrk07mQ_Content { NI cap; tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_TokenKind__aI8M59c62F69cT6myDRhab8g;
struct tyObject_Token__H73wtlSU6RLHrlwmkx6tHQ {
	tyEnum_TokenKind__aI8M59c62F69cT6myDRhab8g kind;
	NimStringV2 lexeme;
	NI line;
	NI col;
};
struct tySequence__BdfKvzphw6Ov4Sxv8IGz2g_Content { NI cap; tyObject_Token__H73wtlSU6RLHrlwmkx6tHQ data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content { NI cap; tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tySequence__BdfKvzphw6Ov4Sxv8IGz2g, tokenize__srcZniminiZfrontend_u9)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* frontend_p0, NimStringV2 source_p1);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u7668)(NimStringV2 errormsg_p0, NI errorcode_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ, parse__srcZniminiZfrontend_u15)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* frontend_p0, tySequence__BdfKvzphw6Ov4Sxv8IGz2g tokens_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__srcZniminiZfrontend_u48)(tySequence__X64B7Q9ceiuE7g3XUrk07mQ* x_p0, tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ*, eqdup___srcZniminiZfrontend_u83)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* src_p0, NIM_BOOL cyclic_p1);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__m8zVzkEnJ0RKZ9cekHzwdQQ_2 = { 39 | NIM_STRLIT_FLAG, "tokenize not implemented for frontend: " };
static const NimStringV2 TM__m8zVzkEnJ0RKZ9cekHzwdQQ_3 = {39, (NimStrPayload*)&TM__m8zVzkEnJ0RKZ9cekHzwdQQ_2};
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__m8zVzkEnJ0RKZ9cekHzwdQQ_5 = { 36 | NIM_STRLIT_FLAG, "parse not implemented for frontend: " };
static const NimStringV2 TM__m8zVzkEnJ0RKZ9cekHzwdQQ_6 = {36, (NimStrPayload*)&TM__m8zVzkEnJ0RKZ9cekHzwdQQ_5};
N_LIB_PRIVATE tySequence__X64B7Q9ceiuE7g3XUrk07mQ registeredFrontends__srcZniminiZfrontend_u45;
extern NIM_BOOL nimInErrorMode__system_u4234;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__m8zVzkEnJ0RKZ9cekHzwdQQ_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)2147483647)){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__m8zVzkEnJ0RKZ9cekHzwdQQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__m8zVzkEnJ0RKZ9cekHzwdQQ_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__BdfKvzphw6Ov4Sxv8IGz2g, tokenize__srcZniminiZfrontend_u9)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* frontend_p0, NimStringV2 source_p1) {
	tySequence__BdfKvzphw6Ov4Sxv8IGz2g result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString((*frontend_p0).name.len + 39);
appendString((&T1_), TM__m8zVzkEnJ0RKZ9cekHzwdQQ_3);
appendString((&T1_), (*frontend_p0).name);
	colontmpD_ = T1_;
	quit__system_u7668(colontmpD_, ((NI)1));
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ, parse__srcZniminiZfrontend_u15)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* frontend_p0, tySequence__BdfKvzphw6Ov4Sxv8IGz2g tokens_p1) {
	tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
	nimZeroMem((void*)(&result), sizeof(tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString((*frontend_p0).name.len + 36);
appendString((&T1_), TM__m8zVzkEnJ0RKZ9cekHzwdQQ_6);
appendString((&T1_), (*frontend_p0).name);
	colontmpD_ = T1_;
	quit__system_u7668(colontmpD_, ((NI)1));
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) + (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* h_1;
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	h_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T1_));
	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ*, eqdup___srcZniminiZfrontend_u83)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* src_p0, NIM_BOOL cyclic_p1) {
	tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* result;
	tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* colontmp_;
	result = NIM_NIL;
	colontmp_ = result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRefCyclic(src_p0, cyclic_p1);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, registerFrontend__srcZniminiZfrontend_u46)(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* frontend_p0) {
	tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ* colontmpD_;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___srcZniminiZfrontend_u83(frontend_p0, NIM_TRUE);
	add__srcZniminiZfrontend_u48((&registeredFrontends__srcZniminiZfrontend_u45), colontmpD_);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZfrontend_u177)(tySequence__X64B7Q9ceiuE7g3XUrk07mQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicDyn(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				nimDestroyAndDispose(dest_p0.p->data[colontmp_]);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, atmsrcatsniminiatsfrontenddotnim_Init000)(void) {
{
	registeredFrontends__srcZniminiZfrontend_u45.len = 0; registeredFrontends__srcZniminiZfrontend_u45.p = (tySequence__X64B7Q9ceiuE7g3XUrk07mQ_Content*) newSeqPayload(0, sizeof(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ*), NIM_ALIGNOF(tyObject_FrontendcolonObjectType___DBjpJAIuE2tAxUcTj0CQpQ*));
	nimTestErrorFlag();
}
}

