/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib_full/@msrc@snimini@splugin.nim.c.o /workspaces/Storie/nimcache_wasm_raylib_full/@msrc@snimini@splugin.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_Table__xnMONimItci4XsmvXfgojg tyObject_Table__xnMONimItci4XsmvXfgojg;
typedef struct tySequence__JGD4gfgTFBL3IKPT9bGZKcA tySequence__JGD4gfgTFBL3IKPT9bGZKcA;
typedef struct tySequence__JGD4gfgTFBL3IKPT9bGZKcA_Content tySequence__JGD4gfgTFBL3IKPT9bGZKcA_Content;
typedef struct tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w;
typedef struct tySequence__WHiKSM9boMj9ccmTT9agvdFUA tySequence__WHiKSM9boMj9ccmTT9agvdFUA;
typedef struct tySequence__WHiKSM9boMj9ccmTT9agvdFUA_Content tySequence__WHiKSM9boMj9ccmTT9agvdFUA_Content;
typedef struct tyObject_PluginInfo__TSVPg56xkAjUehyuY3w2Dg tyObject_PluginInfo__TSVPg56xkAjUehyuY3w2Dg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Table__xR9cTEedWKn2F9bIo07HpGiA tyObject_Table__xR9cTEedWKn2F9bIo07HpGiA;
typedef struct tySequence__tjKRaXJnNPS7F15ps4XqNA tySequence__tjKRaXJnNPS7F15ps4XqNA;
typedef struct tySequence__tjKRaXJnNPS7F15ps4XqNA_Content tySequence__tjKRaXJnNPS7F15ps4XqNA_Content;
typedef struct tyObject_Table__6paSxwYje8mPhxlM9atNHig tyObject_Table__6paSxwYje8mPhxlM9atNHig;
typedef struct tySequence__3z1571A2UZB0YD9c5AVJQig tySequence__3z1571A2UZB0YD9c5AVJQig;
typedef struct tySequence__3z1571A2UZB0YD9c5AVJQig_Content tySequence__3z1571A2UZB0YD9c5AVJQig_Content;
typedef struct tySequence__beXu4r3nkvKFHAEGgdqLRg tySequence__beXu4r3nkvKFHAEGgdqLRg;
typedef struct tySequence__beXu4r3nkvKFHAEGgdqLRg_Content tySequence__beXu4r3nkvKFHAEGgdqLRg_Content;
typedef struct tyObject_PluginHooks__uXjpZ2Kot66KnQFTJVjlXQ tyObject_PluginHooks__uXjpZ2Kot66KnQFTJVjlXQ;
typedef struct tyObject_PluginContextcolonObjectType___LkHBs8w85WLpilelyWV6DA tyObject_PluginContextcolonObjectType___LkHBs8w85WLpilelyWV6DA;
typedef struct tyObject_CodegenMapping__xKklsuryM0wSKrSEYdLpHw tyObject_CodegenMapping__xKklsuryM0wSKrSEYdLpHw;
typedef struct tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content;
typedef struct tyObject_Table__2B4I3z2MUyKxS7DqyRm3OQ tyObject_Table__2B4I3z2MUyKxS7DqyRm3OQ;
typedef struct tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg;
typedef struct tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ;
typedef struct tyTuple__lBireGel9cGbbGOTpgwUdwQ tyTuple__lBireGel9cGbbGOTpgwUdwQ;
typedef struct tyTuple__s3yqhR41JR29axxucYXVy2w tyTuple__s3yqhR41JR29axxucYXVy2w;
typedef struct tyTuple__OMA9b9aREWmi9cW339cOxuOUoQ tyTuple__OMA9b9aREWmi9cW339cOxuOUoQ;
typedef struct tyObject_BackendMapping__9b3mSLoC7EsT9aMyU9a7lxrww tyObject_BackendMapping__9b3mSLoC7EsT9aMyU9a7lxrww;
typedef struct tyTuple__vl6DL4Sojto058PRFb5DFg tyTuple__vl6DL4Sojto058PRFb5DFg;
typedef struct tyObject_ValuecolonObjectType___RcYJRyWduJExIF9chvHZw9aA tyObject_ValuecolonObjectType___RcYJRyWduJExIF9chvHZw9aA;
typedef struct tyObject_Env__3CHZHNtlgDxtzX7rKE9comA tyObject_Env__3CHZHNtlgDxtzX7rKE9comA;
typedef struct tySequence__LLwX9afy1LBS5QLt4UaGSUA tySequence__LLwX9afy1LBS5QLt4UaGSUA;
typedef struct tySequence__LLwX9afy1LBS5QLt4UaGSUA_Content tySequence__LLwX9afy1LBS5QLt4UaGSUA_Content;
typedef struct tyTuple__IZBhtVqX6gsw70GUGulUuA tyTuple__IZBhtVqX6gsw70GUGulUuA;
typedef struct tyObject_NodeDef__gn3Y9cbm8WksuXk7psAcnVQ tyObject_NodeDef__gn3Y9cbm8WksuXk7psAcnVQ;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__JGD4gfgTFBL3IKPT9bGZKcA {
  NI len; tySequence__JGD4gfgTFBL3IKPT9bGZKcA_Content* p;
};
struct tyObject_Table__xnMONimItci4XsmvXfgojg {
	tySequence__JGD4gfgTFBL3IKPT9bGZKcA data;
	NI counter;
};
struct tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg {
	tyObject_Table__xnMONimItci4XsmvXfgojg plugins;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ loadOrder;
};
struct tySequence__WHiKSM9boMj9ccmTT9agvdFUA {
  NI len; tySequence__WHiKSM9boMj9ccmTT9agvdFUA_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_PluginInfo__TSVPg56xkAjUehyuY3w2Dg {
	NimStringV2 name;
	NimStringV2 author;
	NimStringV2 version;
	NimStringV2 description;
};
struct tySequence__tjKRaXJnNPS7F15ps4XqNA {
  NI len; tySequence__tjKRaXJnNPS7F15ps4XqNA_Content* p;
};
struct tyObject_Table__xR9cTEedWKn2F9bIo07HpGiA {
	tySequence__tjKRaXJnNPS7F15ps4XqNA data;
	NI counter;
};
struct tySequence__3z1571A2UZB0YD9c5AVJQig {
  NI len; tySequence__3z1571A2UZB0YD9c5AVJQig_Content* p;
};
struct tyObject_Table__6paSxwYje8mPhxlM9atNHig {
	tySequence__3z1571A2UZB0YD9c5AVJQig data;
	NI counter;
};
struct tySequence__beXu4r3nkvKFHAEGgdqLRg {
  NI len; tySequence__beXu4r3nkvKFHAEGgdqLRg_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_PluginContextcolonObjectType___LkHBs8w85WLpilelyWV6DA* ctx_p0, void* ClE_0);
void* ClE_0;
} tyProc__JXtLU9bKVDxe2lJ518Fv2sw;
struct tyObject_PluginHooks__uXjpZ2Kot66KnQFTJVjlXQ {
	tyProc__JXtLU9bKVDxe2lJ518Fv2sw onLoad;
	tyProc__JXtLU9bKVDxe2lJ518Fv2sw onUnload;
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  NI len; tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content* p;
};
struct tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ {
	tySequence__SFipDZIkFtPcrLs0AGBBjQ data;
	NI counter;
};
struct tyObject_Table__2B4I3z2MUyKxS7DqyRm3OQ {
	tySequence__WHiKSM9boMj9ccmTT9agvdFUA data;
	NI counter;
};
struct tyObject_CodegenMapping__xKklsuryM0wSKrSEYdLpHw {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimImports;
	tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ functionMappings;
	tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ constantMappings;
	tyObject_Table__2B4I3z2MUyKxS7DqyRm3OQ backends;
};
struct tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w {
	tyObject_PluginInfo__TSVPg56xkAjUehyuY3w2Dg info;
	tyObject_Table__xR9cTEedWKn2F9bIo07HpGiA functions;
	tyObject_Table__6paSxwYje8mPhxlM9atNHig constants;
	tySequence__beXu4r3nkvKFHAEGgdqLRg nodes;
	tyObject_PluginHooks__uXjpZ2Kot66KnQFTJVjlXQ hooks;
	NIM_BOOL enabled;
	tyObject_CodegenMapping__xKklsuryM0wSKrSEYdLpHw codegen;
};
struct tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ {
	NI len;
	NI cap;
	tyTuple__lBireGel9cGbbGOTpgwUdwQ* d;
};
struct tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg {
	tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA traceStack;
	tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyTuple__s3yqhR41JR29axxucYXVy2w {
	NI Field0;
	NimStringV2 Field1;
	tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w* Field2;
};
struct tySequence__JGD4gfgTFBL3IKPT9bGZKcA_Content { NI cap; tyTuple__s3yqhR41JR29axxucYXVy2w data[SEQ_DECL_SIZE]; };
struct tyObject_BackendMapping__9b3mSLoC7EsT9aMyU9a7lxrww {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ imports;
	tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ functionMappings;
	tyObject_Table__tTankCrtBQsxM32qYJ9aPPQ constantMappings;
};
struct tyTuple__OMA9b9aREWmi9cW339cOxuOUoQ {
	NI Field0;
	NimStringV2 Field1;
	tyObject_BackendMapping__9b3mSLoC7EsT9aMyU9a7lxrww Field2;
};
struct tySequence__WHiKSM9boMj9ccmTT9agvdFUA_Content { NI cap; tyTuple__OMA9b9aREWmi9cW339cOxuOUoQ data[SEQ_DECL_SIZE]; };
struct tySequence__LLwX9afy1LBS5QLt4UaGSUA {
  NI len; tySequence__LLwX9afy1LBS5QLt4UaGSUA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ValuecolonObjectType___RcYJRyWduJExIF9chvHZw9aA*, ClP_0) (tyObject_Env__3CHZHNtlgDxtzX7rKE9comA* env_p0, tySequence__LLwX9afy1LBS5QLt4UaGSUA args_p1, void* ClE_0);
void* ClE_0;
} tyProc__dRdtWW5bVZ0MoKBmIRx3MQ;
struct tyTuple__vl6DL4Sojto058PRFb5DFg {
	NI Field0;
	NimStringV2 Field1;
	tyProc__dRdtWW5bVZ0MoKBmIRx3MQ Field2;
};
struct tySequence__tjKRaXJnNPS7F15ps4XqNA_Content { NI cap; tyTuple__vl6DL4Sojto058PRFb5DFg data[SEQ_DECL_SIZE]; };
struct tyTuple__IZBhtVqX6gsw70GUGulUuA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_ValuecolonObjectType___RcYJRyWduJExIF9chvHZw9aA* Field2;
};
struct tySequence__3z1571A2UZB0YD9c5AVJQig_Content { NI cap; tyTuple__IZBhtVqX6gsw70GUGulUuA data[SEQ_DECL_SIZE]; };
struct tyObject_NodeDef__gn3Y9cbm8WksuXk7psAcnVQ {
	NimStringV2 name;
	NimStringV2 description;
};
struct tySequence__beXu4r3nkvKFHAEGgdqLRg_Content { NI cap; tyObject_NodeDef__gn3Y9cbm8WksuXk7psAcnVQ data[SEQ_DECL_SIZE]; };
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
	NI Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content { NI cap; tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE]; };
struct tySequence__LLwX9afy1LBS5QLt4UaGSUA_Content { NI cap; tyObject_ValuecolonObjectType___RcYJRyWduJExIF9chvHZw9aA* data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZplugin_u8764)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u6722)(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3717)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u6661)(tySequence__JGD4gfgTFBL3IKPT9bGZKcA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZplugin_u8766)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u1091)(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u731)(tySequence__WHiKSM9boMj9ccmTT9agvdFUA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u500)(tySequence__SFipDZIkFtPcrLs0AGBBjQ dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u800)(tySequence__beXu4r3nkvKFHAEGgdqLRg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZruntime_u164)(tySequence__3z1571A2UZB0YD9c5AVJQig dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u256)(tySequence__tjKRaXJnNPS7F15ps4XqNA dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u1103)(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u268)(tySequence__tjKRaXJnNPS7F15ps4XqNA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZruntime_u176)(tySequence__3z1571A2UZB0YD9c5AVJQig* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u2954)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2962)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u6734)(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u6673)(tySequence__JGD4gfgTFBL3IKPT9bGZKcA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__V39cfh9chfy20I8fZ8bR0gBg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__LSMDwJThUH7Uh8pEgskj0w_;
N_LIB_PRIVATE tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* globalRegistry__srcZniminiZplugin_u6474;
extern NIM_BOOL nimInErrorMode__system_u4234;
static NIM_CONST NU32 TM__nbuZgAxXybed0yk9as03XsA_2[1] = {587448320};
N_LIB_PRIVATE TNimTypeV2 NTIv2__LSMDwJThUH7Uh8pEgskj0w_ = {.destructor = (void*)rttiDestroy__srcZniminiZplugin_u8766, .size = sizeof(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w), .align = (NI16) NIM_ALIGNOF(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w), .depth = 0, .display = TM__nbuZgAxXybed0yk9as03XsA_2, .traceImpl = (void*)eqtrace___srcZniminiZplugin_u1103, .flags = 0};
static NIM_CONST NU32 TM__nbuZgAxXybed0yk9as03XsA_3[1] = {2145355520};
N_LIB_PRIVATE TNimTypeV2 NTIv2__V39cfh9chfy20I8fZ8bR0gBg_ = {.destructor = (void*)rttiDestroy__srcZniminiZplugin_u8764, .size = sizeof(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg), .align = (NI16) NIM_ALIGNOF(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg), .depth = 0, .display = TM__nbuZgAxXybed0yk9as03XsA_3, .traceImpl = (void*)eqtrace___srcZniminiZplugin_u6734, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, desc_p1);
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u1091)(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w* dest_p0) {
	eqdestroy___srcZniminiZplugin_u731((*dest_p0).codegen.backends.data);
	eqdestroy___srcZniminiZplugin_u500((*dest_p0).codegen.constantMappings.data);
	eqdestroy___srcZniminiZplugin_u500((*dest_p0).codegen.functionMappings.data);
	eqdestroy___system_u3717((*dest_p0).codegen.nimImports);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).hooks.onUnload.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).hooks.onUnload.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).hooks.onLoad.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).hooks.onLoad.ClE_0);
	}
LA9_: ;
	eqdestroy___srcZniminiZplugin_u800((*dest_p0).nodes);
	eqdestroy___srcZniminiZruntime_u164((*dest_p0).constants.data);
	eqdestroy___srcZniminiZplugin_u256((*dest_p0).functions.data);
	if ((*dest_p0).info.description.p && !((*dest_p0).info.description.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).info.description.p);
}
	if ((*dest_p0).info.version.p && !((*dest_p0).info.version.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).info.version.p);
}
	if ((*dest_p0).info.author.p && !((*dest_p0).info.author.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).info.author.p);
}
	if ((*dest_p0).info.name.p && !((*dest_p0).info.name.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).info.name.p);
}
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZplugin_u8766)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___srcZniminiZplugin_u1091(((tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) + (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, add__system_u2954)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u2962(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg*) (env_p1));
		add__system_u2954((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u1103)(tyObject_PlugincolonObjectType___LSMDwJThUH7Uh8pEgskj0w* dest_p0, void* env_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqtrace___srcZniminiZplugin_u268((&(*dest_p0).functions.data), env_p1);
	eqtrace___srcZniminiZruntime_u176((&(*dest_p0).constants.data), env_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimTraceRefDyn((&(*dest_p0).hooks.onLoad.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).hooks.onUnload.ClE_0), env_p1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u6722)(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* dest_p0) {
	eqdestroy___system_u3717((*dest_p0).loadOrder);
	eqdestroy___srcZniminiZplugin_u6661((*dest_p0).plugins.data);
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZplugin_u8764)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___srcZniminiZplugin_u6722(((tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZplugin_u6734)(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* dest_p0, void* env_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqtrace___srcZniminiZplugin_u6673((&(*dest_p0).plugins.data), env_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZplugin_u6745)(tyObject_PluginRegistrycolonObjectType___V39cfh9chfy20I8fZ8bR0gBg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__V39cfh9chfy20I8fZ8bR0gBg_))));
		if (!T3_) goto LA4_;
		eqdestroy___srcZniminiZplugin_u6722((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
