/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib_full/@ptimes.nim.c.o /workspaces/Storie/nimcache_wasm_raylib_full/@ptimes.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <time.h>
#include <string.h>
#include <sys/types.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw;
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0);
N_LIB_PRIVATE tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* utcInstance__pureZtimes_u2031;
N_LIB_PRIVATE tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* localInstance__pureZtimes_u2032;
extern NIM_BOOL nimInErrorMode__system_u4234;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, cpuTime__pureZtimes_u5308)(void) {
	NF result;
	struct timespec ts_1;
	int T1_;
	NF T2_;
	NF T3_;
	nimZeroMem((void*)(&ts_1), sizeof(struct timespec));
	T1_ = (int)0;
	T1_ = clock_gettime(((clockid_t) (CLOCK_THREAD_CPUTIME_ID)), (&ts_1));
	(void)(T1_);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1691(((NI) (ts_1.tv_sec)));
	T3_ = (NF)0;
	T3_ = toFloat__system_u1691(ts_1.tv_nsec);
	result = ((NF)(T2_) + (NF)(((NF)(T3_) / (NF)(1000000000.0))));
	return result;
}
