/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3-src/include -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-config-release -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-revision -I/workspaces/Storie/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_sdl_full/@msrc@snimini@sast.nim.c.o /workspaces/Storie/nimcache_wasm_sdl_full/@msrc@snimini@sast.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__fnmev9agYl6F9bZXpx2v9aq6A tySequence__fnmev9agYl6F9bZXpx2v9aq6A;
typedef struct tySequence__fnmev9agYl6F9bZXpx2v9aq6A_Content tySequence__fnmev9agYl6F9bZXpx2v9aq6A_Content;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg;
typedef struct tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ;
typedef struct tyTuple__lBireGel9cGbbGOTpgwUdwQ tyTuple__lBireGel9cGbbGOTpgwUdwQ;
typedef struct tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ;
typedef struct tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA;
typedef struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw tySequence__z9cyhh9cmbMWU4a3QzH1fgyw;
typedef struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content;
typedef struct tySequence__H2U9a7gvIFx9b6MLkmhmYyPg tySequence__H2U9a7gvIFx9b6MLkmhmYyPg;
typedef struct tySequence__H2U9a7gvIFx9b6MLkmhmYyPg_Content tySequence__H2U9a7gvIFx9b6MLkmhmYyPg_Content;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A;
typedef struct tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ;
typedef NU8 tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__fnmev9agYl6F9bZXpx2v9aq6A {
  NI len; tySequence__fnmev9agYl6F9bZXpx2v9aq6A_Content* p;
};
struct tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg {
	NI line;
	NI col;
	tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A kind;
union{
	struct {
	NI intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	NIM_BOOL boolVal;
} _kind_4;
	struct {
	NimStringV2 ident;
} _kind_5;
	struct {
	NimStringV2 op;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* left;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* right;
} _kind_6;
	struct {
	NimStringV2 unaryOp;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* unaryExpr;
} _kind_7;
	struct {
	NimStringV2 funcName;
	tySequence__fnmev9agYl6F9bZXpx2v9aq6A args;
} _kind_8;
	struct {
	tySequence__fnmev9agYl6F9bZXpx2v9aq6A elements;
} _kind_9;
	struct {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* indexTarget;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* indexExpr;
} _kind_10;
};
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ {
	NI len;
	NI cap;
	tyTuple__lBireGel9cGbbGOTpgwUdwQ* d;
};
struct tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg {
	tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA traceStack;
	tyObject_CellSeq__h159c0ZpKR8vbgG5c0l2IHQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef NU8 tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw;
struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw {
  NI len; tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content* p;
};
struct tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* cond;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw stmts;
};
struct tySequence__H2U9a7gvIFx9b6MLkmhmYyPg {
  NI len; tySequence__H2U9a7gvIFx9b6MLkmhmYyPg_Content* p;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ {
	NI line;
	NI col;
	tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw kind;
union{
	struct {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* expr;
} _kind_1;
	struct {
	NimStringV2 varName;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* varValue;
} _kind_2;
	struct {
	NimStringV2 letName;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* letValue;
} _kind_3;
	struct {
	NimStringV2 target;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* assignValue;
} _kind_4;
	struct {
	tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA ifBranch;
	tySequence__H2U9a7gvIFx9b6MLkmhmYyPg elifBranches;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw elseStmts;
} _kind_5;
	struct {
	NimStringV2 forVar;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* forIterable;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw forBody;
} _kind_6;
	struct {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* whileCond;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw whileBody;
} _kind_7;
	struct {
	NimStringV2 procName;
	tySequence__4eQHGndY6XBYpFOH09apV8Q params;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body;
} _kind_8;
	struct {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* returnVal;
} _kind_9;
	struct {
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw stmts;
} _kind_10;
};
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A {
	NI len;
	void* p;
};
struct tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ {
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw stmts;
};
struct tySequence__fnmev9agYl6F9bZXpx2v9aq6A_Content { NI cap; tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* data[SEQ_DECL_SIZE]; };
struct tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content { NI cap; tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* data[SEQ_DECL_SIZE]; };
struct tySequence__H2U9a7gvIFx9b6MLkmhmYyPg_Content { NI cap; tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA data[SEQ_DECL_SIZE]; };
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2645)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, eqdup___srcZniminiZast_u219)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* src_p0, NIM_BOOL cyclic_p1);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZast_u1451)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u106)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u144)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u118)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2);
static N_INLINE(void, add__system_u2954)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2962)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u156)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__fnmev9agYl6F9bZXpx2v9aq6A, eqdup___srcZniminiZast_u150)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__srcZniminiZast_u167)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZast_u1483)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u513)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u552)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u731)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u921)(tySequence__4eQHGndY6XBYpFOH09apV8Q dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u525)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u564)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u743)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw, eqdup___srcZniminiZast_u558)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__srcZniminiZast_u575)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__srcZniminiZast_u1382)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg* x_p0, tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___srcZniminiZast_u48)(tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___srcZniminiZast_u555)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* dest_p0, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, eqdup___srcZniminiZast_u927)(tySequence__4eQHGndY6XBYpFOH09apV8Q src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__srcZniminiZast_u942)(tySequence__4eQHGndY6XBYpFOH09apV8Q* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__srcZniminiZast_u754)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg* s_p0, NI newlen_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__1BCc4BIJdnxLzmcmzPIJXg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_;
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_4 = { 69 | NIM_STRLIT_FLAG, "field \'elifBranches\' is not accessible for type \'Stmt\' using \'kind = " };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_5 = {69, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_6 = { 6 | NIM_STRLIT_FLAG, "skExpr" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_7 = {6, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_8 = { 5 | NIM_STRLIT_FLAG, "skVar" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_9 = {5, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_8};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_10 = { 5 | NIM_STRLIT_FLAG, "skLet" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_11 = {5, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_10};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_12 = { 8 | NIM_STRLIT_FLAG, "skAssign" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_13 = {8, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_12};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_14 = { 4 | NIM_STRLIT_FLAG, "skIf" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_15 = {4, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_14};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_16 = { 5 | NIM_STRLIT_FLAG, "skFor" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_17 = {5, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_16};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_18 = { 7 | NIM_STRLIT_FLAG, "skWhile" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_19 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_18};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_20 = { 6 | NIM_STRLIT_FLAG, "skProc" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_21 = {6, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_20};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_22 = { 8 | NIM_STRLIT_FLAG, "skReturn" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_23 = {8, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_22};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_24 = { 7 | NIM_STRLIT_FLAG, "skBlock" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_25 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_24};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_26 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_27 = {0, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_26};
static const struct {
  NI cap; NIM_CHAR data[66+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_28 = { 66 | NIM_STRLIT_FLAG, "field \'elseStmts\' is not accessible for type \'Stmt\' using \'kind = " };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_29 = {66, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_28};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_30 = { 5 | NIM_STRLIT_FLAG, "ekInt" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_31 = {5, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_30};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_32 = { 7 | NIM_STRLIT_FLAG, "ekFloat" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_33 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_32};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_34 = { 8 | NIM_STRLIT_FLAG, "ekString" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_35 = {8, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_34};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_36 = { 6 | NIM_STRLIT_FLAG, "ekBool" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_37 = {6, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_36};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_38 = { 7 | NIM_STRLIT_FLAG, "ekIdent" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_39 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_38};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_40 = { 7 | NIM_STRLIT_FLAG, "ekBinOp" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_41 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_40};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_42 = { 9 | NIM_STRLIT_FLAG, "ekUnaryOp" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_43 = {9, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_42};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_44 = { 6 | NIM_STRLIT_FLAG, "ekCall" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_45 = {6, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_44};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_46 = { 7 | NIM_STRLIT_FLAG, "ekArray" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_47 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_46};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__egaGbf9cvcvVfE5PvoKJgvA_48 = { 7 | NIM_STRLIT_FLAG, "ekIndex" };
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_49 = {7, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_48};
static const NimStringV2 TM__egaGbf9cvcvVfE5PvoKJgvA_50 = {0, (NimStrPayload*)&TM__egaGbf9cvcvVfE5PvoKJgvA_26};
extern NIM_BOOL nimInErrorMode__system_u4234;
static NIM_CONST NU32 TM__egaGbf9cvcvVfE5PvoKJgvA_2[1] = {278716416};
N_LIB_PRIVATE TNimTypeV2 NTIv2__1BCc4BIJdnxLzmcmzPIJXg_ = {.destructor = (void*)rttiDestroy__srcZniminiZast_u1451, .size = sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), .align = (NI16) NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), .depth = 0, .display = TM__egaGbf9cvcvVfE5PvoKJgvA_2, .traceImpl = (void*)eqtrace___srcZniminiZast_u118, .flags = 0};
static NIM_CONST NU32 TM__egaGbf9cvcvVfE5PvoKJgvA_3[1] = {4196662016};
N_LIB_PRIVATE TNimTypeV2 NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_ = {.destructor = (void*)rttiDestroy__srcZniminiZast_u1483, .size = sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), .align = (NI16) NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), .depth = 0, .display = TM__egaGbf9cvcvVfE5PvoKJgvA_3, .traceImpl = (void*)eqtrace___srcZniminiZast_u525, .flags = 0};
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newInt__srcZniminiZast_u79)(NI v_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NI colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)0);
	colontmpD_ = v_p0;
	(*T1_)._kind_1.intVal = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newFloat__srcZniminiZast_u436)(NF v_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NF colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)1);
	colontmpD_ = v_p0;
	(*T1_)._kind_2.floatVal = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newString__srcZniminiZast_u441)(NimStringV2 v_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NimStringV2 colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)2);
	colontmpD_ = eqdup___system_u2645(v_p0);
	(*T1_)._kind_3.strVal = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newBool__srcZniminiZast_u446)(NIM_BOOL v_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NIM_BOOL colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)3);
	colontmpD_ = v_p0;
	(*T1_)._kind_4.boolVal = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) + (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* h_1;
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	h_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T1_));
	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, eqdup___srcZniminiZast_u219)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* src_p0, NIM_BOOL cyclic_p1) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmp_;
	result = NIM_NIL;
	colontmp_ = result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRefCyclic(src_p0, cyclic_p1);
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newUnaryOp__srcZniminiZast_u463)(NimStringV2 op_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* e_p1, NI line_p2, NI col_p3) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)6);
	colontmpD_ = eqdup___system_u2645(op_p0);
	(*T1_)._kind_7.unaryOp = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(e_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_7.unaryExpr = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, desc_p1);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u144)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicStatic(dest_p0.p->data[colontmp_], ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
				if (!T6_) goto LA7_;
				eqdestroy___srcZniminiZast_u106((&(*dest_p0.p->data[colontmp_])));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u106)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)0):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)1):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)2):
	{
		if ((*dest_p0)._kind_3.strVal.p && !((*dest_p0)._kind_3.strVal.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_3.strVal.p);
}
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)3):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)4):
	{
		if ((*dest_p0)._kind_5.ident.p && !((*dest_p0)._kind_5.ident.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_5.ident.p);
}
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)5):
	{
		{
			NIM_BOOL T9_;
			T9_ = (NIM_BOOL)0;
			T9_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_6.right, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T9_) goto LA10_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_6.right)));
			nimRawDispose((*dest_p0)._kind_6.right, ((NI)8));
		}
LA10_: ;
		{
			NIM_BOOL T14_;
			T14_ = (NIM_BOOL)0;
			T14_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_6.left, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T14_) goto LA15_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_6.left)));
			nimRawDispose((*dest_p0)._kind_6.left, ((NI)8));
		}
LA15_: ;
		if ((*dest_p0)._kind_6.op.p && !((*dest_p0)._kind_6.op.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_6.op.p);
}
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)6):
	{
		{
			NIM_BOOL T20_;
			T20_ = (NIM_BOOL)0;
			T20_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_7.unaryExpr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T20_) goto LA21_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_7.unaryExpr)));
			nimRawDispose((*dest_p0)._kind_7.unaryExpr, ((NI)8));
		}
LA21_: ;
		if ((*dest_p0)._kind_7.unaryOp.p && !((*dest_p0)._kind_7.unaryOp.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_7.unaryOp.p);
}
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)7):
	{
		eqdestroy___srcZniminiZast_u144((*dest_p0)._kind_8.args);
		if ((*dest_p0)._kind_8.funcName.p && !((*dest_p0)._kind_8.funcName.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_8.funcName.p);
}
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)8):
	{
		eqdestroy___srcZniminiZast_u144((*dest_p0)._kind_9.elements);
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)9):
	{
		{
			NIM_BOOL T28_;
			T28_ = (NIM_BOOL)0;
			T28_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_10.indexExpr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T28_) goto LA29_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_10.indexExpr)));
			nimRawDispose((*dest_p0)._kind_10.indexExpr, ((NI)8));
		}
LA29_: ;
		{
			NIM_BOOL T33_;
			T33_ = (NIM_BOOL)0;
			T33_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_10.indexTarget, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T33_) goto LA34_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_10.indexTarget)));
			nimRawDispose((*dest_p0)._kind_10.indexTarget, ((NI)8));
		}
LA34_: ;
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZast_u1451)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___srcZniminiZast_u106(((tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u2954)(tyObject_CellSeq__Y61EHKUy9bziu9aZLY53Z6TA* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u2962(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__P5mFx1YRqn2iTLyn6f3MWg*) (env_p2));
		add__system_u2954((&(*j_1).traceStack), p_1, desc_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u156)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A* dest_p0, void* env_p1) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest_p0).len;
			if (!(colontmp_ < T3_)) goto LA2;
			nimTraceRef(&(*dest_p0).p->data[colontmp_], ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u118)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* dest_p0, void* env_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch ((*dest_p0).kind) {
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)0):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)1):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)2):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)3):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)4):
	{
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)5):
	{
		nimTraceRef(&(*dest_p0)._kind_6.left, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
		nimTraceRef(&(*dest_p0)._kind_6.right, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)6):
	{
		nimTraceRef(&(*dest_p0)._kind_7.unaryExpr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)7):
	{
		eqtrace___srcZniminiZast_u156((&(*dest_p0)._kind_8.args), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)8):
	{
		eqtrace___srcZniminiZast_u156((&(*dest_p0)._kind_9.elements), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)9):
	{
		nimTraceRef(&(*dest_p0)._kind_10.indexTarget, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
		nimTraceRef(&(*dest_p0)._kind_10.indexExpr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u212)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
		if (!T3_) goto LA4_;
		eqdestroy___srcZniminiZast_u106((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZniminiZast_u209)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__fnmev9agYl6F9bZXpx2v9aq6A, eqdup___srcZniminiZast_u150)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A src_p0) {
	tySequence__fnmev9agYl6F9bZXpx2v9aq6A result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__srcZniminiZast_u167((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmp__2;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			colontmp__2 = result.p->data[colontmp_];
			result.p->data[colontmp_] = src_p0.p->data[colontmp_];
			{
				if (!src_p0.p->data[colontmp_]) goto LA7_;
				nimIncRefCyclic(src_p0.p->data[colontmp_], NIM_TRUE);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newCall__srcZniminiZast_u469)(NimStringV2 name_p0, tySequence__fnmev9agYl6F9bZXpx2v9aq6A args_p1, NI line_p2, NI col_p3) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NimStringV2 colontmpD_;
	tySequence__fnmev9agYl6F9bZXpx2v9aq6A colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)7);
	colontmpD_ = eqdup___system_u2645(name_p0);
	(*T1_)._kind_8.funcName = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u150(args_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_8.args = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newIdent__srcZniminiZast_u451)(NimStringV2 v_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NimStringV2 colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)4);
	colontmpD_ = eqdup___system_u2645(v_p0);
	(*T1_)._kind_5.ident = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newArray__srcZniminiZast_u475)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A elements_p0, NI line_p1, NI col_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	tySequence__fnmev9agYl6F9bZXpx2v9aq6A colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)8);
	colontmpD_ = eqdup___srcZniminiZast_u150(elements_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_9.elements = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___srcZniminiZast_u223)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg** dest_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* src_p1) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
		if (!T3_) goto LA4_;
		eqdestroy___srcZniminiZast_u106((&(*colontmp_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose(colontmp_, ((NI)8));
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newIndex__srcZniminiZast_u480)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* target_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* index_p1, NI line_p2, NI col_p3) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)9);
	colontmpD_ = eqdup___srcZniminiZast_u219(target_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_10.indexTarget = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(index_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_10.indexExpr = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*, newBinOp__srcZniminiZast_u456)(NimStringV2 op_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* l_p1, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* r_p2, NI line_p3, NI col_p4) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__3;
	NI colontmpD__4;
	NI colontmpD__5;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = (NI)0;
	colontmpD__5 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg*) nimNewObjUninit(sizeof(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg), NIM_ALIGNOF(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg));
	(*T1_).kind = ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)5);
	colontmpD_ = eqdup___system_u2645(op_p0);
	(*T1_)._kind_6.op = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(l_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_6.left = colontmpD__2;
	colontmpD__3 = eqdup___srcZniminiZast_u219(r_p2, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_6.right = colontmpD__3;
	colontmpD__4 = line_p3;
	(*T1_).line = colontmpD__4;
	colontmpD__5 = col_p4;
	(*T1_).col = colontmpD__5;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newLet__srcZniminiZast_u1244)(NimStringV2 name_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* val_p1, NI line_p2, NI col_p3) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)2);
	colontmpD_ = eqdup___system_u2645(name_p0);
	(*T1_)._kind_3.letName = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(val_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_3.letValue = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newVar__srcZniminiZast_u1238)(NimStringV2 name_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* val_p1, NI line_p2, NI col_p3) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)1);
	colontmpD_ = eqdup___system_u2645(name_p0);
	(*T1_)._kind_2.varName = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(val_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_2.varValue = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u552)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicStatic(dest_p0.p->data[colontmp_], ((TNimTypeV2*) ((&NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_))));
				if (!T6_) goto LA7_;
				eqdestroy___srcZniminiZast_u513((&(*dest_p0.p->data[colontmp_])));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)4));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u731)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			eqdestroy___srcZniminiZast_u552(dest_p0.p->data[colontmp_].stmts);
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicStatic(dest_p0.p->data[colontmp_].cond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
				if (!T6_) goto LA7_;
				eqdestroy___srcZniminiZast_u106((&(*dest_p0.p->data[colontmp_].cond)));
				nimRawDispose(dest_p0.p->data[colontmp_].cond, ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u921)(tySequence__4eQHGndY6XBYpFOH09apV8Q dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field0.p && !(dest_p0.p->data[colontmp_].Field0.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0.p->data[colontmp_].Field0.p);
}
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0.p->data[colontmp_].Field1.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u513)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)0):
	{
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_1.expr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T4_) goto LA5_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_1.expr)));
			nimRawDispose((*dest_p0)._kind_1.expr, ((NI)8));
		}
LA5_: ;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)1):
	{
		{
			NIM_BOOL T10_;
			T10_ = (NIM_BOOL)0;
			T10_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_2.varValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T10_) goto LA11_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_2.varValue)));
			nimRawDispose((*dest_p0)._kind_2.varValue, ((NI)8));
		}
LA11_: ;
		if ((*dest_p0)._kind_2.varName.p && !((*dest_p0)._kind_2.varName.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_2.varName.p);
}
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)2):
	{
		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_3.letValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T16_) goto LA17_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_3.letValue)));
			nimRawDispose((*dest_p0)._kind_3.letValue, ((NI)8));
		}
LA17_: ;
		if ((*dest_p0)._kind_3.letName.p && !((*dest_p0)._kind_3.letName.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_3.letName.p);
}
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)3):
	{
		{
			NIM_BOOL T22_;
			T22_ = (NIM_BOOL)0;
			T22_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_4.assignValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T22_) goto LA23_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_4.assignValue)));
			nimRawDispose((*dest_p0)._kind_4.assignValue, ((NI)8));
		}
LA23_: ;
		if ((*dest_p0)._kind_4.target.p && !((*dest_p0)._kind_4.target.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_4.target.p);
}
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)4):
	{
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_5.elseStmts);
		eqdestroy___srcZniminiZast_u731((*dest_p0)._kind_5.elifBranches);
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_5.ifBranch.stmts);
		{
			NIM_BOOL T28_;
			T28_ = (NIM_BOOL)0;
			T28_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_5.ifBranch.cond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T28_) goto LA29_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_5.ifBranch.cond)));
			nimRawDispose((*dest_p0)._kind_5.ifBranch.cond, ((NI)8));
		}
LA29_: ;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)5):
	{
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_6.forBody);
		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_6.forIterable, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T34_) goto LA35_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_6.forIterable)));
			nimRawDispose((*dest_p0)._kind_6.forIterable, ((NI)8));
		}
LA35_: ;
		if ((*dest_p0)._kind_6.forVar.p && !((*dest_p0)._kind_6.forVar.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_6.forVar.p);
}
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)6):
	{
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_7.whileBody);
		{
			NIM_BOOL T40_;
			T40_ = (NIM_BOOL)0;
			T40_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_7.whileCond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T40_) goto LA41_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_7.whileCond)));
			nimRawDispose((*dest_p0)._kind_7.whileCond, ((NI)8));
		}
LA41_: ;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)7):
	{
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_8.body);
		eqdestroy___srcZniminiZast_u921((*dest_p0)._kind_8.params);
		if ((*dest_p0)._kind_8.procName.p && !((*dest_p0)._kind_8.procName.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_8.procName.p);
}
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)8):
	{
		{
			NIM_BOOL T47_;
			T47_ = (NIM_BOOL)0;
			T47_ = nimDecRefIsLastCyclicStatic((*dest_p0)._kind_9.returnVal, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
			if (!T47_) goto LA48_;
			eqdestroy___srcZniminiZast_u106((&(*(*dest_p0)._kind_9.returnVal)));
			nimRawDispose((*dest_p0)._kind_9.returnVal, ((NI)8));
		}
LA48_: ;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)9):
	{
		eqdestroy___srcZniminiZast_u552((*dest_p0)._kind_10.stmts);
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__srcZniminiZast_u1483)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___srcZniminiZast_u513(((tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u564)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* dest_p0, void* env_p1) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest_p0).len;
			if (!(colontmp_ < T3_)) goto LA2;
			nimTraceRef(&(*dest_p0).p->data[colontmp_], ((TNimTypeV2*) ((&NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_))), env_p1);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u743)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg* dest_p0, void* env_p1) {
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest_p0).len;
			if (!(colontmp_ < T3_)) goto LA2;
			nimTraceRef(&(*dest_p0).p->data[colontmp_].cond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
			eqtrace___srcZniminiZast_u564((&(*dest_p0).p->data[colontmp_].stmts), env_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___srcZniminiZast_u525)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* dest_p0, void* env_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch ((*dest_p0).kind) {
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)0):
	{
		nimTraceRef(&(*dest_p0)._kind_1.expr, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)1):
	{
		nimTraceRef(&(*dest_p0)._kind_2.varValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)2):
	{
		nimTraceRef(&(*dest_p0)._kind_3.letValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)3):
	{
		nimTraceRef(&(*dest_p0)._kind_4.assignValue, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)4):
	{
		nimTraceRef(&(*dest_p0)._kind_5.ifBranch.cond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_5.ifBranch.stmts), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqtrace___srcZniminiZast_u743((&(*dest_p0)._kind_5.elifBranches), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_5.elseStmts), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)5):
	{
		nimTraceRef(&(*dest_p0)._kind_6.forIterable, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_6.forBody), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)6):
	{
		nimTraceRef(&(*dest_p0)._kind_7.whileCond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_7.whileBody), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)7):
	{
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_8.body), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)8):
	{
		nimTraceRef(&(*dest_p0)._kind_9.returnVal, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))), env_p1);
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)9):
	{
		eqtrace___srcZniminiZast_u564((&(*dest_p0)._kind_10.stmts), env_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u620)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_))));
		if (!T3_) goto LA4_;
		eqdestroy___srcZniminiZast_u513((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZniminiZast_u617)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw, eqdup___srcZniminiZast_u558)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw src_p0) {
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__srcZniminiZast_u575((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* colontmp__2;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			colontmp__2 = result.p->data[colontmp_];
			result.p->data[colontmp_] = src_p0.p->data[colontmp_];
			{
				if (!src_p0.p->data[colontmp_]) goto LA7_;
				nimIncRefCyclic(src_p0.p->data[colontmp_], NIM_TRUE);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newIf__srcZniminiZast_u1256)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* cond_p0, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p1, NI line_p2, NI col_p3) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)4);
	colontmpD_ = eqdup___srcZniminiZast_u219(cond_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_5.ifBranch.cond = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u558(body_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_5.ifBranch.stmts = colontmpD__2;
	(*T1_)._kind_5.elifBranches.len = 0; (*T1_)._kind_5.elifBranches.p = (tySequence__H2U9a7gvIFx9b6MLkmhmYyPg_Content*) newSeqPayload(0, sizeof(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA), NIM_ALIGNOF(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA));
	(*T1_)._kind_5.elseStmts.len = 0; (*T1_)._kind_5.elseStmts.p = (tySequence__z9cyhh9cmbMWU4a3QzH1fgyw_Content*) newSeqPayload(0, sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*));
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___srcZniminiZast_u48)(tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)0):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_7;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)1):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_9;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)2):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_11;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)3):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_13;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)4):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_15;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)5):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_17;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)6):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_19;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)7):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_21;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)8):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_23;
	}
	break;
	case ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)9):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_25;
	}
	break;
	default:
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_27;
	}
	break;
	}
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addElif__srcZniminiZast_u1378)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* s_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* cond_p1, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p2) {
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD__2;
	tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	if (!(((16 &((NU16)1<<((NU)(((*s_p0).kind))&15U)))!=0))) 	{ raiseFieldErrorStr(TM__egaGbf9cvcvVfE5PvoKJgvA_5, dollar___srcZniminiZast_u48((*s_p0).kind)); goto BeforeRet_;
	}
	nimZeroMem((void*)(&T1_), sizeof(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA));
	colontmpD_ = eqdup___srcZniminiZast_u219(cond_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.cond = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u558(body_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.stmts = colontmpD__2;
	add__srcZniminiZast_u1382((&(*s_p0)._kind_5.elifBranches), T1_);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A*) (x_p0))).p == (*((tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___srcZniminiZast_u555)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* dest_p0, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__srcZniminiZast_u575((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* colontmp__2;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			colontmp__2 = (*dest_p0).p->data[colontmp_];
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRefCyclic(src_p1.p->data[colontmp_], NIM_TRUE);
			}
LA12_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastCyclicStatic(colontmp__2, ((TNimTypeV2*) ((&NTIv2__e9coj9b3ErRGqFCDBo9bT5SbQ_))));
				if (!T16_) goto LA17_;
				eqdestroy___srcZniminiZast_u513((&(*colontmp__2)));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose(colontmp__2, ((NI)4));
			}
LA17_: ;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addElse__srcZniminiZast_u1402)(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* s_p0, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if (!(((16 &((NU16)1<<((NU)(((*s_p0).kind))&15U)))!=0))) 	{ raiseFieldErrorStr(TM__egaGbf9cvcvVfE5PvoKJgvA_29, dollar___srcZniminiZast_u48((*s_p0).kind)); goto BeforeRet_;
	}
	eqcopy___srcZniminiZast_u555((&(*s_p0)._kind_5.elseStmts), body_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newFor__srcZniminiZast_u1405)(NimStringV2 varName_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* iterable_p1, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p2, NI line_p3, NI col_p4) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD__3;
	NI colontmpD__4;
	NI colontmpD__5;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4 = (NI)0;
	colontmpD__5 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)5);
	colontmpD_ = eqdup___system_u2645(varName_p0);
	(*T1_)._kind_6.forVar = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(iterable_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_6.forIterable = colontmpD__2;
	colontmpD__3 = eqdup___srcZniminiZast_u558(body_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_6.forBody = colontmpD__3;
	colontmpD__4 = line_p3;
	(*T1_).line = colontmpD__4;
	colontmpD__5 = col_p4;
	(*T1_).col = colontmpD__5;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newWhile__srcZniminiZast_u1412)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* cond_p0, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p1, NI line_p2, NI col_p3) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)6);
	colontmpD_ = eqdup___srcZniminiZast_u219(cond_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_7.whileCond = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u558(body_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_7.whileBody = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u987)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZniminiZast_u984)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0) {
	(*dest_p0).Field0.len = 0; (*dest_p0).Field0.p = NIM_NIL;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, eqdup___srcZniminiZast_u927)(tySequence__4eQHGndY6XBYpFOH09apV8Q src_p0) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__srcZniminiZast_u942((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_].Field0 = eqdup___system_u2645(src_p0.p->data[colontmp_].Field0);
			result.p->data[colontmp_].Field1 = eqdup___system_u2645(src_p0.p->data[colontmp_].Field1);
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newProc__srcZniminiZast_u1418)(NimStringV2 name_p0, tySequence__4eQHGndY6XBYpFOH09apV8Q params_p1, tySequence__z9cyhh9cmbMWU4a3QzH1fgyw body_p2, NI line_p3, NI col_p4) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	NimStringV2 colontmpD_;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__2;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD__3;
	NI colontmpD__4;
	NI colontmpD__5;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4 = (NI)0;
	colontmpD__5 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)7);
	colontmpD_ = eqdup___system_u2645(name_p0);
	(*T1_)._kind_8.procName = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u927(params_p1);
	(*T1_)._kind_8.params = colontmpD__2;
	colontmpD__3 = eqdup___srcZniminiZast_u558(body_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_8.body = colontmpD__3;
	colontmpD__4 = line_p3;
	(*T1_).line = colontmpD__4;
	colontmpD__5 = col_p4;
	(*T1_).col = colontmpD__5;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newReturn__srcZniminiZast_u1425)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* val_p0, NI line_p1, NI col_p2) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)8);
	colontmpD_ = eqdup___srcZniminiZast_u219(val_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_9.returnVal = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newBlock__srcZniminiZast_u1430)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw stmts_p0, NI line_p1, NI col_p2) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	tySequence__z9cyhh9cmbMWU4a3QzH1fgyw colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)9);
	colontmpD_ = eqdup___srcZniminiZast_u558(stmts_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_10.stmts = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newAssign__srcZniminiZast_u1250)(NimStringV2 target_p0, tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* val_p1, NI line_p2, NI col_p3) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	NimStringV2 colontmpD_;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)3);
	colontmpD_ = eqdup___system_u2645(target_p0);
	(*T1_)._kind_4.target = colontmpD_;
	colontmpD__2 = eqdup___srcZniminiZast_u219(val_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_4.assignValue = colontmpD__2;
	colontmpD__3 = line_p2;
	(*T1_).line = colontmpD__3;
	colontmpD__4 = col_p3;
	(*T1_).col = colontmpD__4;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*, newExprStmt__srcZniminiZast_u486)(tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* e_p0, NI line_p1, NI col_p2) {
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* result;
	tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ*) nimNewObjUninit(sizeof(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ), NIM_ALIGNOF(tyObject_StmtcolonObjectType___e9coj9b3ErRGqFCDBo9bT5SbQ));
	(*T1_).kind = ((tyEnum_StmtKind__D8EDU79auTamhe1cnOIXjdw)0);
	colontmpD_ = eqdup___srcZniminiZast_u219(e_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_1.expr = colontmpD_;
	colontmpD__2 = line_p1;
	(*T1_).line = colontmpD__2;
	colontmpD__3 = col_p2;
	(*T1_).col = colontmpD__3;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZniminiZast_u549)(tySequence__z9cyhh9cmbMWU4a3QzH1fgyw* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZparser_u585)(tyObject_Program__N1ismuKdjTwwRdqZ0AWSnQ* dest_p0) {
	eqdestroy___srcZniminiZast_u552((*dest_p0).stmts);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___srcZniminiZast_u13)(tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)0):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_31;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)1):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_33;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)2):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_35;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)3):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_37;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)4):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_39;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)5):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_41;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)6):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_43;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)7):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_45;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)8):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_47;
	}
	break;
	case ((tyEnum_ExprKind__WjuAz8QTkRMXY39b9a8vjE7A)9):
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_49;
	}
	break;
	default:
	{
		result = TM__egaGbf9cvcvVfE5PvoKJgvA_50;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___srcZniminiZast_u147)(tySequence__fnmev9agYl6F9bZXpx2v9aq6A* dest_p0, tySequence__fnmev9agYl6F9bZXpx2v9aq6A src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__srcZniminiZast_u167((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmp__2;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			colontmp__2 = (*dest_p0).p->data[colontmp_];
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRefCyclic(src_p1.p->data[colontmp_], NIM_TRUE);
			}
LA12_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastCyclicStatic(colontmp__2, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
				if (!T16_) goto LA17_;
				eqdestroy___srcZniminiZast_u106((&(*colontmp__2)));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose(colontmp__2, ((NI)8));
			}
LA17_: ;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZniminiZast_u799)(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA* dest_p0) {
	eqdestroy___srcZniminiZast_u552((*dest_p0).stmts);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic((*dest_p0).cond, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
		if (!T3_) goto LA4_;
		eqdestroy___srcZniminiZast_u106((&(*(*dest_p0).cond)));
		nimRawDispose((*dest_p0).cond, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZniminiZast_u796)(tyObject_IfBranch__YDp2CB7EcdSHbHIen1leUA* dest_p0) {
	(*dest_p0).cond = 0;
	(*dest_p0).stmts.len = 0; (*dest_p0).stmts.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___srcZniminiZast_u734)(tySequence__H2U9a7gvIFx9b6MLkmhmYyPg* dest_p0, tySequence__H2U9a7gvIFx9b6MLkmhmYyPg src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__srcZniminiZast_u754((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			tyObject_ExprcolonObjectType___1BCc4BIJdnxLzmcmzPIJXg* colontmp__2;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			colontmp__2 = (*dest_p0).p->data[colontmp_].cond;
			{
				if (!src_p1.p->data[colontmp_].cond) goto LA12_;
				nimIncRefCyclic(src_p1.p->data[colontmp_].cond, NIM_TRUE);
			}
LA12_: ;
			(*dest_p0).p->data[colontmp_].cond = src_p1.p->data[colontmp_].cond;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastCyclicStatic(colontmp__2, ((TNimTypeV2*) ((&NTIv2__1BCc4BIJdnxLzmcmzPIJXg_))));
				if (!T16_) goto LA17_;
				eqdestroy___srcZniminiZast_u106((&(*colontmp__2)));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose(colontmp__2, ((NI)8));
			}
LA17_: ;
			eqcopy___srcZniminiZast_u555((&(*dest_p0).p->data[colontmp_].stmts), src_p1.p->data[colontmp_].stmts);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
