/**
 * Build script: Copy site files to docs/ after library build
 */

import { copyFileSync, mkdirSync, readdirSync, statSync, existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rootDir = join(__dirname, '..');
const siteDir = join(rootDir, 'site');
const docsDir = join(rootDir, 'docs');

// Ensure docs directory exists
if (!existsSync(docsDir)) {
  mkdirSync(docsDir, { recursive: true });
}

/**
 * Recursively copy directory
 */
function copyDir(src, dest) {
  // Create destination directory
  if (!existsSync(dest)) {
    mkdirSync(dest, { recursive: true });
  }

  const entries = readdirSync(src);

  for (const entry of entries) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    const stat = statSync(srcPath);

    if (stat.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
      console.log(`  Copied: ${entry}`);
    }
  }
}

console.log('📦 Building S|torie...\n');

console.log('Generating favicons...');
execSync('npm run generate-favicons', { stdio: 'inherit' });

console.log('Copying site files to docs/...');
copyDir(siteDir, docsDir);

// Bust caches for the JS library import in docs/index.html.
// Tauri/WebView environments can aggressively cache module URLs; if the query
// string is fixed, a rebuild may still load an old bundle.
try {
  const indexPath = join(docsDir, 'index.html');
  if (existsSync(indexPath)) {
    const buildId = new Date().toISOString();
    const html = readFileSync(indexPath, 'utf8');
    const nextHtml = html.replace(/__BUILD_ID__/g, buildId);
    writeFileSync(indexPath, nextHtml);
    console.log(`  Updated: index.html cache-buster (?v=${buildId})`);
  }
} catch (e) {
  console.warn('  ⚠ Failed to update index.html cache-buster:', e);
}

// Create warning README
const warningReadme = `# ⚠️ AUTO-GENERATED DIRECTORY

**DO NOT EDIT FILES IN THIS DIRECTORY DIRECTLY**

This folder is automatically generated by the build process and served by GitHub Pages.

## Source Files

- **HTML/Static files**: Edit in \`/site/\` directory
- **JavaScript library**: Edit TypeScript files in \`/src/\` directory

## Build Process

\`\`\`bash
npm run build
\`\`\`

This will:
1. Compile TypeScript (\`src/\`) → JavaScript
2. Bundle with Vite → \`docs/storie.*.js\`
3. Copy \`site/\` contents → \`docs/\`

## Deployment

This folder is served at: https://maddestlabs.github.io/storie/

Changes pushed to \`main\` branch are automatically deployed by GitHub Pages.

## To Make Changes

1. Edit files in \`/site/\` or \`/src/\` directories
2. Run \`npm run build\`
3. Test locally: \`npm run preview\`
4. Commit both source and built files
5. Push to deploy

---

**Last built:** ${new Date().toISOString()}
`;

writeFileSync(join(docsDir, 'AUTO_GENERATED_README.md'), warningReadme);
console.log('  Created: AUTO_GENERATED_README.md');

// Create .nojekyll for GitHub Pages
writeFileSync(join(docsDir, '.nojekyll'), '');
console.log('  Created: .nojekyll');

console.log('\n✅ Build complete!');
console.log('📁 Output: /docs/ directory');
console.log('🌐 Preview: npm run preview');
