/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3-src/include -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-config-release -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-revision -I/workspaces/Storie/vendor/SDL_ttf-src/include   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_sdl/@mplatform@srender3d_interface.nim.c.o /workspaces/Storie/nimcache_wasm_sdl/@mplatform@srender3d_interface.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw;
typedef struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content tySequence__uFLLGQVsiasALrzzzvqnZw_Content;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NF32 tyArray__EH3vwk2gvJbf6WGsCM9baJQ[16];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  NI len; tySequence__uFLLGQVsiasALrzzzvqnZw_Content* p;
};
struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	tySequence__uFLLGQVsiasALrzzzvqnZw indices;
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ {
	NF32 x;
	NF32 y;
	NF32 z;
};
struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ position;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ up;
	NF32 fov;
	NF32 near;
	NF32 far;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content { NI cap; NU16 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZrender3d95interface_u261)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u7722)(NimStringV2 errormsg_p0, NI errorcode_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZrender3d95interface_u266)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZrender3d95interface_u269)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3);
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZrender3d95interface_u275)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZrender3d95interface_u278)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2);
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZrender3d95interface_u283)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1);
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZrender3d95interface_u287)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg mesh_p1);
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZrender3d95interface_u291)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u197)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, lookAt__platformZrender3d95interface_u133)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ eye_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target_p1, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ up_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, normalize__platformZrender3d95interface_u101)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0);
N_LIB_PRIVATE N_NIMCALL(NF32, length__platformZrender3d95interface_u98)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, vec3__platformZrender3d95interface_u20)(NF32 x_p0, NF32 y_p1, NF32 z_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, minus___platformZrender3d95interface_u78)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, cross__platformZrender3d95interface_u94)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1);
N_LIB_PRIVATE N_NIMCALL(void, identity__platformZrender3d95interface_u105)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(NF32, dot__platformZrender3d95interface_u90)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1);
N_LIB_PRIVATE N_NIMCALL(void, perspective__platformZrender3d95interface_u107)(NF32 fov_p0, NF32 aspect_p1, NF32 near_p2, NF32 far_p3, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, eqdup___platformZrender3d95interface_u34)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ src_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, pluseq___platformZrender3d95interface_u185)(NF32* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u437)(tySequence__uFLLGQVsiasALrzzzvqnZw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u314)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u323)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest_p0, tySequence__4Xyxy0Om14N6K1l5e9bUPSQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u446)(tySequence__uFLLGQVsiasALrzzzvqnZw* dest_p0, tySequence__uFLLGQVsiasALrzzzvqnZw src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZrender3d95interface_u589)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZrender3d95interface_u641)(tySequence__uFLLGQVsiasALrzzzvqnZw* x_p0, NU16 y_p1);
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_2 = { 38 | NIM_STRLIT_FLAG, "Renderer3D.init3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_3 = {38, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_2};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_4 = { 42 | NIM_STRLIT_FLAG, "Renderer3D.shutdown3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_5 = {42, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_4};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_6 = { 44 | NIM_STRLIT_FLAG, "Renderer3D.beginFrame3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_7 = {44, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_6};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_8 = { 42 | NIM_STRLIT_FLAG, "Renderer3D.endFrame3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_9 = {42, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_8};
static const struct {
  NI cap; NIM_CHAR data[41+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_10 = { 41 | NIM_STRLIT_FLAG, "Renderer3D.setCamera() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_11 = {41, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_10};
static const struct {
  NI cap; NIM_CHAR data[49+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_12 = { 49 | NIM_STRLIT_FLAG, "Renderer3D.setModelTransform() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_13 = {49, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_12};
static const struct {
  NI cap; NIM_CHAR data[40+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_14 = { 40 | NIM_STRLIT_FLAG, "Renderer3D.drawMesh() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_15 = {40, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_14};
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_16 = { 43 | NIM_STRLIT_FLAG, "Renderer3D.setViewport() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_17 = {43, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_16};
extern TFrame* framePtr__system_u2675;
extern NIM_BOOL nimInErrorMode__system_u4277;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2675 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2675).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2675;
	framePtr__system_u2675 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4495();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2675 = (*framePtr__system_u2675).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZrender3d95interface_u261)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	NIM_BOOL result;
	nimfr_("init3D", "/workspaces/Storie/platform/render3d_interface.nim");
	result = (NIM_BOOL)0;
	nimlf_(186, "/workspaces/Storie/platform/render3d_interface.nim");	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_3, ((NI)1));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZrender3d95interface_u266)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	nimfr_("shutdown3D", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(189);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_5, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZrender3d95interface_u269)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3) {
	nimfr_("beginFrame3D", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(192);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_7, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZrender3d95interface_u275)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	nimfr_("endFrame3D", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(195);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_9, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZrender3d95interface_u278)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2) {
	nimfr_("setCamera", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(198);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_11, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZrender3d95interface_u283)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1) {
	nimfr_("setModelTransform", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(201);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_13, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZrender3d95interface_u287)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg mesh_p1) {
	nimfr_("drawMesh", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(204);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_15, ((NI)1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZrender3d95interface_u291)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4) {
	nimfr_("setViewport", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(207);	quit__system_u7722(TM__0AG1Bhfktbzesi9cL0Iv9bng_17, ((NI)1));
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(364, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimln_(353);	nimln_(357);	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) + (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");
	nimlf_(88, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	nimln_(88);	(*((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T2_))).rc, ((NI)16));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");
	nimln_(219);	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u197)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___platformZrender3d95interface_u230)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw** dest_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___platformZrender3d95interface_u197((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4277);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NF32, length__platformZrender3d95interface_u98)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0) {
	NF32 result;
	nimfr_("length", "/workspaces/Storie/platform/render3d_interface.nim");
	nimlf_(60, "/workspaces/Storie/platform/render3d_interface.nim");	result = sqrtf(((NF32)(((NF32)(((NF32)(v_p0.x) * (NF32)(v_p0.x))) + (NF32)(((NF32)(v_p0.y) * (NF32)(v_p0.y))))) + (NF32)(((NF32)(v_p0.z) * (NF32)(v_p0.z)))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, vec3__platformZrender3d95interface_u20)(NF32 x_p0, NF32 y_p1, NF32 z_p2) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	nimfr_("vec3", "/workspaces/Storie/platform/render3d_interface.nim");
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	nimln_(32);	colontmpD_ = x_p0;
	result.x = colontmpD_;
	colontmpD__2 = y_p1;
	result.y = colontmpD__2;
	colontmpD__3 = z_p2;
	result.z = colontmpD__3;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, normalize__platformZrender3d95interface_u101)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ v_p0) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD_;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD__2;
	NF32 len_1;
NIM_BOOL* nimErr_;
	nimfr_("normalize", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimln_(63);	len_1 = length__platformZrender3d95interface_u98(v_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(64);	{
		if (!(0.0001 < ((NF) (len_1)))) goto LA3_;
		nimln_(65);		colontmpD_ = vec3__platformZrender3d95interface_u20(((NF32)(v_p0.x) / (NF32)(len_1)), ((NF32)(v_p0.y) / (NF32)(len_1)), ((NF32)(v_p0.z) / (NF32)(len_1)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(67);		colontmpD__2 = vec3__platformZrender3d95interface_u20(0.0f, 0.0f, 0.0f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, minus___platformZrender3d95interface_u78)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
NIM_BOOL* nimErr_;
	nimfr_("-", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimln_(41);	result = vec3__platformZrender3d95interface_u20(((NF32)(a_p0.x) - (NF32)(b_p1.x)), ((NF32)(a_p0.y) - (NF32)(b_p1.y)), ((NF32)(a_p0.z) - (NF32)(b_p1.z)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, cross__platformZrender3d95interface_u94)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
NIM_BOOL* nimErr_;
	nimfr_("cross", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimln_(53);	nimln_(54);	nimln_(55);	nimln_(56);	nimln_(53);	result = vec3__platformZrender3d95interface_u20(((NF32)(((NF32)(a_p0.y) * (NF32)(b_p1.z))) - (NF32)(((NF32)(a_p0.z) * (NF32)(b_p1.y)))), ((NF32)(((NF32)(a_p0.z) * (NF32)(b_p1.x))) - (NF32)(((NF32)(a_p0.x) * (NF32)(b_p1.z)))), ((NF32)(((NF32)(a_p0.x) * (NF32)(b_p1.y))) - (NF32)(((NF32)(a_p0.y) * (NF32)(b_p1.x)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, identity__platformZrender3d95interface_u105)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	nimfr_("identity", "/workspaces/Storie/platform/render3d_interface.nim");
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(74);	Result[(((NI)0))- 0] = 1.0f;
	Result[(((NI)5))- 0] = 1.0f;
	Result[(((NI)10))- 0] = 1.0f;
	Result[(((NI)15))- 0] = 1.0f;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NF32, dot__platformZrender3d95interface_u90)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ a_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ b_p1) {
	NF32 result;
	nimfr_("dot", "/workspaces/Storie/platform/render3d_interface.nim");
	nimln_(50);	result = ((NF32)(((NF32)(((NF32)(a_p0.x) * (NF32)(b_p1.x))) + (NF32)(((NF32)(a_p0.y) * (NF32)(b_p1.y))))) + (NF32)(((NF32)(a_p0.z) * (NF32)(b_p1.z))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, lookAt__platformZrender3d95interface_u133)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ eye_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target_p1, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ up_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ f_1;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ T1_;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ s_1;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ T2_;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ u_1;
	NF32 T3_;
	NF32 T4_;
	NF32 T5_;
NIM_BOOL* nimErr_;
	nimfr_("lookAt", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(87);	T1_ = minus___platformZrender3d95interface_u78(target_p1, eye_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	f_1 = normalize__platformZrender3d95interface_u101(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);	T2_ = cross__platformZrender3d95interface_u94(f_1, up_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	s_1 = normalize__platformZrender3d95interface_u101(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(89);	u_1 = cross__platformZrender3d95interface_u94(s_1, f_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(91);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(92);	Result[(((NI)0))- 0] = s_1.x;
	nimln_(93);	Result[(((NI)4))- 0] = s_1.y;
	nimln_(94);	Result[(((NI)8))- 0] = s_1.z;
	nimln_(95);	Result[(((NI)1))- 0] = u_1.x;
	nimln_(96);	Result[(((NI)5))- 0] = u_1.y;
	nimln_(97);	Result[(((NI)9))- 0] = u_1.z;
	nimln_(98);	Result[(((NI)2))- 0] = -(f_1.x);
	nimln_(99);	Result[(((NI)6))- 0] = -(f_1.y);
	nimln_(100);	Result[(((NI)10))- 0] = -(f_1.z);
	nimln_(101);	T3_ = (NF32)0;
	T3_ = dot__platformZrender3d95interface_u90(s_1, eye_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)12))- 0] = -(T3_);
	nimln_(102);	T4_ = (NF32)0;
	T4_ = dot__platformZrender3d95interface_u90(u_1, eye_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)13))- 0] = -(T4_);
	nimln_(103);	T5_ = (NF32)0;
	T5_ = dot__platformZrender3d95interface_u90(f_1, eye_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)14))- 0] = T5_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, getViewMatrix__platformZrender3d95interface_u249)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("getViewMatrix", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(166);	lookAt__platformZrender3d95interface_u133((*cam_p0).position, (*cam_p0).target, (*cam_p0).up, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, perspective__platformZrender3d95interface_u107)(NF32 fov_p0, NF32 aspect_p1, NF32 near_p2, NF32 far_p3, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF tanHalfFov_1;
NIM_BOOL* nimErr_;
	nimfr_("perspective", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(77);	tanHalfFov_1 = tan(((NF)(((NF)(((NF) (fov_p0))) * (NF)(3.141592653589793))) / (NF)(360.0)));
	nimln_(78);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(79);	Result[(((NI)0))- 0] = ((NF32) (((NF)(1.0) / (NF)(((NF)(((NF) (aspect_p1))) * (NF)(tanHalfFov_1))))));
	nimln_(80);	Result[(((NI)5))- 0] = ((NF32) (((NF)(1.0) / (NF)(tanHalfFov_1))));
	nimln_(81);	Result[(((NI)10))- 0] = ((NF32)(-(((NF32)(far_p3) + (NF32)(near_p2)))) / (NF32)(((NF32)(far_p3) - (NF32)(near_p2))));
	nimln_(82);	Result[(((NI)11))- 0] = -1.0f;
	nimln_(83);	Result[(((NI)14))- 0] = ((NF32) (((NF)(-(((NF)(((NF)(2.0) * (NF)(((NF) (far_p3))))) * (NF)(((NF) (near_p2)))))) / (NF)(((NF) (((NF32)(far_p3) - (NF32)(near_p2))))))));
	nimln_(84);	Result[(((NI)15))- 0] = 0.0f;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, getProjectionMatrix__platformZrender3d95interface_u252)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0, NF32 aspect_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("getProjectionMatrix", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(169);	perspective__platformZrender3d95interface_u107((*cam_p0).fov, aspect_p1, (*cam_p0).near, (*cam_p0).far, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u236)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw** dest_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___platformZrender3d95interface_u197((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, eqdup___platformZrender3d95interface_u34)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ src_p0) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	result.x = src_p0.x;
	result.y = src_p0.y;
	result.z = src_p0.z;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw*, newCamera3D__platformZrender3d95interface_u189)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ position_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target_p1, NF32 fov_p2) {
	tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* result;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD_;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD__2;
	NF32 colontmpD__3;
	tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newCamera3D", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	colontmpD__3 = (NF32)0;
	nimln_(156);	T1_ = NIM_NIL;
	T1_ = (tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw*) nimNewObjUninit(sizeof(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw), NIM_ALIGNOF(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw));
	nimln_(157);	nimln_(32);	colontmpD_ = eqdup___platformZrender3d95interface_u34(position_p0);
	(*T1_).position = colontmpD_;
	nimln_(158);	nimln_(32);	colontmpD__2 = eqdup___platformZrender3d95interface_u34(target_p1);
	(*T1_).target = colontmpD__2;
	nimln_(159);	(*T1_).up = vec3__platformZrender3d95interface_u20(0.0f, 1.0f, 0.0f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(160);	colontmpD__3 = fov_p2;
	(*T1_).fov = colontmpD__3;
	(*T1_).near = 0.1f;
	(*T1_).far = 1000.0f;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u227)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___platformZrender3d95interface_u197((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
static N_INLINE(void, pluseq___platformZrender3d95interface_u185)(NF32* x_p0, NF32 y_p1) {
	nimfr_("+=", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(330, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	(*x_p0) = ((NF32)((*x_p0)) + (NF32)(y_p1));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, star___platformZrender3d95interface_u166)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ a_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ b_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	nimfr_("*", "/workspaces/Storie/platform/render3d_interface.nim");
{	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_28;
				if (!(res_1 <= ((NI)3))) goto LA3;
				nimlf_(145, "/workspaces/Storie/platform/render3d_interface.nim");				i_1 = ((NI) (res_1));
				{
					NI j_1;
					NI res_2;
					j_1 = (NI)0;
					nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");					res_2 = ((NI)0);
					{
						nimln_(97);						while (1) {
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_18;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_19;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_27;
							if (!(res_2 <= ((NI)3))) goto LA6;
							nimlf_(146, "/workspaces/Storie/platform/render3d_interface.nim");							j_1 = ((NI) (res_2));
							nimln_(147);							if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_18)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_18), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_19)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19), 15); goto BeforeRet_;
							}
							Result[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19))- 0] = 0.0f;
							{
								NI k_1;
								NI res_3;
								k_1 = (NI)0;
								nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");								res_3 = ((NI)0);
								{
									nimln_(97);									while (1) {
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_20;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_21;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_22;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_23;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_24;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_25;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_26;
										if (!(res_3 <= ((NI)3))) goto LA9;
										nimlf_(148, "/workspaces/Storie/platform/render3d_interface.nim");										k_1 = ((NI) (res_3));
										nimln_(149);										if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_20)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_20), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_21)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21), 15); goto BeforeRet_;
										}
										if (nimMulInt(k_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_22)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_22), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_23)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23), 15); goto BeforeRet_;
										}
										if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_24)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_24), k_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_25)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25), 15); goto BeforeRet_;
										}
										pluseq___platformZrender3d95interface_u185((&Result[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21))- 0]), ((NF32)(a_p0[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23))- 0]) * (NF32)(b_p1[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25))- 0])));
										nimlf_(102, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");										if (nimAddInt(res_3, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_26)) { raiseOverflow(); goto BeforeRet_;
										};
										res_3 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_26);
									} LA9: ;
								}
							}
							if (nimAddInt(res_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_27)) { raiseOverflow(); goto BeforeRet_;
							};
							res_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_27);
						} LA6: ;
					}
				}
				if (nimAddInt(res_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_28)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_28);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, translate__platformZrender3d95interface_u141)(NF32 x_p0, NF32 y_p1, NF32 z_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("translate", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimlf_(106, "/workspaces/Storie/platform/render3d_interface.nim");	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(107);	Result[(((NI)12))- 0] = x_p0;
	nimln_(108);	Result[(((NI)13))- 0] = y_p1;
	nimln_(109);	Result[(((NI)14))- 0] = z_p2;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, rotateX__platformZrender3d95interface_u151)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
	nimfr_("rotateX", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(118);	c_1 = cosf(angle_p0);
	nimln_(119);	s_1 = sinf(angle_p0);
	nimln_(120);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(121);	Result[(((NI)5))- 0] = c_1;
	nimln_(122);	Result[(((NI)6))- 0] = s_1;
	nimln_(123);	Result[(((NI)9))- 0] = -(s_1);
	nimln_(124);	Result[(((NI)10))- 0] = c_1;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, rotateY__platformZrender3d95interface_u156)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
	nimfr_("rotateY", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(127);	c_1 = cosf(angle_p0);
	nimln_(128);	s_1 = sinf(angle_p0);
	nimln_(129);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(130);	Result[(((NI)0))- 0] = c_1;
	nimln_(131);	Result[(((NI)2))- 0] = -(s_1);
	nimln_(132);	Result[(((NI)8))- 0] = s_1;
	nimln_(133);	Result[(((NI)10))- 0] = c_1;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, rotateZ__platformZrender3d95interface_u161)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
	nimfr_("rotateZ", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(136);	c_1 = cosf(angle_p0);
	nimln_(137);	s_1 = sinf(angle_p0);
	nimln_(138);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(139);	Result[(((NI)0))- 0] = c_1;
	nimln_(140);	Result[(((NI)1))- 0] = s_1;
	nimln_(141);	Result[(((NI)4))- 0] = -(s_1);
	nimln_(142);	Result[(((NI)5))- 0] = c_1;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, scale__platformZrender3d95interface_u146)(NF32 x_p0, NF32 y_p1, NF32 z_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("scale", "/workspaces/Storie/platform/render3d_interface.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(112);	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(113);	Result[(((NI)0))- 0] = x_p0;
	nimln_(114);	Result[(((NI)5))- 0] = y_p1;
	nimln_(115);	Result[(((NI)10))- 0] = z_p2;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u371)(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg* dest_p0) {
	eqdestroy___platformZrender3d95interface_u437((*dest_p0).indices);
	eqdestroy___platformZrender3d95interface_u314((*dest_p0).vertices);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg, createCubeMeshData__platformZrender3d95interface_u298)(NF32 size_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ color_p1) {
	tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg result;
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	NF32 colontmpD__4;
	NF32 colontmpD__5;
	NF32 colontmpD__6;
	NF32 colontmpD__7;
	NF32 colontmpD__8;
	NF32 colontmpD__9;
	NF32 colontmpD__10;
	NF32 colontmpD__11;
	NF32 colontmpD__12;
	NF32 colontmpD__13;
	NF32 colontmpD__14;
	NF32 colontmpD__15;
	NF32 colontmpD__16;
	NF32 colontmpD__17;
	NF32 colontmpD__18;
	NF32 colontmpD__19;
	NF32 colontmpD__20;
	NF32 colontmpD__21;
	NF32 colontmpD__22;
	NF32 colontmpD__23;
	NF32 colontmpD__24;
	NF32 s_1;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ T1_;
	tySequence__uFLLGQVsiasALrzzzvqnZw T2_;
	nimfr_("createCubeMeshData", "/workspaces/Storie/platform/render3d_interface.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg));
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	colontmpD__4 = (NF32)0;
	colontmpD__5 = (NF32)0;
	colontmpD__6 = (NF32)0;
	colontmpD__7 = (NF32)0;
	colontmpD__8 = (NF32)0;
	colontmpD__9 = (NF32)0;
	colontmpD__10 = (NF32)0;
	colontmpD__11 = (NF32)0;
	colontmpD__12 = (NF32)0;
	colontmpD__13 = (NF32)0;
	colontmpD__14 = (NF32)0;
	colontmpD__15 = (NF32)0;
	colontmpD__16 = (NF32)0;
	colontmpD__17 = (NF32)0;
	colontmpD__18 = (NF32)0;
	colontmpD__19 = (NF32)0;
	colontmpD__20 = (NF32)0;
	colontmpD__21 = (NF32)0;
	colontmpD__22 = (NF32)0;
	colontmpD__23 = (NF32)0;
	colontmpD__24 = (NF32)0;
	nimln_(215);	s_1 = ((NF32)(size_p0) / (NF32)(2.0f));
	nimln_(216);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 48; T1_.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(48, sizeof(NF32), NIM_ALIGNOF(NF32));
	nimln_(218);	T1_.p->data[0] = -(s_1);
	T1_.p->data[1] = -(s_1);
	T1_.p->data[2] = s_1;
	colontmpD_ = color_p1.x;
	T1_.p->data[3] = colontmpD_;
	colontmpD__2 = color_p1.y;
	T1_.p->data[4] = colontmpD__2;
	colontmpD__3 = color_p1.z;
	T1_.p->data[5] = colontmpD__3;
	T1_.p->data[6] = s_1;
	nimln_(219);	T1_.p->data[7] = -(s_1);
	T1_.p->data[8] = s_1;
	colontmpD__4 = color_p1.x;
	T1_.p->data[9] = colontmpD__4;
	colontmpD__5 = color_p1.y;
	T1_.p->data[10] = colontmpD__5;
	colontmpD__6 = color_p1.z;
	T1_.p->data[11] = colontmpD__6;
	T1_.p->data[12] = s_1;
	T1_.p->data[13] = s_1;
	T1_.p->data[14] = s_1;
	nimln_(220);	colontmpD__7 = color_p1.x;
	T1_.p->data[15] = colontmpD__7;
	colontmpD__8 = color_p1.y;
	T1_.p->data[16] = colontmpD__8;
	colontmpD__9 = color_p1.z;
	T1_.p->data[17] = colontmpD__9;
	nimln_(221);	T1_.p->data[18] = -(s_1);
	T1_.p->data[19] = s_1;
	T1_.p->data[20] = s_1;
	colontmpD__10 = color_p1.x;
	T1_.p->data[21] = colontmpD__10;
	colontmpD__11 = color_p1.y;
	T1_.p->data[22] = colontmpD__11;
	colontmpD__12 = color_p1.z;
	T1_.p->data[23] = colontmpD__12;
	nimln_(223);	T1_.p->data[24] = -(s_1);
	T1_.p->data[25] = -(s_1);
	T1_.p->data[26] = -(s_1);
	colontmpD__13 = color_p1.x;
	T1_.p->data[27] = colontmpD__13;
	colontmpD__14 = color_p1.y;
	T1_.p->data[28] = colontmpD__14;
	colontmpD__15 = color_p1.z;
	T1_.p->data[29] = colontmpD__15;
	T1_.p->data[30] = s_1;
	nimln_(224);	T1_.p->data[31] = -(s_1);
	T1_.p->data[32] = -(s_1);
	colontmpD__16 = color_p1.x;
	T1_.p->data[33] = colontmpD__16;
	colontmpD__17 = color_p1.y;
	T1_.p->data[34] = colontmpD__17;
	colontmpD__18 = color_p1.z;
	T1_.p->data[35] = colontmpD__18;
	T1_.p->data[36] = s_1;
	T1_.p->data[37] = s_1;
	nimln_(225);	T1_.p->data[38] = -(s_1);
	colontmpD__19 = color_p1.x;
	T1_.p->data[39] = colontmpD__19;
	colontmpD__20 = color_p1.y;
	T1_.p->data[40] = colontmpD__20;
	colontmpD__21 = color_p1.z;
	T1_.p->data[41] = colontmpD__21;
	nimln_(226);	T1_.p->data[42] = -(s_1);
	T1_.p->data[43] = s_1;
	T1_.p->data[44] = -(s_1);
	colontmpD__22 = color_p1.x;
	T1_.p->data[45] = colontmpD__22;
	colontmpD__23 = color_p1.y;
	T1_.p->data[46] = colontmpD__23;
	colontmpD__24 = color_p1.z;
	T1_.p->data[47] = colontmpD__24;
	nimln_(216);	eqsink___platformZrender3d95interface_u323((&result.vertices), T1_);
	nimln_(229);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 36; T2_.p = (tySequence__uFLLGQVsiasALrzzzvqnZw_Content*) newSeqPayload(36, sizeof(NU16), NIM_ALIGNOF(NU16));
	T2_.p->data[0] = ((NU16)0);
	T2_.p->data[1] = ((NU16)1);
	T2_.p->data[2] = ((NU16)2);
	T2_.p->data[3] = ((NU16)2);
	T2_.p->data[4] = ((NU16)3);
	T2_.p->data[5] = ((NU16)0);
	T2_.p->data[6] = ((NU16)1);
	T2_.p->data[7] = ((NU16)5);
	T2_.p->data[8] = ((NU16)6);
	T2_.p->data[9] = ((NU16)6);
	T2_.p->data[10] = ((NU16)2);
	T2_.p->data[11] = ((NU16)1);
	T2_.p->data[12] = ((NU16)5);
	T2_.p->data[13] = ((NU16)4);
	T2_.p->data[14] = ((NU16)7);
	T2_.p->data[15] = ((NU16)7);
	T2_.p->data[16] = ((NU16)6);
	T2_.p->data[17] = ((NU16)5);
	T2_.p->data[18] = ((NU16)4);
	T2_.p->data[19] = ((NU16)0);
	T2_.p->data[20] = ((NU16)3);
	T2_.p->data[21] = ((NU16)3);
	T2_.p->data[22] = ((NU16)7);
	T2_.p->data[23] = ((NU16)4);
	T2_.p->data[24] = ((NU16)3);
	T2_.p->data[25] = ((NU16)2);
	T2_.p->data[26] = ((NU16)6);
	T2_.p->data[27] = ((NU16)6);
	T2_.p->data[28] = ((NU16)7);
	T2_.p->data[29] = ((NU16)3);
	T2_.p->data[30] = ((NU16)4);
	T2_.p->data[31] = ((NU16)5);
	T2_.p->data[32] = ((NU16)1);
	T2_.p->data[33] = ((NU16)1);
	T2_.p->data[34] = ((NU16)0);
	T2_.p->data[35] = ((NU16)4);
	eqsink___platformZrender3d95interface_u446((&result.indices), T2_);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg, createSphereMeshData__platformZrender3d95interface_u557)(NF32 radius_p0, NI segments_p1, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ color_p2) {
	tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg result;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ T1_;
	tySequence__uFLLGQVsiasALrzzzvqnZw T2_;
	nimfr_("createSphereMeshData", "/workspaces/Storie/platform/render3d_interface.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg));
	nimln_(216);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 0; T1_.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(0, sizeof(NF32), NIM_ALIGNOF(NF32));
	eqsink___platformZrender3d95interface_u323((&result.vertices), T1_);
	nimln_(229);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 0; T2_.p = (tySequence__uFLLGQVsiasALrzzzvqnZw_Content*) newSeqPayload(0, sizeof(NU16), NIM_ALIGNOF(NU16));
	eqsink___platformZrender3d95interface_u446((&result.indices), T2_);
	{
		NI lat_1;
		NI res_1;
		lat_1 = (NI)0;
		nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NF theta_1;
				NF sinTheta_1;
				NF cosTheta_1;
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_30;
				if (!(res_1 <= segments_p1)) goto LA5;
				nimlf_(244, "/workspaces/Storie/platform/render3d_interface.nim");				lat_1 = ((NI) (res_1));
				nimln_(245);				theta_1 = ((NF)(((NF) (((NF32)(((NF32) (lat_1))) / (NF32)(((NF32) (segments_p1))))))) * (NF)(3.141592653589793));
				nimln_(246);				sinTheta_1 = sin(theta_1);
				nimln_(247);				cosTheta_1 = cos(theta_1);
				{
					NI lon_1;
					NI res_2;
					lon_1 = (NI)0;
					nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");					res_2 = ((NI)0);
					{
						nimln_(97);						while (1) {
							NF32 colontmpD_;
							NF32 colontmpD__2;
							NF32 colontmpD__3;
							NF phi_1;
							NF sinPhi_1;
							NF cosPhi_1;
							NF x_1;
							NF y_1;
							NF z_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_29;
							if (!(res_2 <= segments_p1)) goto LA8;
							colontmpD_ = (NF32)0;
							colontmpD__2 = (NF32)0;
							colontmpD__3 = (NF32)0;
							nimlf_(249, "/workspaces/Storie/platform/render3d_interface.nim");							lon_1 = ((NI) (res_2));
							nimln_(250);							phi_1 = ((NF)(((NF)(((NF) (((NF32)(((NF32) (lon_1))) / (NF32)(((NF32) (segments_p1))))))) * (NF)(2.0))) * (NF)(3.141592653589793));
							nimln_(251);							sinPhi_1 = sin(phi_1);
							nimln_(252);							cosPhi_1 = cos(phi_1);
							nimln_(254);							x_1 = ((NF)(cosPhi_1) * (NF)(sinTheta_1));
							nimln_(255);							y_1 = cosTheta_1;
							nimln_(256);							z_1 = ((NF)(sinPhi_1) * (NF)(sinTheta_1));
							nimln_(258);							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(x_1) * (NF)(((NF) (radius_p0)))))));
							nimln_(259);							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(y_1) * (NF)(((NF) (radius_p0)))))));
							nimln_(260);							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(z_1) * (NF)(((NF) (radius_p0)))))));
							nimln_(261);							colontmpD_ = color_p2.x;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD_);
							nimln_(262);							colontmpD__2 = color_p2.y;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD__2);
							nimln_(263);							colontmpD__3 = color_p2.z;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD__3);
							nimlf_(102, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");							if (nimAddInt(res_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_29)) { raiseOverflow(); goto BeforeRet_;
							};
							res_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_29);
						} LA8: ;
					}
				}
				if (nimAddInt(res_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_30)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_30);
			} LA5: ;
		}
	}
	{
		NI lat_2;
		NI i_1;
		lat_2 = (NI)0;
		nimln_(128);		i_1 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_36;
				if (!(i_1 < segments_p1)) goto LA11;
				nimlf_(266, "/workspaces/Storie/platform/render3d_interface.nim");				lat_2 = i_1;
				{
					NI lon_2;
					NI i_2;
					lon_2 = (NI)0;
					nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");					i_2 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NU16 first_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_31;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_32;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_33;
							NU16 second_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_34;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_35;
							if (!(i_2 < segments_p1)) goto LA14;
							nimlf_(267, "/workspaces/Storie/platform/render3d_interface.nim");							lon_2 = i_2;
							nimln_(268);							if (nimAddInt(segments_p1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_31)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimMulInt(lat_2, (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_31), &TM__0AG1Bhfktbzesi9cL0Iv9bng_32)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_32), lon_2, &TM__0AG1Bhfktbzesi9cL0Iv9bng_33)) { raiseOverflow(); goto BeforeRet_;
							};
							first_1 = ((NU16) ((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_33)));
							nimln_(269);							if (nimAddInt(segments_p1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_34)) { raiseOverflow(); goto BeforeRet_;
							};
							second_1 = (NU16)((NU16)(first_1) + (NU16)(((NU16) ((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_34)))));
							nimln_(271);							add__platformZrender3d95interface_u641((&result.indices), first_1);
							nimln_(272);							add__platformZrender3d95interface_u641((&result.indices), second_1);
							nimln_(273);							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(first_1) + (NU16)(((NU16)1))));
							nimln_(275);							add__platformZrender3d95interface_u641((&result.indices), second_1);
							nimln_(276);							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(second_1) + (NU16)(((NU16)1))));
							nimln_(277);							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(first_1) + (NU16)(((NU16)1))));
							nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");							if (nimAddInt(i_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_35)) { raiseOverflow(); goto BeforeRet_;
							};
							i_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_35);
						} LA14: ;
					}
				}
				if (nimAddInt(i_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_36)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_36);
			} LA11: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
