/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3-src/include -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-config-release -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-revision -I/workspaces/Storie/vendor/SDL_ttf-src/include   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_sdl/@mplatform@ssdl@ssdl_render3d.nim.c.o /workspaces/Storie/nimcache_wasm_sdl/@mplatform@ssdl@ssdl_render3d.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q;
typedef struct tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content tySequence__uFLLGQVsiasALrzzzvqnZw_Content;
typedef struct tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg;
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg {
	NU32 program;
	NU32 vertexShader;
	NU32 fragmentShader;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ {
	RootObj Sup;
};
typedef NF32 tyArray__EH3vwk2gvJbf6WGsCM9baJQ[16];
struct tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q {
	tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ Sup;
	tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader;
	tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* currentCamera;
	NF32 currentAspect;
	tyArray__EH3vwk2gvJbf6WGsCM9baJQ modelMatrix;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__CSBtGJGy4Lx1NJVMcpENaA[512];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  NI len; tySequence__uFLLGQVsiasALrzzzvqnZw_Content* p;
};
struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	tySequence__uFLLGQVsiasALrzzzvqnZw indices;
};
struct tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg {
	NU32 vao;
	NU32 vbo;
	NU32 ebo;
	NI vertexCount;
	NI indexCount;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content { NI cap; NU16 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZsdlZsdl95render3d_u295)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0);
N_NIMCALL(void, glEnable)(NU32 cap_p0);
N_NIMCALL(void, glDepthFunc)(NU32 fun_p0);
N_NIMCALL(void, glCullFace)(NU32 mode_p0);
N_NIMCALL(void, glFrontFace)(NU32 mode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZsdlZsdl95render3d_u110)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg** dest_p0, tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* src_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u80)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg*, createDefaultShader__platformZsdlZsdl95render3d_u123)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg*, createShader__platformZsdlZsdl95render3d_u70)(NimStringV2 vertexSrc_p0, NimStringV2 fragmentSrc_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__platformZsdlZsdl95render3d_u23)(NimStringV2 source_p0, NU32 shaderType_p1);
N_NIMCALL(NU32, glCreateShader)(NU32 shaderType_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_NIMCALL(void, glShaderSource)(NU32 shader_p0, NI32 count_p1, NCSTRING* str_p2, NI32* length_p3);
N_NIMCALL(void, glCompileShader)(NU32 shader_p0);
N_NIMCALL(void, glGetShaderiv)(NU32 shader_p0, NU32 pname_p1, NI32* params_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(void, glGetShaderInfoLog)(NU32 shader_p0, NI32 maxLength_p1, NI32* length_p2, NIM_CHAR* infoLog_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_NIMCALL(NU32, glCreateProgram)(void);
N_NIMCALL(void, glAttachShader)(NU32 program_p0, NU32 shader_p1);
N_NIMCALL(void, glLinkProgram)(NU32 program_p0);
N_NIMCALL(void, glGetProgramiv)(NU32 program_p0, NU32 pname_p1, NI32* params_p2);
N_NIMCALL(void, glGetProgramInfoLog)(NU32 program_p0, NI32 maxLength_p1, NI32* length_p2, NIM_CHAR* infoLog_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u101)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZsdlZsdl95render3d_u298)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, cleanup__platformZsdlZsdl95render3d_u138)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0);
N_NIMCALL(void, glDeleteShader)(NU32 shader_p0);
N_NIMCALL(void, glDeleteProgram)(NU32 program_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZsdlZsdl95render3d_u303)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3);
N_NIMCALL(void, glClearColor)(NF32 red_p0, NF32 green_p1, NF32 blue_p2, NF32 alpha_p3);
N_NIMCALL(void, glClear)(NU32 mask_p0);
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZsdlZsdl95render3d_u308)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZsdlZsdl95render3d_u310)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___platformZrender3d95interface_u230)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw** dest_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, use__platformZsdlZsdl95render3d_u125)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0);
N_NIMCALL(void, glUseProgram)(NU32 program_p0);
N_LIB_PRIVATE N_NIMCALL(void, setUniformMat4__platformZsdlZsdl95render3d_u127)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0, NimStringV2 name_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p2);
N_NIMCALL(NI32, glGetUniformLocation)(NU32 program_p0, NCSTRING name_p1);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_NIMCALL(void, glUniformMatrix4fv)(NI32 location_p0, NI32 count_p1, NU8 transpose_p2, NF32* value_p3);
N_LIB_PRIVATE N_NIMCALL(void, getViewMatrix__platformZrender3d95interface_u249)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(void, getProjectionMatrix__platformZrender3d95interface_u252)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p0, NF32 aspect_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZsdlZsdl95render3d_u314)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1);
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZsdlZsdl95render3d_u317)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg meshData_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg*, createMesh__platformZsdlZsdl95render3d_u140)(NF32* vertices_p0, NI vertices_p0Len_0, NU16* indices_p1, NI indices_p1Len_0);
N_NIMCALL(void, glGenVertexArrays)(NI32 n_p0, NU32* arrays_p1);
N_NIMCALL(void, glGenBuffers)(NI32 n_p0, NU32* buffers_p1);
N_NIMCALL(void, glBindVertexArray)(NU32 arr_p0);
N_NIMCALL(void, glBindBuffer)(NU32 target_p0, NU32 buffer_p1);
N_NIMCALL(void, glBufferData)(NU32 target_p0, NI32 size_p1, void* data_p2, NU32 usage_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_NIMCALL(void, glEnableVertexAttribArray)(NU32 index_p0);
N_NIMCALL(void, glVertexAttribPointer)(NU32 index_p0, NI32 size_p1, NU32 typ_p2, NU8 normalized_p3, NI32 stride_p4, void* pointer_p5);
N_LIB_PRIVATE N_NIMCALL(void, drawMeshGL__platformZsdlZsdl95render3d_u225)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* mesh_p0);
N_NIMCALL(void, glDrawElements)(NU32 mode_p0, NI32 count_p1, NU32 typ_p2, void* indices_p3);
N_LIB_PRIVATE N_NIMCALL(void, cleanup__platformZsdlZsdl95render3d_u227)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* mesh_p0);
N_NIMCALL(void, glDeleteVertexArrays)(NI32 n_p0, NU32* arrays_p1);
N_NIMCALL(void, glDeleteBuffers)(NI32 n_p0, NU32* buffers_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u184)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u161)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZsdlZsdl95render3d_u357)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4);
N_NIMCALL(void, glViewport)(NI32 x_p0, NI32 y_p1, NI32 width_p2, NI32 height_p3);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__platformZsdlZsdl95render3d_u403)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u234)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u197)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, identity__platformZrender3d95interface_u105)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_2 = { 27 | NIM_STRLIT_FLAG, "Shader compilation failed: " };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_3 = {27, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_2};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_4 = { 23 | NIM_STRLIT_FLAG, "Shader linking failed: " };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_5 = {23, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_4};
static const struct {
  NI cap; NIM_CHAR data[294+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_6 = { 294 | NIM_STRLIT_FLAG, "#ifdef GL_ES\012precision mediump float;\012#endif\012\012attribute vec3 aPosition;\012attribute vec3 aColor;\012\012uniform mat4 uModel;\012uniform mat4 uView;\012uniform mat4 uProjection;\012\012varying vec3 vColor;\012\012void main() {\012    vColor = aColor;\012    gl_Position = uProjection * uView * uModel * vec4(aPosition, 1.0);\012}\012" };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_7 = {294, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_6};
static const struct {
  NI cap; NIM_CHAR data[122+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_8 = { 122 | NIM_STRLIT_FLAG, "#ifdef GL_ES\012precision mediump float;\012#endif\012\012varying vec3 vColor;\012\012void main() {\012    gl_FragColor = vec4(vColor, 1.0);\012}\012" };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_9 = {122, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_8};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_11 = { 34 | NIM_STRLIT_FLAG, "SDL OpenGL 3D renderer initialized" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_12 = { 5 | NIM_STRLIT_FLAG, "uView" };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_13 = {5, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_12};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_14 = { 11 | NIM_STRLIT_FLAG, "uProjection" };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_15 = {11, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_14};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__w3RBNgLk85rG52tyD9cpOOA_16 = { 6 | NIM_STRLIT_FLAG, "uModel" };
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_17 = {6, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_16};
static const NimStringV2 TM__w3RBNgLk85rG52tyD9cpOOA_20 = {6, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_16};
N_LIB_PRIVATE TNimTypeV2 NTIv2__fQrcNqwLsMYFmZjr9ap4W6Q_;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__w3RBNgLk85rG52tyD9cpOOA_10 = {{34, (NimStrPayload*)&TM__w3RBNgLk85rG52tyD9cpOOA_11}}
;
extern TFrame* framePtr__system_u2675;
extern NIM_BOOL nimInErrorMode__system_u4277;
static NIM_CONST NU32 TM__w3RBNgLk85rG52tyD9cpOOA_21[3] = {3701606400, 3864839680, 182203904};
N_LIB_PRIVATE TNimTypeV2 NTIv2__fQrcNqwLsMYFmZjr9ap4W6Q_ = {.destructor = (void*)rttiDestroy__platformZsdlZsdl95render3d_u403, .size = sizeof(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q), .align = (NI16) NIM_ALIGNOF(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q), .depth = 2, .display = TM__w3RBNgLk85rG52tyD9cpOOA_21, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2675 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2675).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2675;
	framePtr__system_u2675 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4495();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2675 = (*framePtr__system_u2675).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(364, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");
	nimlf_(219, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u80)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZsdlZsdl95render3d_u110)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg** dest_p0, tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___platformZsdlZsdl95render3d_u80((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4277);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__platformZsdlZsdl95render3d_u23)(NimStringV2 source_p0, NU32 shaderType_p1) {
	NU32 result;
	NCSTRING csource_1;
	NI32 length_1;
	NI32 success_1;
NIM_BOOL* nimErr_;
	nimfr_("compileShader", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(69, "/workspaces/Storie/platform/sdl/sdl_render3d.nim");	result = glCreateShader(shaderType_p1);
	nimln_(70);	csource_1 = nimToCStringConv(source_p0);
	nimln_(71);	length_1 = ((NI32) (source_p0.len));
	nimln_(72);	glShaderSource(result, ((NI32)1), (&csource_1), (&length_1));
	nimln_(73);	glCompileShader(result);
	success_1 = (NI32)0;
	nimln_(76);	glGetShaderiv(result, ((NU32)35713), (&success_1));
	nimln_(77);	{
		NimStringV2 colontmpD_;
		NI32 logLength_1;
		tyArray__CSBtGJGy4Lx1NJVMcpENaA log_1;
		tyArray__Re75IspeoxXy2oCZHwcRrA T6_;
		if (!(success_1 == ((NI32)0))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		logLength_1 = (NI32)0;
		nimZeroMem((void*)log_1, sizeof(tyArray__CSBtGJGy4Lx1NJVMcpENaA));
		nimln_(80);		glGetShaderInfoLog(result, ((NI32)512), (&logLength_1), (&log_1[(((NI)0))- 0]));
		nimln_(81);		T6_[0] = TM__w3RBNgLk85rG52tyD9cpOOA_3;
		colontmpD_ = cstrToNimstr(((NCSTRING) ((&log_1[(((NI)0))- 0]))));
		T6_[1] = colontmpD_;
		echoBinSafe(T6_, 2);
		{
			LA5_:;
		}
		{
			nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg*, createShader__platformZsdlZsdl95render3d_u70)(NimStringV2 vertexSrc_p0, NimStringV2 fragmentSrc_p1) {
	tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* result;
	tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* T1_;
	NU32 T2_;
	NU32 T3_;
	NI32 success_1;
NIM_BOOL* nimErr_;
	nimfr_("createShader", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(84, "/workspaces/Storie/platform/sdl/sdl_render3d.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg*) nimNewObj(sizeof(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg), NIM_ALIGNOF(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg));
	result = T1_;
	nimln_(86);	T2_ = (NU32)0;
	T2_ = compileShader__platformZsdlZsdl95render3d_u23(vertexSrc_p0, ((NU32)35633));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*result).vertexShader = T2_;
	nimln_(87);	T3_ = (NU32)0;
	T3_ = compileShader__platformZsdlZsdl95render3d_u23(fragmentSrc_p1, ((NU32)35632));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*result).fragmentShader = T3_;
	nimln_(89);	(*result).program = glCreateProgram();
	nimln_(90);	glAttachShader((*result).program, (*result).vertexShader);
	nimln_(91);	glAttachShader((*result).program, (*result).fragmentShader);
	nimln_(92);	glLinkProgram((*result).program);
	success_1 = (NI32)0;
	nimln_(95);	glGetProgramiv((*result).program, ((NU32)35714), (&success_1));
	nimln_(96);	{
		NimStringV2 colontmpD_;
		NI32 logLength_1;
		tyArray__CSBtGJGy4Lx1NJVMcpENaA log_1;
		tyArray__Re75IspeoxXy2oCZHwcRrA T9_;
		if (!(success_1 == ((NI32)0))) goto LA6_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		logLength_1 = (NI32)0;
		nimZeroMem((void*)log_1, sizeof(tyArray__CSBtGJGy4Lx1NJVMcpENaA));
		nimln_(99);		glGetProgramInfoLog((*result).program, ((NI32)512), (&logLength_1), (&log_1[(((NI)0))- 0]));
		nimln_(100);		T9_[0] = TM__w3RBNgLk85rG52tyD9cpOOA_5;
		colontmpD_ = cstrToNimstr(((NCSTRING) ((&log_1[(((NI)0))- 0]))));
		T9_[1] = colontmpD_;
		echoBinSafe(T9_, 2);
		{
			LA8_:;
		}
		{
			nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA6_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg*, createDefaultShader__platformZsdlZsdl95render3d_u123)(void) {
	tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* result;
NIM_BOOL* nimErr_;
	nimfr_("createDefaultShader", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(103, "/workspaces/Storie/platform/sdl/sdl_render3d.nim");	result = createShader__platformZsdlZsdl95render3d_u70(TM__w3RBNgLk85rG52tyD9cpOOA_7, TM__w3RBNgLk85rG52tyD9cpOOA_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u101)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___platformZsdlZsdl95render3d_u80((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZsdlZsdl95render3d_u295)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0) {
	NIM_BOOL result;
	tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* T1_;
NIM_BOOL* nimErr_;
	nimfr_("init3D", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(173);	glEnable(((NU32)2929));
	nimln_(174);	glDepthFunc(((NU32)515));
	nimln_(175);	glEnable(((NU32)2884));
	nimln_(176);	glCullFace(((NU32)1029));
	nimln_(177);	glFrontFace(((NU32)2305));
	nimln_(84);	nimln_(180);	T1_ = NIM_NIL;
	T1_ = createDefaultShader__platformZsdlZsdl95render3d_u123();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___platformZsdlZsdl95render3d_u101(T1_); goto BeforeRet_;}
	nimln_(84);	eqsink___platformZsdlZsdl95render3d_u110(&(*r_p0).shader, T1_);
	nimln_(182);	echoBinSafe(TM__w3RBNgLk85rG52tyD9cpOOA_10, 1);
	nimln_(183);	nimln_(171);	nimln_(183);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, cleanup__platformZsdlZsdl95render3d_u138)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0) {
	nimfr_("cleanup", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(118);	glDeleteShader((*shader_p0).vertexShader);
	nimln_(119);	glDeleteShader((*shader_p0).fragmentShader);
	nimln_(120);	glDeleteProgram((*shader_p0).program);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZsdlZsdl95render3d_u298)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0) {
NIM_BOOL* nimErr_;
	nimfr_("shutdown3D", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimln_(186);	{
		if (!!(((*r_p0).shader == 0))) goto LA3_;
		nimln_(187);		cleanup__platformZsdlZsdl95render3d_u138((*r_p0).shader);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZsdlZsdl95render3d_u303)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3) {
	nimfr_("beginFrame3D", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(190);	glClearColor(clearR_p1, clearG_p2, clearB_p3, 1.0f);
	nimln_(191);	glClear(((NU32)16640));
	nimln_(195);	glEnable(((NU32)2929));
	nimln_(196);	glDepthFunc(((NU32)515));
	nimln_(197);	glEnable(((NU32)2884));
	nimln_(198);	glCullFace(((NU32)1029));
	nimln_(199);	glFrontFace(((NU32)2305));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZsdlZsdl95render3d_u308)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0) {
	nimfr_("endFrame3D", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, use__platformZsdlZsdl95render3d_u125)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0) {
	nimfr_("use", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(106);	glUseProgram((*shader_p0).program);
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
N_LIB_PRIVATE N_NIMCALL(void, setUniformMat4__platformZsdlZsdl95render3d_u127)(tyObject_Shader3DcolonObjectType___6GeY2mjw8qo85dkQX2InQg* shader_p0, NimStringV2 name_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p2) {
	NI32 loc_1;
	tyArray__EH3vwk2gvJbf6WGsCM9baJQ matCopy_1;
	nimfr_("setUniformMat4", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(109);	loc_1 = glGetUniformLocation((*shader_p0).program, nimToCStringConv(name_p1));
	nimZeroMem((void*)matCopy_1, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(110);	nimCopyMem((void*)matCopy_1, (NIM_CONST void*)mat_p2, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(111);	glUniformMatrix4fv(loc_1, ((NI32)1), ((NU8)0), (&matCopy_1[(((NI)0))- 0]));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZsdlZsdl95render3d_u310)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2) {
	tyArray__EH3vwk2gvJbf6WGsCM9baJQ T1_;
	tyArray__EH3vwk2gvJbf6WGsCM9baJQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("setCamera", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(156, "/workspaces/Storie/platform/render3d_interface.nim");	eqcopy___platformZrender3d95interface_u230(&(*r_p0).currentCamera, cam_p1);
	nimlf_(207, "/workspaces/Storie/platform/sdl/sdl_render3d.nim");	(*r_p0).currentAspect = aspect_p2;
	nimln_(209);	use__platformZsdlZsdl95render3d_u125((*r_p0).shader);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(210);	nimZeroMem((void*)T1_, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	getViewMatrix__platformZrender3d95interface_u249(cam_p1, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setUniformMat4__platformZsdlZsdl95render3d_u127((*r_p0).shader, TM__w3RBNgLk85rG52tyD9cpOOA_13, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(211);	nimZeroMem((void*)T2_, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	getProjectionMatrix__platformZrender3d95interface_u252(cam_p1, aspect_p2, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setUniformMat4__platformZsdlZsdl95render3d_u127((*r_p0).shader, TM__w3RBNgLk85rG52tyD9cpOOA_15, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZsdlZsdl95render3d_u314)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1) {
NIM_BOOL* nimErr_;
	nimfr_("setModelTransform", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimln_(214);	nimCopyMem((void*)(*r_p0).modelMatrix, (NIM_CONST void*)mat_p1, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	nimln_(215);	use__platformZsdlZsdl95render3d_u125((*r_p0).shader);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(216);	setUniformMat4__platformZsdlZsdl95render3d_u127((*r_p0).shader, TM__w3RBNgLk85rG52tyD9cpOOA_17, mat_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg*, createMesh__platformZsdlZsdl95render3d_u140)(NF32* vertices_p0, NI vertices_p0Len_0, NU16* indices_p1, NI indices_p1Len_0) {
	tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* result;
	tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* T1_;
	NI TM__w3RBNgLk85rG52tyD9cpOOA_18;
	NI32 T2_;
	NI TM__w3RBNgLk85rG52tyD9cpOOA_19;
	NI32 T3_;
	nimfr_("createMesh", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{	nimln_(127);	T1_ = NIM_NIL;
	T1_ = (tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg*) nimNewObj(sizeof(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg), NIM_ALIGNOF(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg));
	result = T1_;
	nimln_(128);	(*result).vertexCount = (NI)((vertices_p0Len_0) / (((NI)6)));
	nimln_(129);	(*result).indexCount = indices_p1Len_0;
	nimln_(131);	glGenVertexArrays(((NI32)1), (&(*result).vao));
	nimln_(132);	glGenBuffers(((NI32)1), (&(*result).vbo));
	nimln_(133);	glGenBuffers(((NI32)1), (&(*result).ebo));
	nimln_(135);	glBindVertexArray((*result).vao);
	nimln_(137);	glBindBuffer(((NU32)34962), (*result).vbo);
	nimln_(138);	if (nimMulInt(vertices_p0Len_0, ((NI)4), &TM__w3RBNgLk85rG52tyD9cpOOA_18)) { raiseOverflow(); goto BeforeRet_;
	};
	T2_ = (NI32)0;
	T2_ = ((NI32) ((NI)(TM__w3RBNgLk85rG52tyD9cpOOA_18)));
	if (((NI)0) < 0 || ((NI)0) >= vertices_p0Len_0){ raiseIndexError2(((NI)0),vertices_p0Len_0-1); goto BeforeRet_;
	}
	glBufferData(((NU32)34962), T2_, ((void*) ((&vertices_p0[((NI)0)]))), ((NU32)35044));
	nimln_(140);	glBindBuffer(((NU32)34963), (*result).ebo);
	nimln_(141);	if (nimMulInt(indices_p1Len_0, ((NI)2), &TM__w3RBNgLk85rG52tyD9cpOOA_19)) { raiseOverflow(); goto BeforeRet_;
	};
	T3_ = (NI32)0;
	T3_ = ((NI32) ((NI)(TM__w3RBNgLk85rG52tyD9cpOOA_19)));
	if (((NI)0) < 0 || ((NI)0) >= indices_p1Len_0){ raiseIndexError2(((NI)0),indices_p1Len_0-1); goto BeforeRet_;
	}
	glBufferData(((NU32)34963), T3_, ((void*) ((&indices_p1[((NI)0)]))), ((NU32)35044));
	nimln_(144);	glEnableVertexAttribArray(((NU32)0));
	nimln_(145);	glVertexAttribPointer(((NU32)0), ((NI32)3), ((NU32)5126), ((NU8)0), ((NI32)24), NIM_NIL);
	nimln_(148);	glEnableVertexAttribArray(((NU32)1));
	nimln_(149);	glVertexAttribPointer(((NU32)1), ((NI32)3), ((NU32)5126), ((NU8)0), ((NI32)24), ((void*) (((NI)12))));
	nimln_(151);	glBindVertexArray(((NU32)0));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, drawMeshGL__platformZsdlZsdl95render3d_u225)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* mesh_p0) {
	nimfr_("drawMeshGL", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(154);	glBindVertexArray((*mesh_p0).vao);
	nimln_(155);	glDrawElements(((NU32)4), ((NI32) ((*mesh_p0).indexCount)), ((NU32)5123), NIM_NIL);
	nimln_(156);	glBindVertexArray(((NU32)0));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, cleanup__platformZsdlZsdl95render3d_u227)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* mesh_p0) {
	nimfr_("cleanup", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(159);	glDeleteVertexArrays(((NI32)1), (&(*mesh_p0).vao));
	nimln_(160);	glDeleteBuffers(((NI32)1), (&(*mesh_p0).vbo));
	nimln_(161);	glDeleteBuffers(((NI32)1), (&(*mesh_p0).ebo));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u161)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u184)(tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___platformZsdlZsdl95render3d_u161((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZsdlZsdl95render3d_u317)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg meshData_p1) {
	tyObject_Mesh3DcolonObjectType___Lo12I3GlH8J64WEpcTl8Tg* mesh_1;
NIM_BOOL* nimErr_;
	nimfr_("drawMesh", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	mesh_1 = NIM_NIL;
	nimln_(220);	mesh_1 = createMesh__platformZsdlZsdl95render3d_u140(((meshData_p1.vertices).p) ? (meshData_p1.vertices.p->data) : NIM_NIL, meshData_p1.vertices.len, ((meshData_p1.indices).p) ? (meshData_p1.indices.p->data) : NIM_NIL, meshData_p1.indices.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(222);	use__platformZsdlZsdl95render3d_u125((*r_p0).shader);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(223);	setUniformMat4__platformZsdlZsdl95render3d_u127((*r_p0).shader, TM__w3RBNgLk85rG52tyD9cpOOA_20, (*r_p0).modelMatrix);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(225);	drawMeshGL__platformZsdlZsdl95render3d_u225(mesh_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(226);	cleanup__platformZsdlZsdl95render3d_u227(mesh_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(127);	eqdestroy___platformZsdlZsdl95render3d_u184(mesh_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZsdlZsdl95render3d_u357)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4) {
	nimfr_("setViewport", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
	nimln_(229);	glViewport(((NI32) (x_p1)), ((NI32) (y_p2)), ((NI32) (width_p3)), ((NI32) (height_p4)));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	nimlf_(518, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimlf_(521, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZsdlZsdl95render3d_u285)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q** dest_p0, tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* src_p1) {
	tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u234)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).currentCamera);
		if (!T3_) goto LA4_;
		eqdestroy___platformZrender3d95interface_u197((&(*(*dest_p0).currentCamera)));
		nimRawDispose((*dest_p0).currentCamera, ((NI)4));
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).shader);
		if (!T8_) goto LA9_;
		eqdestroy___platformZsdlZsdl95render3d_u80((&(*(*dest_p0).shader)));
		nimRawDispose((*dest_p0).shader, ((NI)4));
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__platformZsdlZsdl95render3d_u403)(void* dest_p0) {
	eqdestroy___platformZsdlZsdl95render3d_u234(((tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q*, newSdlRenderer3D__platformZsdlZsdl95render3d_u229)(void) {
	tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* result;
	tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newSdlRenderer3D", "/workspaces/Storie/platform/sdl/sdl_render3d.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(168, "/workspaces/Storie/platform/sdl/sdl_render3d.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q*) nimNewObj(sizeof(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q), NIM_ALIGNOF(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q));
	(*T1_).Sup.Sup.m_type = (&NTIv2__fQrcNqwLsMYFmZjr9ap4W6Q_);
	result = T1_;
	nimln_(169);	identity__platformZrender3d95interface_u105((*result).modelMatrix);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZsdlZsdl95render3d_u274)(tyObject_SdlRenderer3DcolonObjectType___fQrcNqwLsMYFmZjr9ap4W6Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
