/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3-src/include -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-config-release -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-revision -I/workspaces/Storie/vendor/SDL_ttf-src/include   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_sdl/@msrc@snimini@sbackends@snim_backend.nim.c.o /workspaces/Storie/nimcache_wasm_sdl/@msrc@snimini@sbackends@snim_backend.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateInt__srcZniminiZbackendsZnim95backend_u61)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateFloat__srcZniminiZbackendsZnim95backend_u65)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NF value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4771)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateString__srcZniminiZbackendsZnim95backend_u72)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBool__srcZniminiZbackendsZnim95backend_u77)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NIM_BOOL value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIdent__srcZniminiZbackendsZnim95backend_u81)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2642)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBinOp__srcZniminiZbackendsZnim95backend_u85)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 left_p1, NimStringV2 op_p2, NimStringV2 right_p3);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateUnaryOp__srcZniminiZbackendsZnim95backend_u92)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 op_p1, NimStringV2 operand_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateCall__srcZniminiZbackendsZnim95backend_u97)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 funcName_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ args_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateArray__srcZniminiZbackendsZnim95backend_u102)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ elements_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIndex__srcZniminiZbackendsZnim95backend_u106)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 target_p1, NimStringV2 index_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateVarDecl__srcZniminiZbackendsZnim95backend_u111)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateLetDecl__srcZniminiZbackendsZnim95backend_u117)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateAssignment__srcZniminiZbackendsZnim95backend_u123)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 target_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIfStmt__srcZniminiZbackendsZnim95backend_u129)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElifStmt__srcZniminiZbackendsZnim95backend_u134)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElseStmt__srcZniminiZbackendsZnim95backend_u139)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 indent_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateForLoop__srcZniminiZbackendsZnim95backend_u143)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 varName_p1, NimStringV2 iterable_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateWhileLoop__srcZniminiZbackendsZnim95backend_u149)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProcDecl__srcZniminiZbackendsZnim95backend_u154)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, tySequence__4eQHGndY6XBYpFOH09apV8Q params_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2645)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3717)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateReturn__srcZniminiZbackendsZnim95backend_u179)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 value_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateImport__srcZniminiZbackendsZnim95backend_u184)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 module_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateComment__srcZniminiZbackendsZnim95backend_u188)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 text_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramHeader__srcZniminiZbackendsZnim95backend_u193)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramFooter__srcZniminiZbackendsZnim95backend_u196)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_2 = { 1 | NIM_STRLIT_FLAG, "\\" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_3 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_4 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_5 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_6 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_7 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_8 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_9 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_10 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_11 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_10};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_12 = { 2 | NIM_STRLIT_FLAG, "\\n" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_13 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_14 = { 1 | NIM_STRLIT_FLAG, "\015" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_15 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_14};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_16 = { 2 | NIM_STRLIT_FLAG, "\\r" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_17 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_16};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_18 = { 1 | NIM_STRLIT_FLAG, "\011" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_19 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_18};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_20 = { 2 | NIM_STRLIT_FLAG, "\\t" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_21 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_20};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_22 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_6};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_24 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_25 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_26 = {4, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_25};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_27 = { 5 | NIM_STRLIT_FLAG, "false" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_28 = {5, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_27};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_29 = { 3 | NIM_STRLIT_FLAG, "and" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_30 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_29};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_31 = { 2 | NIM_STRLIT_FLAG, "or" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_32 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_31};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_33 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_29};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_34 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_31};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_35 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_36 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_35};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_37 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_38 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_37};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_39 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_37};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_40 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_41 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_40};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_42 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_43 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_42};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_44 = { 3 | NIM_STRLIT_FLAG, "not" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_45 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_44};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_46 = { 2 | NIM_STRLIT_FLAG, "-(" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_47 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_46};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_48 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_40};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_49 = { 5 | NIM_STRLIT_FLAG, "not (" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_50 = {5, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_49};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_51 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_40};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_52 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_35};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_53 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_40};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_54 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_35};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_55 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_56 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_55};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_57 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_40};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_58 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_59 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_58};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_60 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_55};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_61 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_62 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_61};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_63 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_64 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_63};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_65 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_61};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_66 = { 4 | NIM_STRLIT_FLAG, "var " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_67 = {4, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_66};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_68 = { 3 | NIM_STRLIT_FLAG, " = " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_69 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_68};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_70 = { 4 | NIM_STRLIT_FLAG, "let " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_71 = {4, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_70};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_72 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_68};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_73 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_68};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_74 = { 3 | NIM_STRLIT_FLAG, "if " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_75 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_74};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_76 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_77 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_76};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_78 = { 5 | NIM_STRLIT_FLAG, "elif " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_79 = {5, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_78};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_80 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_76};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_81 = { 5 | NIM_STRLIT_FLAG, "else:" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_82 = {5, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_81};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_83 = { 4 | NIM_STRLIT_FLAG, "for " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_84 = {4, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_83};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_85 = { 4 | NIM_STRLIT_FLAG, " in " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_86 = {4, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_85};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_87 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_76};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_88 = { 6 | NIM_STRLIT_FLAG, "while " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_89 = {6, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_88};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_90 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_76};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_91 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_92 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_91};
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_93 = { 149 | NIM_STRLIT_FLAG, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_94 = {149, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_93};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_95 = { 2 | NIM_STRLIT_FLAG, "; " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_96 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_95};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_97 = { 5 | NIM_STRLIT_FLAG, "proc " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_98 = {5, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_97};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_99 = {1, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_35};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_100 = { 3 | NIM_STRLIT_FLAG, ") =" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_101 = {3, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_100};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_102 = { 7 | NIM_STRLIT_FLAG, "return " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_103 = {7, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_102};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_104 = { 7 | NIM_STRLIT_FLAG, "import " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_105 = {7, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_104};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_106 = { 2 | NIM_STRLIT_FLAG, "# " };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_107 = {2, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_106};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__dCuhjUDGqzYoZDapbzD1Dw_108 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_109 = {0, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_108};
static const NimStringV2 TM__dCuhjUDGqzYoZDapbzD1Dw_110 = {0, (NimStrPayload*)&TM__dCuhjUDGqzYoZDapbzD1Dw_108};
extern NIM_BOOL nimInErrorMode__system_u4277;
extern TFrame* framePtr__system_u2675;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4277);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2675 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2675).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2675;
	framePtr__system_u2675 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4495();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2675 = (*framePtr__system_u2675).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateInt__srcZniminiZbackendsZnim95backend_u61)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NI value_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("generateInt", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(24, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	result = dollar___systemZdollars_u14(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateFloat__srcZniminiZbackendsZnim95backend_u65)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NF value_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("generateFloat", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(27);	result = dollar___system_u4771(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__dCuhjUDGqzYoZDapbzD1Dw_23;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)2147483647)){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__dCuhjUDGqzYoZDapbzD1Dw_23)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__dCuhjUDGqzYoZDapbzD1Dw_23);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateString__srcZniminiZbackendsZnim95backend_u72)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 value_p1) {
	NimStringV2 result;
	NimStringV2 escaped_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("generateString", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	escaped_1.len = 0; escaped_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	nimln_(31);	nimln_(36);	nimln_(35);	nimln_(34);	nimln_(33);	nimln_(32);	colontmpD_ = nsuReplaceStr(value_p1, TM__dCuhjUDGqzYoZDapbzD1Dw_3, TM__dCuhjUDGqzYoZDapbzD1Dw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(33);	colontmpD__2 = nsuReplaceStr(colontmpD_, TM__dCuhjUDGqzYoZDapbzD1Dw_7, TM__dCuhjUDGqzYoZDapbzD1Dw_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(34);	colontmpD__3 = nsuReplaceStr(colontmpD__2, TM__dCuhjUDGqzYoZDapbzD1Dw_11, TM__dCuhjUDGqzYoZDapbzD1Dw_13);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(35);	colontmpD__4 = nsuReplaceStr(colontmpD__3, TM__dCuhjUDGqzYoZDapbzD1Dw_15, TM__dCuhjUDGqzYoZDapbzD1Dw_17);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(36);	escaped_1 = nsuReplaceStr(colontmpD__4, TM__dCuhjUDGqzYoZDapbzD1Dw_19, TM__dCuhjUDGqzYoZDapbzD1Dw_21);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(37);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(escaped_1.len + 2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_22);
appendString((&T1_), escaped_1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_24);
	result = T1_;
	nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__4.p);
}
	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	if (escaped_1.p && !(escaped_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(escaped_1.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBool__srcZniminiZbackendsZnim95backend_u77)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NIM_BOOL value_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateBool", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	T1_.len = 0; T1_.p = NIM_NIL;
	nimlf_(40, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	{
		if (!value_p1) goto LA4_;
		result = TM__dCuhjUDGqzYoZDapbzD1Dw_26;
	}
	goto LA2_;
LA4_: ;
	{
		result = TM__dCuhjUDGqzYoZDapbzD1Dw_28;
	}
LA2_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIdent__srcZniminiZbackendsZnim95backend_u81)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1) {
	NimStringV2 result;
	nimfr_("generateIdent", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2642((&result), name_p1);
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/strmantle.nim");
{	nimlf_(33, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBinOp__srcZniminiZbackendsZnim95backend_u85)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 left_p1, NimStringV2 op_p2, NimStringV2 right_p3) {
	NimStringV2 result;
	NimStringV2 nimOp_1;
	NimStringV2 T1_;
	NimStringV2 T9_;
	nimfr_("generateBinOp", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimOp_1.len = 0; nimOp_1.p = NIM_NIL;
	nimlf_(51, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	if (eqStrings(op_p2, TM__dCuhjUDGqzYoZDapbzD1Dw_30)) goto LA2_;
	if (eqStrings(op_p2, TM__dCuhjUDGqzYoZDapbzD1Dw_32)) goto LA3_;
	goto LA4_;
	LA2_: ;
	{
		nimln_(52);		nimOp_1 = TM__dCuhjUDGqzYoZDapbzD1Dw_33;
	}
	goto LA5_;
	LA3_: ;
	{
		nimln_(51);		nimln_(53);		nimOp_1 = TM__dCuhjUDGqzYoZDapbzD1Dw_34;
	}
	goto LA5_;
	LA4_: ;
	{
		nimln_(51);		nimln_(54);		nimOp_1 = op_p2;
	}
LA5_: ;
	nimln_(56);	T9_.len = 0; T9_.p = NIM_NIL;
	T9_ = rawNewString(left_p1.len + nimOp_1.len + right_p3.len + 4);
appendString((&T9_), TM__dCuhjUDGqzYoZDapbzD1Dw_36);
appendString((&T9_), left_p1);
appendString((&T9_), TM__dCuhjUDGqzYoZDapbzD1Dw_38);
appendString((&T9_), nimOp_1);
appendString((&T9_), TM__dCuhjUDGqzYoZDapbzD1Dw_39);
appendString((&T9_), right_p3);
appendString((&T9_), TM__dCuhjUDGqzYoZDapbzD1Dw_41);
	result = T9_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateUnaryOp__srcZniminiZbackendsZnim95backend_u92)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 op_p1, NimStringV2 operand_p2) {
	NimStringV2 result;
	nimfr_("generateUnaryOp", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(59);	if (eqStrings(op_p1, TM__dCuhjUDGqzYoZDapbzD1Dw_43)) goto LA1_;
	if (eqStrings(op_p1, TM__dCuhjUDGqzYoZDapbzD1Dw_45)) goto LA2_;
	goto LA3_;
	LA1_: ;
	{
		NimStringV2 T6_;
		nimln_(61);		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = rawNewString(operand_p2.len + 3);
appendString((&T6_), TM__dCuhjUDGqzYoZDapbzD1Dw_47);
appendString((&T6_), operand_p2);
appendString((&T6_), TM__dCuhjUDGqzYoZDapbzD1Dw_48);
		result = T6_;
	}
	goto LA4_;
	LA2_: ;
	{
		NimStringV2 T8_;
		nimln_(63);		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(operand_p2.len + 6);
appendString((&T8_), TM__dCuhjUDGqzYoZDapbzD1Dw_50);
appendString((&T8_), operand_p2);
appendString((&T8_), TM__dCuhjUDGqzYoZDapbzD1Dw_51);
		result = T8_;
	}
	goto LA4_;
	LA3_: ;
	{
		NimStringV2 T10_;
		nimln_(65);		T10_.len = 0; T10_.p = NIM_NIL;
		T10_ = rawNewString(op_p1.len + operand_p2.len + 2);
appendString((&T10_), op_p1);
appendString((&T10_), TM__dCuhjUDGqzYoZDapbzD1Dw_52);
appendString((&T10_), operand_p2);
appendString((&T10_), TM__dCuhjUDGqzYoZDapbzD1Dw_53);
		result = T10_;
	}
LA4_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateCall__srcZniminiZbackendsZnim95backend_u97)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 funcName_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ args_p2) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("generateCall", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(68);	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuJoinSep(((args_p2).p) ? (args_p2.p->data) : NIM_NIL, args_p2.len, TM__dCuhjUDGqzYoZDapbzD1Dw_56);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(funcName_p1.len + colontmpD_.len + 2);
appendString((&T1_), funcName_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_54);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_57);
	result = T1_;
	nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateArray__srcZniminiZbackendsZnim95backend_u102)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ elements_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("generateArray", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(71, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuJoinSep(((elements_p1).p) ? (elements_p1.p->data) : NIM_NIL, elements_p1.len, TM__dCuhjUDGqzYoZDapbzD1Dw_60);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 3);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_59);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_62);
	result = T1_;
	nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIndex__srcZniminiZbackendsZnim95backend_u106)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 target_p1, NimStringV2 index_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateIndex", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimlf_(74, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(target_p1.len + index_p2.len + 2);
appendString((&T1_), target_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_64);
appendString((&T1_), index_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_65);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateVarDecl__srcZniminiZbackendsZnim95backend_u111)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateVarDecl", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(81);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + name_p1.len + value_p2.len + 7);
appendString((&T1_), indent_p3);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_67);
appendString((&T1_), name_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_69);
appendString((&T1_), value_p2);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateLetDecl__srcZniminiZbackendsZnim95backend_u117)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateLetDecl", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(84);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + name_p1.len + value_p2.len + 7);
appendString((&T1_), indent_p3);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_71);
appendString((&T1_), name_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_72);
appendString((&T1_), value_p2);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateAssignment__srcZniminiZbackendsZnim95backend_u123)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 target_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateAssignment", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(87);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + target_p1.len + value_p2.len + 3);
appendString((&T1_), indent_p3);
appendString((&T1_), target_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_73);
appendString((&T1_), value_p2);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIfStmt__srcZniminiZbackendsZnim95backend_u129)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateIfStmt", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(94);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 4);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_75);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_77);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElifStmt__srcZniminiZbackendsZnim95backend_u134)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateElifStmt", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(97);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 6);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_79);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_80);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElseStmt__srcZniminiZbackendsZnim95backend_u139)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 indent_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateElseStmt", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(100);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p1.len + 5);
appendString((&T1_), indent_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_82);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateForLoop__srcZniminiZbackendsZnim95backend_u143)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 varName_p1, NimStringV2 iterable_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateForLoop", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(103);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + varName_p1.len + iterable_p2.len + 9);
appendString((&T1_), indent_p3);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_84);
appendString((&T1_), varName_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_86);
appendString((&T1_), iterable_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_87);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateWhileLoop__srcZniminiZbackendsZnim95backend_u149)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateWhileLoop", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(106);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 7);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_89);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_90);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProcDecl__srcZniminiZbackendsZnim95backend_u154)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 name_p1, tySequence__4eQHGndY6XBYpFOH09apV8Q params_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ paramStrs_1;
	NimStringV2 paramList_1;
	NimStringV2 T16_;
NIM_BOOL* nimErr_;
	nimfr_("generateProcDecl", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	paramStrs_1.len = 0; paramStrs_1.p = NIM_NIL;
	paramList_1.len = 0; paramList_1.p = NIM_NIL;
	nimln_(113);	paramStrs_1.len = 0; paramStrs_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2* pname_1;
		NimStringV2* ptype_1;
		NI i_1;
		NI L_1;
		NI T2_;
		pname_1 = (NimStringV2*)0;
		ptype_1 = (NimStringV2*)0;
		nimlf_(249, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = params_p2.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(114, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");				if (i_1 < 0 || i_1 >= params_p2.len){ raiseIndexError2(i_1,params_p2.len-1); goto BeforeRet_;
				}
				pname_1 = (&params_p2.p->data[i_1].Field0);
				if (i_1 < 0 || i_1 >= params_p2.len){ raiseIndexError2(i_1,params_p2.len-1); goto BeforeRet_;
				}
				ptype_1 = (&params_p2.p->data[i_1].Field1);
				nimln_(115);				{
					NimStringV2 T9_;
					if (!(((NI)0) < (*ptype_1).len)) goto LA7_;
					nimln_(116);					T9_.len = 0; T9_.p = NIM_NIL;
					T9_ = rawNewString((*pname_1).len + (*ptype_1).len + 2);
appendString((&T9_), (*pname_1));
appendString((&T9_), TM__dCuhjUDGqzYoZDapbzD1Dw_92);
appendString((&T9_), (*ptype_1));
					add__stdZenumutils_u70((&paramStrs_1), T9_);
				}
				goto LA5_;
LA7_: ;
				{
					NimStringV2 colontmpD_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimln_(119);					nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					colontmpD_ = eqdup___system_u2645((*pname_1));
					nimlf_(119, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");					add__stdZenumutils_u70((&paramStrs_1), colontmpD_);
				}
LA5_: ;
				nimlf_(13, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T13_;
					T13_ = params_p2.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u234(TM__dCuhjUDGqzYoZDapbzD1Dw_94);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA14_: ;
			} LA4: ;
		}
	}
	nimlf_(121, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	paramList_1 = nsuJoinSep(((paramStrs_1).p) ? (paramStrs_1.p->data) : NIM_NIL, paramStrs_1.len, TM__dCuhjUDGqzYoZDapbzD1Dw_96);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(122);	T16_.len = 0; T16_.p = NIM_NIL;
	T16_ = rawNewString(indent_p3.len + name_p1.len + paramList_1.len + 9);
appendString((&T16_), indent_p3);
appendString((&T16_), TM__dCuhjUDGqzYoZDapbzD1Dw_98);
appendString((&T16_), name_p1);
appendString((&T16_), TM__dCuhjUDGqzYoZDapbzD1Dw_99);
appendString((&T16_), paramList_1);
appendString((&T16_), TM__dCuhjUDGqzYoZDapbzD1Dw_101);
	result = T16_;
	nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	if (paramList_1.p && !(paramList_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(paramList_1.p);
}
	nimln_(2128);	eqdestroy___system_u3717(paramStrs_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateReturn__srcZniminiZbackendsZnim95backend_u179)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 value_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateReturn", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimlf_(125, "/workspaces/Storie/src/nimini/backends/nim_backend.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + value_p1.len + 7);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_103);
appendString((&T1_), value_p1);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateImport__srcZniminiZbackendsZnim95backend_u184)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 module_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateImport", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(132);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(module_p1.len + 7);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_105);
appendString((&T1_), module_p1);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateComment__srcZniminiZbackendsZnim95backend_u188)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0, NimStringV2 text_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	nimfr_("generateComment", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(135);	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + text_p1.len + 2);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__dCuhjUDGqzYoZDapbzD1Dw_107);
appendString((&T1_), text_p1);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramHeader__srcZniminiZbackendsZnim95backend_u193)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0) {
	NimStringV2 result;
	nimfr_("generateProgramHeader", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(142);	result = TM__dCuhjUDGqzYoZDapbzD1Dw_109;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramFooter__srcZniminiZbackendsZnim95backend_u196)(tyObject_NimBackendcolonObjectType___3ozHq9cNgsv8mtpx5Ksi3lw* backend_p0) {
	NimStringV2 result;
	nimfr_("generateProgramFooter", "/workspaces/Storie/src/nimini/backends/nim_backend.nim");
	nimln_(145);	result = TM__dCuhjUDGqzYoZDapbzD1Dw_110;
	popFrame();
	return result;
}
