/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -I/workspaces/Storie/vendor/SDL3-src/include -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-config-release -I/workspaces/Storie/build-wasm/vendor/SDL3-src/include-revision -I/workspaces/Storie/vendor/SDL_ttf-src/include   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_sdl/@ptimes.nim.c.o /workspaces/Storie/nimcache_wasm_sdl/@ptimes.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <time.h>
#include <string.h>
#include <sys/types.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw;
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* utcInstance__pureZtimes_u2031;
N_LIB_PRIVATE tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* localInstance__pureZtimes_u2032;
extern NIM_BOOL nimInErrorMode__system_u4277;
extern TFrame* framePtr__system_u2675;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4277);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2675 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2675).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2675;
	framePtr__system_u2675 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4495();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2675 = (*framePtr__system_u2675).prev;
}
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");
	nimlf_(1286, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, cpuTime__pureZtimes_u5308)(void) {
	NF result;
	struct timespec ts_1;
	int T1_;
	NF T2_;
	NF T3_;
	nimfr_("cpuTime", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/times.nim");
	nimlf_(2850, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/times.nim");	nimZeroMem((void*)(&ts_1), sizeof(struct timespec));
	nimln_(2851);	T1_ = (int)0;
	T1_ = clock_gettime(((clockid_t) (CLOCK_THREAD_CPUTIME_ID)), (&ts_1));
	(void)(T1_);
	nimln_(2852);	T2_ = (NF)0;
	T2_ = toFloat__system_u1691(((NI) (ts_1.tv_sec)));
	nimln_(2853);	T3_ = (NF)0;
	T3_ = toFloat__system_u1691(ts_1.tv_nsec);
	result = ((NF)(T2_) + (NF)(((NF)(T3_) / (NF)(1000000000.0))));
	popFrame();
	return result;
}
