/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -Ivendor/raylib-src/src -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/Storie -o /workspaces/Storie/nimcache_wasm_raylib/@mplatform@srender3d_interface.nim.c.o /workspaces/Storie/nimcache_wasm_raylib/@mplatform@srender3d_interface.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw;
typedef struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content tySequence__uFLLGQVsiasALrzzzvqnZw_Content;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NF32 tyArray__EH3vwk2gvJbf6WGsCM9baJQ[16];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  NI len; tySequence__uFLLGQVsiasALrzzzvqnZw_Content* p;
};
struct tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	tySequence__uFLLGQVsiasALrzzzvqnZw indices;
};
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ {
	NF32 x;
	NF32 y;
	NF32 z;
};
struct tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ position;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ up;
	NF32 fov;
	NF32 near;
	NF32 far;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__uFLLGQVsiasALrzzzvqnZw_Content { NI cap; NU16 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZrender3d95interface_u261)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u7668)(NimStringV2 errormsg_p0, NI errorcode_p1);
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZrender3d95interface_u266)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZrender3d95interface_u269)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3);
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZrender3d95interface_u275)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZrender3d95interface_u278)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2);
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZrender3d95interface_u283)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1);
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZrender3d95interface_u287)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg mesh_p1);
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZrender3d95interface_u291)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u197)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, eqdup___platformZrender3d95interface_u34)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, vec3__platformZrender3d95interface_u20)(NF32 x_p0, NF32 y_p1, NF32 z_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, pluseq___platformZrender3d95interface_u185)(NF32* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, identity__platformZrender3d95interface_u105)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u437)(tySequence__uFLLGQVsiasALrzzzvqnZw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u314)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u323)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest_p0, tySequence__4Xyxy0Om14N6K1l5e9bUPSQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u446)(tySequence__uFLLGQVsiasALrzzzvqnZw* dest_p0, tySequence__uFLLGQVsiasALrzzzvqnZw src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZrender3d95interface_u589)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__platformZrender3d95interface_u641)(tySequence__uFLLGQVsiasALrzzzvqnZw* x_p0, NU16 y_p1);
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_2 = { 38 | NIM_STRLIT_FLAG, "Renderer3D.init3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_3 = {38, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_2};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_4 = { 42 | NIM_STRLIT_FLAG, "Renderer3D.shutdown3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_5 = {42, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_4};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_6 = { 44 | NIM_STRLIT_FLAG, "Renderer3D.beginFrame3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_7 = {44, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_6};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_8 = { 42 | NIM_STRLIT_FLAG, "Renderer3D.endFrame3D() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_9 = {42, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_8};
static const struct {
  NI cap; NIM_CHAR data[41+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_10 = { 41 | NIM_STRLIT_FLAG, "Renderer3D.setCamera() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_11 = {41, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_10};
static const struct {
  NI cap; NIM_CHAR data[49+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_12 = { 49 | NIM_STRLIT_FLAG, "Renderer3D.setModelTransform() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_13 = {49, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_12};
static const struct {
  NI cap; NIM_CHAR data[40+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_14 = { 40 | NIM_STRLIT_FLAG, "Renderer3D.drawMesh() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_15 = {40, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_14};
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__0AG1Bhfktbzesi9cL0Iv9bng_16 = { 43 | NIM_STRLIT_FLAG, "Renderer3D.setViewport() must be overridden" };
static const NimStringV2 TM__0AG1Bhfktbzesi9cL0Iv9bng_17 = {43, (NimStrPayload*)&TM__0AG1Bhfktbzesi9cL0Iv9bng_16};
extern NIM_BOOL nimInErrorMode__system_u4234;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, init3D__platformZrender3d95interface_u261)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_3, ((NI)1));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown3D__platformZrender3d95interface_u266)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_5, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, beginFrame3D__platformZrender3d95interface_u269)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NF32 clearR_p1, NF32 clearG_p2, NF32 clearB_p3) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_7, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, endFrame3D__platformZrender3d95interface_u275)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_9, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, setCamera__platformZrender3d95interface_u278)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* cam_p1, NF32 aspect_p2) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_11, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, setModelTransform__platformZrender3d95interface_u283)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ mat_p1) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_13, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, drawMesh__platformZrender3d95interface_u287)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg mesh_p1) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_15, ((NI)1));
}
N_LIB_PRIVATE N_NIMCALL(void, setViewport__platformZrender3d95interface_u291)(tyObject_Renderer3DcolonObjectType___OuZcxs1GnYU9aNWMd48G9cCQ* r_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4) {
	quit__system_u7668(TM__0AG1Bhfktbzesi9cL0Iv9bng_17, ((NI)1));
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, identity__platformZrender3d95interface_u105)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	Result[(((NI)0))- 0] = 1.0f;
	Result[(((NI)5))- 0] = 1.0f;
	Result[(((NI)10))- 0] = 1.0f;
	Result[(((NI)15))- 0] = 1.0f;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u197)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___platformZrender3d95interface_u236)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw** dest_p0, tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___platformZrender3d95interface_u197((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, eqdup___platformZrender3d95interface_u34)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ src_p0) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	result.x = src_p0.x;
	result.y = src_p0.y;
	result.z = src_p0.z;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ, vec3__platformZrender3d95interface_u20)(NF32 x_p0, NF32 y_p1, NF32 z_p2) {
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ result;
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	colontmpD_ = x_p0;
	result.x = colontmpD_;
	colontmpD__2 = y_p1;
	result.y = colontmpD__2;
	colontmpD__3 = z_p2;
	result.z = colontmpD__3;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw*, newCamera3D__platformZrender3d95interface_u189)(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ position_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ target_p1, NF32 fov_p2) {
	tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* result;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD_;
	tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ colontmpD__2;
	NF32 colontmpD__3;
	tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ));
	colontmpD__3 = (NF32)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw*) nimNewObjUninit(sizeof(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw), NIM_ALIGNOF(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw));
	colontmpD_ = eqdup___platformZrender3d95interface_u34(position_p0);
	(*T1_).position = colontmpD_;
	colontmpD__2 = eqdup___platformZrender3d95interface_u34(target_p1);
	(*T1_).target = colontmpD__2;
	(*T1_).up = vec3__platformZrender3d95interface_u20(0.0f, 1.0f, 0.0f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__3 = fov_p2;
	(*T1_).fov = colontmpD__3;
	(*T1_).near = 0.1f;
	(*T1_).far = 1000.0f;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___platformZrender3d95interface_u227)(tyObject_Camera3DcolonObjectType___Y29cWHTcfVPZdwsrDPvb09cw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___platformZrender3d95interface_u197((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
static N_INLINE(void, pluseq___platformZrender3d95interface_u185)(NF32* x_p0, NF32 y_p1) {
	(*x_p0) = ((NF32)((*x_p0)) + (NF32)(y_p1));
}
N_LIB_PRIVATE N_NIMCALL(void, star___platformZrender3d95interface_u166)(tyArray__EH3vwk2gvJbf6WGsCM9baJQ a_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ b_p1, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
{	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		res_1 = ((NI)0);
		{
			while (1) {
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_28;
				if (!(res_1 <= ((NI)3))) goto LA3;
				i_1 = ((NI) (res_1));
				{
					NI j_1;
					NI res_2;
					j_1 = (NI)0;
					res_2 = ((NI)0);
					{
						while (1) {
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_18;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_19;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_27;
							if (!(res_2 <= ((NI)3))) goto LA6;
							j_1 = ((NI) (res_2));
							if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_18)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_18), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_19)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19), 15); goto BeforeRet_;
							}
							Result[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_19))- 0] = 0.0f;
							{
								NI k_1;
								NI res_3;
								k_1 = (NI)0;
								res_3 = ((NI)0);
								{
									while (1) {
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_20;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_21;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_22;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_23;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_24;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_25;
										NI TM__0AG1Bhfktbzesi9cL0Iv9bng_26;
										if (!(res_3 <= ((NI)3))) goto LA9;
										k_1 = ((NI) (res_3));
										if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_20)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_20), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_21)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21), 15); goto BeforeRet_;
										}
										if (nimMulInt(k_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_22)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_22), j_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_23)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23), 15); goto BeforeRet_;
										}
										if (nimMulInt(i_1, ((NI)4), &TM__0AG1Bhfktbzesi9cL0Iv9bng_24)) { raiseOverflow(); goto BeforeRet_;
										};
										if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_24), k_1, &TM__0AG1Bhfktbzesi9cL0Iv9bng_25)) { raiseOverflow(); goto BeforeRet_;
										};
										if ((NU)((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25)) > (NU)(15)){ raiseIndexError2((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25), 15); goto BeforeRet_;
										}
										pluseq___platformZrender3d95interface_u185((&Result[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_21))- 0]), ((NF32)(a_p0[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_23))- 0]) * (NF32)(b_p1[((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_25))- 0])));
										if (nimAddInt(res_3, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_26)) { raiseOverflow(); goto BeforeRet_;
										};
										res_3 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_26);
									} LA9: ;
								}
							}
							if (nimAddInt(res_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_27)) { raiseOverflow(); goto BeforeRet_;
							};
							res_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_27);
						} LA6: ;
					}
				}
				if (nimAddInt(res_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_28)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_28);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, translate__platformZrender3d95interface_u141)(NF32 x_p0, NF32 y_p1, NF32 z_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)12))- 0] = x_p0;
	Result[(((NI)13))- 0] = y_p1;
	Result[(((NI)14))- 0] = z_p2;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rotateX__platformZrender3d95interface_u151)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	c_1 = cosf(angle_p0);
	s_1 = sinf(angle_p0);
	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)5))- 0] = c_1;
	Result[(((NI)6))- 0] = s_1;
	Result[(((NI)9))- 0] = -(s_1);
	Result[(((NI)10))- 0] = c_1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rotateY__platformZrender3d95interface_u156)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	c_1 = cosf(angle_p0);
	s_1 = sinf(angle_p0);
	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)0))- 0] = c_1;
	Result[(((NI)2))- 0] = -(s_1);
	Result[(((NI)8))- 0] = s_1;
	Result[(((NI)10))- 0] = c_1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rotateZ__platformZrender3d95interface_u161)(NF32 angle_p0, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
	NF32 c_1;
	NF32 s_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	c_1 = cosf(angle_p0);
	s_1 = sinf(angle_p0);
	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)0))- 0] = c_1;
	Result[(((NI)1))- 0] = s_1;
	Result[(((NI)4))- 0] = -(s_1);
	Result[(((NI)5))- 0] = c_1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, scale__platformZrender3d95interface_u146)(NF32 x_p0, NF32 y_p1, NF32 z_p2, tyArray__EH3vwk2gvJbf6WGsCM9baJQ Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__EH3vwk2gvJbf6WGsCM9baJQ));
	identity__platformZrender3d95interface_u105(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Result[(((NI)0))- 0] = x_p0;
	Result[(((NI)5))- 0] = y_p1;
	Result[(((NI)10))- 0] = z_p2;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___storie_u273)(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg* dest_p0) {
	eqdestroy___platformZrender3d95interface_u437((*dest_p0).indices);
	eqdestroy___platformZrender3d95interface_u314((*dest_p0).vertices);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg, createCubeMeshData__platformZrender3d95interface_u298)(NF32 size_p0, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ color_p1) {
	tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg result;
	NF32 colontmpD_;
	NF32 colontmpD__2;
	NF32 colontmpD__3;
	NF32 colontmpD__4;
	NF32 colontmpD__5;
	NF32 colontmpD__6;
	NF32 colontmpD__7;
	NF32 colontmpD__8;
	NF32 colontmpD__9;
	NF32 colontmpD__10;
	NF32 colontmpD__11;
	NF32 colontmpD__12;
	NF32 colontmpD__13;
	NF32 colontmpD__14;
	NF32 colontmpD__15;
	NF32 colontmpD__16;
	NF32 colontmpD__17;
	NF32 colontmpD__18;
	NF32 colontmpD__19;
	NF32 colontmpD__20;
	NF32 colontmpD__21;
	NF32 colontmpD__22;
	NF32 colontmpD__23;
	NF32 colontmpD__24;
	NF32 s_1;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ T1_;
	tySequence__uFLLGQVsiasALrzzzvqnZw T2_;
	nimZeroMem((void*)(&result), sizeof(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg));
	colontmpD_ = (NF32)0;
	colontmpD__2 = (NF32)0;
	colontmpD__3 = (NF32)0;
	colontmpD__4 = (NF32)0;
	colontmpD__5 = (NF32)0;
	colontmpD__6 = (NF32)0;
	colontmpD__7 = (NF32)0;
	colontmpD__8 = (NF32)0;
	colontmpD__9 = (NF32)0;
	colontmpD__10 = (NF32)0;
	colontmpD__11 = (NF32)0;
	colontmpD__12 = (NF32)0;
	colontmpD__13 = (NF32)0;
	colontmpD__14 = (NF32)0;
	colontmpD__15 = (NF32)0;
	colontmpD__16 = (NF32)0;
	colontmpD__17 = (NF32)0;
	colontmpD__18 = (NF32)0;
	colontmpD__19 = (NF32)0;
	colontmpD__20 = (NF32)0;
	colontmpD__21 = (NF32)0;
	colontmpD__22 = (NF32)0;
	colontmpD__23 = (NF32)0;
	colontmpD__24 = (NF32)0;
	s_1 = ((NF32)(size_p0) / (NF32)(2.0f));
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 48; T1_.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(48, sizeof(NF32), NIM_ALIGNOF(NF32));
	T1_.p->data[0] = -(s_1);
	T1_.p->data[1] = -(s_1);
	T1_.p->data[2] = s_1;
	colontmpD_ = color_p1.x;
	T1_.p->data[3] = colontmpD_;
	colontmpD__2 = color_p1.y;
	T1_.p->data[4] = colontmpD__2;
	colontmpD__3 = color_p1.z;
	T1_.p->data[5] = colontmpD__3;
	T1_.p->data[6] = s_1;
	T1_.p->data[7] = -(s_1);
	T1_.p->data[8] = s_1;
	colontmpD__4 = color_p1.x;
	T1_.p->data[9] = colontmpD__4;
	colontmpD__5 = color_p1.y;
	T1_.p->data[10] = colontmpD__5;
	colontmpD__6 = color_p1.z;
	T1_.p->data[11] = colontmpD__6;
	T1_.p->data[12] = s_1;
	T1_.p->data[13] = s_1;
	T1_.p->data[14] = s_1;
	colontmpD__7 = color_p1.x;
	T1_.p->data[15] = colontmpD__7;
	colontmpD__8 = color_p1.y;
	T1_.p->data[16] = colontmpD__8;
	colontmpD__9 = color_p1.z;
	T1_.p->data[17] = colontmpD__9;
	T1_.p->data[18] = -(s_1);
	T1_.p->data[19] = s_1;
	T1_.p->data[20] = s_1;
	colontmpD__10 = color_p1.x;
	T1_.p->data[21] = colontmpD__10;
	colontmpD__11 = color_p1.y;
	T1_.p->data[22] = colontmpD__11;
	colontmpD__12 = color_p1.z;
	T1_.p->data[23] = colontmpD__12;
	T1_.p->data[24] = -(s_1);
	T1_.p->data[25] = -(s_1);
	T1_.p->data[26] = -(s_1);
	colontmpD__13 = color_p1.x;
	T1_.p->data[27] = colontmpD__13;
	colontmpD__14 = color_p1.y;
	T1_.p->data[28] = colontmpD__14;
	colontmpD__15 = color_p1.z;
	T1_.p->data[29] = colontmpD__15;
	T1_.p->data[30] = s_1;
	T1_.p->data[31] = -(s_1);
	T1_.p->data[32] = -(s_1);
	colontmpD__16 = color_p1.x;
	T1_.p->data[33] = colontmpD__16;
	colontmpD__17 = color_p1.y;
	T1_.p->data[34] = colontmpD__17;
	colontmpD__18 = color_p1.z;
	T1_.p->data[35] = colontmpD__18;
	T1_.p->data[36] = s_1;
	T1_.p->data[37] = s_1;
	T1_.p->data[38] = -(s_1);
	colontmpD__19 = color_p1.x;
	T1_.p->data[39] = colontmpD__19;
	colontmpD__20 = color_p1.y;
	T1_.p->data[40] = colontmpD__20;
	colontmpD__21 = color_p1.z;
	T1_.p->data[41] = colontmpD__21;
	T1_.p->data[42] = -(s_1);
	T1_.p->data[43] = s_1;
	T1_.p->data[44] = -(s_1);
	colontmpD__22 = color_p1.x;
	T1_.p->data[45] = colontmpD__22;
	colontmpD__23 = color_p1.y;
	T1_.p->data[46] = colontmpD__23;
	colontmpD__24 = color_p1.z;
	T1_.p->data[47] = colontmpD__24;
	eqsink___platformZrender3d95interface_u323((&result.vertices), T1_);
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 36; T2_.p = (tySequence__uFLLGQVsiasALrzzzvqnZw_Content*) newSeqPayload(36, sizeof(NU16), NIM_ALIGNOF(NU16));
	T2_.p->data[0] = ((NU16)0);
	T2_.p->data[1] = ((NU16)1);
	T2_.p->data[2] = ((NU16)2);
	T2_.p->data[3] = ((NU16)2);
	T2_.p->data[4] = ((NU16)3);
	T2_.p->data[5] = ((NU16)0);
	T2_.p->data[6] = ((NU16)1);
	T2_.p->data[7] = ((NU16)5);
	T2_.p->data[8] = ((NU16)6);
	T2_.p->data[9] = ((NU16)6);
	T2_.p->data[10] = ((NU16)2);
	T2_.p->data[11] = ((NU16)1);
	T2_.p->data[12] = ((NU16)5);
	T2_.p->data[13] = ((NU16)4);
	T2_.p->data[14] = ((NU16)7);
	T2_.p->data[15] = ((NU16)7);
	T2_.p->data[16] = ((NU16)6);
	T2_.p->data[17] = ((NU16)5);
	T2_.p->data[18] = ((NU16)4);
	T2_.p->data[19] = ((NU16)0);
	T2_.p->data[20] = ((NU16)3);
	T2_.p->data[21] = ((NU16)3);
	T2_.p->data[22] = ((NU16)7);
	T2_.p->data[23] = ((NU16)4);
	T2_.p->data[24] = ((NU16)3);
	T2_.p->data[25] = ((NU16)2);
	T2_.p->data[26] = ((NU16)6);
	T2_.p->data[27] = ((NU16)6);
	T2_.p->data[28] = ((NU16)7);
	T2_.p->data[29] = ((NU16)3);
	T2_.p->data[30] = ((NU16)4);
	T2_.p->data[31] = ((NU16)5);
	T2_.p->data[32] = ((NU16)1);
	T2_.p->data[33] = ((NU16)1);
	T2_.p->data[34] = ((NU16)0);
	T2_.p->data[35] = ((NU16)4);
	eqsink___platformZrender3d95interface_u446((&result.indices), T2_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg, createSphereMeshData__platformZrender3d95interface_u557)(NF32 radius_p0, NI segments_p1, tyObject_Vec3__VCo9cHwfJBy7PoQQx3Ag2GQ color_p2) {
	tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg result;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ T1_;
	tySequence__uFLLGQVsiasALrzzzvqnZw T2_;
{	nimZeroMem((void*)(&result), sizeof(tyObject_MeshData__i0o8rU9aTRm2iFbbx6dAfdg));
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 0; T1_.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(0, sizeof(NF32), NIM_ALIGNOF(NF32));
	eqsink___platformZrender3d95interface_u323((&result.vertices), T1_);
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 0; T2_.p = (tySequence__uFLLGQVsiasALrzzzvqnZw_Content*) newSeqPayload(0, sizeof(NU16), NIM_ALIGNOF(NU16));
	eqsink___platformZrender3d95interface_u446((&result.indices), T2_);
	{
		NI lat_1;
		NI res_1;
		lat_1 = (NI)0;
		res_1 = ((NI)0);
		{
			while (1) {
				NF theta_1;
				NF sinTheta_1;
				NF cosTheta_1;
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_30;
				if (!(res_1 <= segments_p1)) goto LA5;
				lat_1 = ((NI) (res_1));
				theta_1 = ((NF)(((NF) (((NF32)(((NF32) (lat_1))) / (NF32)(((NF32) (segments_p1))))))) * (NF)(3.141592653589793));
				sinTheta_1 = sin(theta_1);
				cosTheta_1 = cos(theta_1);
				{
					NI lon_1;
					NI res_2;
					lon_1 = (NI)0;
					res_2 = ((NI)0);
					{
						while (1) {
							NF32 colontmpD_;
							NF32 colontmpD__2;
							NF32 colontmpD__3;
							NF phi_1;
							NF sinPhi_1;
							NF cosPhi_1;
							NF x_1;
							NF y_1;
							NF z_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_29;
							if (!(res_2 <= segments_p1)) goto LA8;
							colontmpD_ = (NF32)0;
							colontmpD__2 = (NF32)0;
							colontmpD__3 = (NF32)0;
							lon_1 = ((NI) (res_2));
							phi_1 = ((NF)(((NF)(((NF) (((NF32)(((NF32) (lon_1))) / (NF32)(((NF32) (segments_p1))))))) * (NF)(2.0))) * (NF)(3.141592653589793));
							sinPhi_1 = sin(phi_1);
							cosPhi_1 = cos(phi_1);
							x_1 = ((NF)(cosPhi_1) * (NF)(sinTheta_1));
							y_1 = cosTheta_1;
							z_1 = ((NF)(sinPhi_1) * (NF)(sinTheta_1));
							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(x_1) * (NF)(((NF) (radius_p0)))))));
							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(y_1) * (NF)(((NF) (radius_p0)))))));
							add__platformZrender3d95interface_u589((&result.vertices), ((NF32) (((NF)(z_1) * (NF)(((NF) (radius_p0)))))));
							colontmpD_ = color_p2.x;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD_);
							colontmpD__2 = color_p2.y;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD__2);
							colontmpD__3 = color_p2.z;
							add__platformZrender3d95interface_u589((&result.vertices), colontmpD__3);
							if (nimAddInt(res_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_29)) { raiseOverflow(); goto BeforeRet_;
							};
							res_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_29);
						} LA8: ;
					}
				}
				if (nimAddInt(res_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_30)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_30);
			} LA5: ;
		}
	}
	{
		NI lat_2;
		NI i_1;
		lat_2 = (NI)0;
		i_1 = ((NI)0);
		{
			while (1) {
				NI TM__0AG1Bhfktbzesi9cL0Iv9bng_36;
				if (!(i_1 < segments_p1)) goto LA11;
				lat_2 = i_1;
				{
					NI lon_2;
					NI i_2;
					lon_2 = (NI)0;
					i_2 = ((NI)0);
					{
						while (1) {
							NU16 first_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_31;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_32;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_33;
							NU16 second_1;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_34;
							NI TM__0AG1Bhfktbzesi9cL0Iv9bng_35;
							if (!(i_2 < segments_p1)) goto LA14;
							lon_2 = i_2;
							if (nimAddInt(segments_p1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_31)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimMulInt(lat_2, (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_31), &TM__0AG1Bhfktbzesi9cL0Iv9bng_32)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_32), lon_2, &TM__0AG1Bhfktbzesi9cL0Iv9bng_33)) { raiseOverflow(); goto BeforeRet_;
							};
							first_1 = ((NU16) ((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_33)));
							if (nimAddInt(segments_p1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_34)) { raiseOverflow(); goto BeforeRet_;
							};
							second_1 = (NU16)((NU16)(first_1) + (NU16)(((NU16) ((NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_34)))));
							add__platformZrender3d95interface_u641((&result.indices), first_1);
							add__platformZrender3d95interface_u641((&result.indices), second_1);
							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(first_1) + (NU16)(((NU16)1))));
							add__platformZrender3d95interface_u641((&result.indices), second_1);
							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(second_1) + (NU16)(((NU16)1))));
							add__platformZrender3d95interface_u641((&result.indices), (NU16)((NU16)(first_1) + (NU16)(((NU16)1))));
							if (nimAddInt(i_2, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_35)) { raiseOverflow(); goto BeforeRet_;
							};
							i_2 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_35);
						} LA14: ;
					}
				}
				if (nimAddInt(i_1, ((NI)1), &TM__0AG1Bhfktbzesi9cL0Iv9bng_36)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__0AG1Bhfktbzesi9cL0Iv9bng_36);
			} LA11: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
